import { chromium } from '../../webpage/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { serve } from './serve.mjs';
const server=await serve(0),port=server.address().port;
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(`http://127.0.0.1:${port}`);
await page.waitForFunction(()=>document.querySelector('video').readyState>=1);
const media=await page.locator('video').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,error:v.error}));
assert.equal(media.duration,30);assert.equal(media.width,1920);assert.equal(media.height,1080);assert.equal(media.error,null);
await page.getByRole('button',{name:'18—27 VITALIS 실제 데모'}).click();
await page.waitForFunction(()=>document.querySelector('video').currentTime>18.2);
await page.locator('video').evaluate(v=>v.pause());
assert.equal(await page.locator('.chapter.active').getAttribute('data-time'),'18');
await page.locator('video').evaluate(v=>{v.textTracks[0].mode='hidden';});
await page.waitForFunction(()=>document.querySelector('video').textTracks[0].cues?.length===10);
await page.screenshot({path:'output/preview-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'output/preview-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
await writeFile('output/playback-check.json',JSON.stringify({media,chapterSeeking:true,playbackAdvances:true,captionCues:10,mobileOverflow:false,browserErrors:errors},null,2));
await browser.close();server.close();console.log('PASS: 30s / 1080p / playback / chapter seek / Korean captions / mobile layout.');
