import {assertGameResult} from './assert-result.mjs';
import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_PATH?pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href:'playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:4188',out=process.env.EVIDENCE_DIR||'evidence';await mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
const excludedMaps=(process.env.EXCLUDE_MAPS||'').split(',').filter(Boolean),testedMaps=['neon','orbit','zigzag','split','parade'].filter(id=>!excludedMaps.includes(id));assert.ok(testedMaps.length);
const report={at:new Date().toISOString(),browser:browser.version(),tests:[],performance:[],excludedMaps,limitations:['Mobile Chrome viewport emulation, not a physical phone.','Synthesized audio scheduling tested without human speaker listening.','No Safari/Firefox or native WebMCP browser tested.','Cross-runtime bit-exact replay is not supported: Node vs Chrome floating-point differences can diverge through collisions.']};
const shot=(p,f)=>p.screenshot({path:`${out}/${f}.png`,fullPage:true});const snap=p=>p.evaluate(()=>window.pinball.snapshot());
async function finish(p,name){await p.waitForFunction(()=>['complete','invalid'].includes(document.body.dataset.state),null,{timeout:110000});const s=await snap(p);if(s.state==='invalid')await writeFile(`${out}/${name}-invalid-round.json`,JSON.stringify(await p.evaluate(()=>window.pinball.exportRound()),null,2));assertGameResult(s);const ids=await p.locator('#ranking li').evaluateAll(es=>es.map(e=>e.dataset.ballId));assert.deepEqual(ids,s.finishOrder.map(x=>x.id));assert.equal(await p.locator('#winner-name').textContent(),s.winner.label);const round=await p.evaluate(()=>window.pinball.exportRound());await writeFile(`${out}/${name}-round.json`,JSON.stringify(round,null,2));const replay=await p.evaluate(async round=>{const {Race}=await import(window.pinball.settings().physicsModule||'/src/physics.js');const replay=new Race(round.config,round.seed);replay.start();while(!['complete','invalid'].includes(replay.state))replay.step();return replay.finishOrder;},round);assert.deepEqual(replay,s.finishOrder,'Same-browser replay without rendering, pauses or slow motion must match the visible race');return s;}
async function run(name,options,fn,trace=false){const c=await browser.newContext({viewport:{width:1440,height:1000},...options});const errors=[],external=[];await c.route('**/*',r=>{if(new URL(r.request().url()).origin!==new URL(base).origin){external.push(r.request().url());return r.abort();}return r.continue();});await c.addInitScript(()=>{window.__audioStarts=0;const original=window.AudioContext?.prototype.createOscillator;if(original)AudioContext.prototype.createOscillator=function(){window.__audioStarts++;return original.call(this);};});if(trace)await c.tracing.start({screenshots:true,snapshots:true,sources:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='error')errors.push(e.text());});const t=Date.now();try{await p.goto(base);await p.waitForFunction(()=>window.pinball);await fn(p);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);report.tests.push({name,status:'PASS',ms:Date.now()-t,errors,external});console.log('PASS',name);}catch(e){report.tests.push({name,status:'FAIL',ms:Date.now()-t,error:e.stack,errors,external});console.error('FAIL',name,e.stack);await shot(p,`failure-${report.tests.length}`).catch(()=>{});}finally{if(trace)await c.tracing.stop({path:`${out}/${options.isMobile?'mobile':'desktop'}-trace.zip`});await c.close();await writeFile(`${out}/browser-results.json`,JSON.stringify(report,null,2));}}
await run('PC inputs: empty/duplicates/long names/counts/N-range/XSS/individual count',{},async p=>{
 assert.equal((await snap(p)).total,5);assert.equal((await p.evaluate(()=>window.pinball.settings())).renderer,'webgl');assert.equal(await p.locator('.roster-row').count(),5);await shot(p,'desktop-setup');
 for(const text of ['', ' , ', '가'.repeat(41), 'A*0','A*-1','A*11','A*1.5','A*abc','A*',Array.from({length:61},(_,i)=>i).join(',')]){await p.locator('#participants').fill(text);await p.locator('#start').click();assert.ok(await p.locator('#input-error').textContent());assert.equal((await snap(p)).state,'ready');}
 await p.locator('#participants').fill('동일,동일,아주긴이름'.repeat(1)+',<b>안전</b>');assert.equal((await snap(p)).total,4);assert.ok(await p.locator('#roster').textContent().then(s=>s.includes('동일 (2)')));assert.equal(await p.locator('#roster b').count(),0);
 await p.locator('#roster-details summary').click();await p.locator('#count-0').fill('3');assert.equal((await snap(p)).total,6);await p.locator('#count-0').fill('0');await p.locator('#start').click();assert.match(await p.locator('#input-error').textContent(),/공 개수/);await p.locator('#count-0').fill('2');assert.equal((await snap(p)).total,5);
 for(const count of ['', '0','-1','11','1.5','abc','1e1']){await p.locator('#default-count').fill(count);await p.locator('#start').click();assert.ok(await p.locator('#input-error').textContent());}await p.locator('#default-count').fill('1');await p.locator('input[name=rule][value=nth]').check();for(const n of ['0','5','-1','','1.2','abc']){await p.locator('#nth').fill(n);await p.locator('#start').click();assert.ok(await p.locator('#input-error').textContent());}await p.locator('#nth').fill('4');assert.equal((await snap(p)).target,4);
 await p.locator('#participants').fill('가'.repeat(40)+',두번째');assert.equal((await snap(p)).total,4); // invalid N leaves the previous ready snapshot; start must still reject it.
 await p.locator('#nth').fill('2');assert.equal((await snap(p)).total,2);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
});
await run('PC end-to-end: 20 balls, first winner, rapid clicks, pause/resume, replay',{},async p=>{
 await p.locator('#sample').click();assert.equal((await snap(p)).total,20);await p.locator('#sound').click();await p.locator('#start').evaluate(e=>{for(let i=0;i<25;i++)e.dispatchEvent(new MouseEvent('click',{bubbles:true}));});const id=(await snap(p)).roundId;assert.equal((await snap(p)).state,'mixing');assert.equal(await p.locator('#participants').isDisabled(),true);assert.equal(await p.locator('.map-choice').first().isDisabled(),true);
 await p.locator('#pause').click();const paused=await snap(p);await p.waitForTimeout(400);assert.deepEqual(await snap(p),paused);await p.locator('#pause').click();await p.waitForFunction(()=>document.body.dataset.state==='countdown');assert.equal(await p.locator('#countdown').isVisible(),true);await p.waitForFunction(()=>document.body.dataset.state==='racing');await p.waitForTimeout(2400);await shot(p,'desktop-racing');await p.locator('#pause').click();const pausedRace=await snap(p);await p.waitForTimeout(300);assert.deepEqual(await snap(p),pausedRace);await p.locator('#pause').click();const s=await finish(p,'desktop-first');assert.equal(s.roundId,id);assert.equal(s.target,1);assert.ok(await p.evaluate(()=>window.__audioStarts)>4);await shot(p,'desktop-result');
 await p.locator('#start').click();assert.notEqual((await snap(p)).roundId,id);assert.equal((await snap(p)).finishOrder.length,0);await p.locator('#reset').click();assert.equal((await snap(p)).state,'ready');assert.equal(await p.locator('#participants').isDisabled(),false);
},true);
await run(`${testedMaps.length} map selection and real 60-ball maximum performance, last winner`,{reducedMotion:'reduce'},async p=>{
 await p.locator('#participants').fill(Array.from({length:60},(_,i)=>`번호 ${i+1}`).join(','));await p.locator('input[name=rule][value=last]').check();
 for(const mapId of testedMaps){
  await p.locator(`[data-map=${mapId}]`).click();assert.equal(await p.locator(`[data-map=${mapId}]`).getAttribute('aria-pressed'),'true');await p.locator('#view').click();await shot(p,`map-${mapId}`);await p.locator('#view').click();await p.locator('#start').click();await p.waitForFunction(()=>document.body.dataset.state==='racing');await p.waitForTimeout(5500);const perf=await p.evaluate(()=>window.pinball.performance());const samples=perf.samples.filter(s=>s.state==='racing'&&s.total===60&&s.delta>0);const costs=samples.map(s=>s.cost).sort((a,b)=>a-b),deltas=samples.map(s=>s.delta).sort((a,b)=>a-b);report.performance.push({map:mapId,device:'desktop 1440x1000',balls:60,samples:samples.length,meanFrameCostMs:costs.reduce((a,b)=>a+b,0)/costs.length,p95FrameCostMs:costs[Math.floor(costs.length*.95)],p95FrameIntervalMs:deltas[Math.floor(deltas.length*.95)],fps:1000/(deltas.reduce((a,b)=>a+b,0)/deltas.length)});const s=await finish(p,`max-${mapId}`);assert.equal(s.target,60);await p.locator('#edit').click();
 }
});
await run('Mobile 390x844 touch: per-person balls → Nth → pause → result → replay',{viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true},async p=>{
 await p.locator('#participants').fill('모바일 A*2,모바일 B,모바일 C');await p.locator('input[name=rule][value=nth]').check();await p.locator('#nth').fill('3');await p.locator('[data-map=orbit]').tap();assert.equal((await snap(p)).total,4);await shot(p,'mobile-setup');await p.locator('#start').tap();await p.waitForFunction(()=>document.body.dataset.state==='racing');await p.waitForTimeout(1500);await p.locator('#pause').tap();const a=await snap(p);await p.waitForTimeout(300);assert.deepEqual(await snap(p),a);await p.locator('#pause').tap();await shot(p,'mobile-racing');const s=await finish(p,'mobile-nth');assert.equal(s.target,3);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#winner-card').scrollIntoViewIfNeeded();await shot(p,'mobile-result');await p.locator('#winner-card').screenshot({path:`${out}/mobile-result-detail.png`});await p.locator('#start').tap();assert.equal((await snap(p)).state,'mixing');await p.locator('#reset').tap();assert.equal((await snap(p)).state,'ready');
},true);
await run('Mobile maximum: 60 balls, reduced motion and frame timing',{viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,reducedMotion:'reduce'},async p=>{
 assert.equal(await p.locator('#motion').getAttribute('aria-pressed'),'true');await p.locator('#participants').fill(Array.from({length:60},(_,i)=>`공 ${i+1}`).join(','));await p.locator('#start').tap();await p.waitForFunction(()=>document.body.dataset.state==='racing');await p.waitForTimeout(5500);const perf=await p.evaluate(()=>window.pinball.performance()),s=perf.samples.filter(s=>s.state==='racing'&&s.total===60&&s.delta>0);const costs=s.map(s=>s.cost).sort((a,b)=>a-b),d=s.map(s=>s.delta).sort((a,b)=>a-b);report.performance.push({map:'neon',device:'mobile emulation 390x844 DPR2',balls:60,samples:s.length,meanFrameCostMs:costs.reduce((a,b)=>a+b,0)/costs.length,p95FrameCostMs:costs[Math.floor(costs.length*.95)],p95FrameIntervalMs:d[Math.floor(d.length*.95)],fps:1000/(d.reduce((a,b)=>a+b,0)/d.length)});await finish(p,'mobile-max');assert.equal(await p.locator('.confetti-piece').count(),0);
});
await run('Responsive, keyboard, mute, visibility pause',{},async p=>{
 for(const width of [320,768,1024]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow ${width}`);}await p.setViewportSize({width:1440,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#sound').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#sound').getAttribute('aria-pressed'),'true');await p.locator('#sound').click();const tones=await p.evaluate(()=>window.__audioStarts);await p.locator('#start').click();await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>window.__audioStarts),tones);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal((await snap(p)).state,'paused');await p.locator('#reset').click();
});
await browser.close();await writeFile(`${out}/browser-results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.tests.filter(t=>t.status==='PASS').length,failed:report.tests.filter(t=>t.status==='FAIL').length,performance:report.performance},null,2));if(report.tests.some(t=>t.status==='FAIL'))process.exitCode=1;
