import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {assertGameResult} from './assert-result.mjs';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href),browser=await chromium.launch({channel:'chrome'}),report={at:new Date().toISOString(),tests:[]};
try{for(const mobile of [false,true]){
 const device=mobile?'mobile':'desktop',c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile,reducedMotion:'reduce'});
 await c.addInitScript(()=>{crypto.getRandomValues=a=>{for(let i=0;i<a.length;i++)a[i]=11;return a;};});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.BASE_URL||'http://127.0.0.1:4189');await p.waitForFunction(()=>window.pinball);
 assert.equal((await p.evaluate(()=>window.pinball.settings())).playbackSpeed,1.5);assert.equal(await p.locator('[data-speed="1.5"]').getAttribute('aria-pressed'),'true');
 await p.locator('#participants').fill(Array.from({length:60},(_,i)=>`탑승객 ${i+1}`).join('\n'));await p.locator('input[value=last]').check();await p.locator('#focus-mode').click();await p.locator('#arena-start').click();
 await p.waitForFunction(()=>window.pinball.snapshot().devices.some(d=>d.kind==='magnet'&&d.holding),null,{timeout:40000});await p.locator('#pause').click();const magnet=await p.evaluate(()=>window.pinball.snapshot());await p.waitForTimeout(170);assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),magnet);await p.locator('#board').screenshot({path:`evidence/park-20260921/09-${device}-magnet.png`});await p.locator('#pause').click();
 await p.waitForFunction(()=>window.pinball.snapshot().devices.some(d=>d.kind==='cannon'&&d.holding),null,{timeout:60000});await p.locator('#pause').click();const cannon=await p.evaluate(()=>window.pinball.snapshot());assert.ok(cannon.devices.some(d=>d.kind==='cannon'&&d.holding));await p.waitForTimeout(180);assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),cannon);await p.locator('#board').screenshot({path:`evidence/park-20260921/09-${device}-cannon.png`});
 await p.locator('[data-speed="3"]').click();assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),cannon);await p.locator('#pause').click();await p.waitForFunction(()=>window.pinball.snapshot().state==='complete',null,{timeout:70000});
 const round=await p.evaluate(()=>window.pinball.exportRound());assertGameResult(round.result);assert.ok(round.result.deviceStats.captures>0&&round.result.deviceStats.launches>0);assert.ok(round.result.finishOrder.every(r=>r.exitId===1));
 const replay=await p.evaluate(async round=>{const {Race}=await import(window.pinball.settings().physicsModule);const r=new Race(round.config,round.seed);r.start();while(!['complete','invalid'].includes(r.state))r.step();const {roundId,...s}=r.snapshot();return s;},round);const {roundId,...actual}=round.result;assert.deepEqual(actual,replay);
 await p.screenshot({path:`evidence/park-20260921/09-${device}-winner.png`,fullPage:true});await p.locator('#splash-replay').click();assert.equal((await p.evaluate(()=>window.pinball.snapshot())).deviceStats.captures,0);assert.equal((await p.evaluate(()=>window.pinball.settings())).playbackSpeed,3);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);report.tests.push({device,status:'PASS',defaultSpeed:1.5,capturePause:'PASS',speedChangeDuringHold:'PASS',sameBrowserExactReplay:'PASS',deviceStats:actual.deviceStats,finishCount:actual.finishOrder.length,exitIds:[...new Set(actual.finishOrder.map(r=>r.exitId))],errors});console.log('PASS actual devices',report.tests.at(-1));await c.close();
}report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;console.error(e);}finally{await writeFile('evidence/park-20260921/09-devices-browser-results.json',JSON.stringify(report,null,2));await browser.close();}
