import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const prefix=process.env.EVIDENCE_PREFIX||'17';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href),browser=await chromium.launch({channel:'chrome'}),report={at:new Date().toISOString(),tests:[],status:'RUNNING'};
try{for(const mobile of [false,true]){
 const device=mobile?'mobile':'desktop',c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},deviceScaleFactor:mobile?2:1,isMobile:mobile,hasTouch:mobile,reducedMotion:'reduce'});await c.addInitScript(()=>{crypto.getRandomValues=a=>{for(let i=0;i<a.length;i++)a[i]=1201;return a;};});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.BASE_URL||'http://127.0.0.1:4189');await p.waitForFunction(()=>window.pinball);assert.equal((await p.evaluate(()=>window.pinball.snapshot())).total,5);
 await p.locator('#participants').fill('지우*3,현우,지우');assert.equal((await p.evaluate(()=>window.pinball.snapshot())).total,5);assert.match(await p.locator('#roster').textContent(),/지우 \(2\)/);
 await p.locator('#tab-player').focus();await p.keyboard.press('ArrowRight');assert.equal((await p.evaluate(()=>window.pinball.settings())).gameMode,'lotto');await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#participants').inputValue(),'지우*3,현우,지우');
 await p.locator('#tab-lotto').click();assert.equal(await p.locator('#player-options').isVisible(),false);assert.equal(await p.locator('#lotto-options').isVisible(),true);assert.equal((await p.evaluate(()=>window.pinball.snapshot())).total,45);const cfg=await p.evaluate(()=>window.pinball.exportRound().config);assert.ok(cfg.people.every((x,i)=>x.name===String(i+1)&&x.count===1));await p.locator('[data-map=parade]').click();await p.locator('[data-speed="3"]').click();
 for(const order of ['first','last']){
  await p.locator(`input[name=lotto-rule][value=${order}]`).check();await p.locator('#start').click();assert.equal(await p.locator('#tab-player').isDisabled(),true);assert.equal(await p.locator(`input[name=lotto-rule][value=${order}]`).isDisabled(),true);await p.waitForFunction(()=>window.pinball.snapshot().state==='racing');await p.locator('#pause').click();const paused=await p.evaluate(()=>window.pinball.snapshot());await p.waitForTimeout(180);assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),paused);await p.locator('#half-view').click();assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),paused);await p.screenshot({path:`evidence/park-20260921/${prefix}-lotto-${device}-${order}-paused.png`});await p.locator('#pause').click();await p.waitForFunction(()=>['complete','invalid'].includes(document.body.dataset.state),null,{timeout:90000});
  const round=await p.evaluate(()=>window.pinball.exportRound()),s=round.result,l=round.lotto;assert.equal(s.state,'complete');assert.equal(s.finishOrder.length,order==='first'?7:44);assert.equal(new Set([...l.numbers,l.bonus]).size,7);assert.equal(l.bonusArrived,order==='first');assert.deepEqual(await p.locator('#splash-lotto .lotto-main b').allTextContents(),l.numbers.map(String));assert.equal(await p.locator('#splash-lotto .lotto-bonus b').textContent(),String(l.bonus));if(order==='last'){assert.equal(s.winner.crossedFinish,false);assert.ok(!s.finishOrder.some(x=>+x.name===l.bonus));}await p.screenshot({path:`evidence/park-20260921/${prefix}-lotto-${device}-${order}-result.png`});
  const replay=await p.evaluate(async round=>{const {Race}=await import(window.pinball.settings().physicsModule);const r=new Race(round.config,round.seed);r.start();while(!['complete','invalid'].includes(r.state))r.step();const {roundId,...rest}=r.snapshot();return rest;},round);const {roundId,...actual}=s;assert.deepEqual(actual,replay);await p.locator('#splash-close').click();assert.equal(await p.locator('#winner-caption').textContent(),order==='first'?'처음 6개 + 보너스':'마지막 6개 + 보너스');assert.deepEqual(await p.locator('#winner-lotto .lotto-main b').allTextContents(),l.numbers.map(String));assert.equal((await p.evaluate(()=>window.pinball.settings())).focusMode,false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await writeFile(`evidence/park-20260921/${prefix}-lotto-${device}-${order}-round.json`,JSON.stringify(round,null,2));report.tests.push({device,order,status:'PASS',numbers:l.numbers,bonus:l.bonus,arrivals:s.finishOrder.length,exactReplay:true});console.log('PASS lotto',device,order,l);await p.locator('#edit').click();assert.equal(await p.evaluate(()=>document.activeElement.name),'lotto-rule');
 }
 await p.locator('#tab-player').click();assert.equal(await p.locator('#participants').inputValue(),'지우*3,현우,지우');assert.equal((await p.evaluate(()=>window.pinball.snapshot())).total,5);assert.equal(await p.locator('#winner-lotto').isVisible(),false);assert.deepEqual(errors,[]);await c.close();
}report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;console.error(e);}finally{await writeFile(`evidence/park-20260921/${prefix}-lotto-browser-results.json`,JSON.stringify(report,null,2));await browser.close();}
