import test from 'node:test';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
import {Race,makeConfig,parseParticipants,MAPS,STEP} from '../src/physics.js';
const names=n=>Array.from({length:n},(_,i)=>`참가 ${i+1}`).join(',');const cfg=(n=20,rule='first',rank=1,mapId='neon')=>({...makeConfig(names(n),1,rule,rank),mapId});const done=r=>['complete','invalid'].includes(r.state);const run=r=>{r.start();while(!done(r))r.step();return r;};
test('participants: defaults, explicit counts, duplicate labels, Unicode and literal markup',()=>{const p=parseParticipants('하늘*3,민준,하늘,<b>이름</b>,,');assert.deepEqual(p.map(x=>x.count),[3,1,1,1]);assert.equal(p[2].label,'하늘 (2)');assert.equal(new Set(p.map(x=>x.id)).size,4);assert.equal(parseParticipants('🌟'.repeat(40))[0].name.length,80);});
test('reject empty, long, excessive and invalid counts without silently clamping',()=>{for(const text of ['', ' , ', '가'.repeat(41),names(61),'A*0','A*11','A*1.5','A*-1','A*abc','A*','A*1*2','A*1e1',names(7).split(',').map(n=>n+'*10').join(',')])assert.throws(()=>parseParticipants(text));for(const count of ['',0,11,-1,'1.2','2e0','NaN','Infinity'])assert.throws(()=>parseParticipants('A',count));});
test('rule validation and ball-based N range',()=>{assert.equal(makeConfig('A*3,B',1,'last',1).target,4);for(const n of [0,5,'',-1,'1.5','abc'])assert.throws(()=>makeConfig('A*3,B',1,'nth',n));assert.throws(()=>makeConfig('A',1,'unknown',1));});
test('start/pause/resume are idempotent; all phases freeze including rotations',()=>{const r=new Race(cfg(),12);assert.equal(r.start(),true);for(let i=0;i<30;i++)assert.equal(r.start(),false);for(let i=0;i<20;i++)r.step();assert.equal(r.pause(),true);const before=JSON.stringify(r.snapshot()),rotation=r.rotationTime;for(let i=0;i<200;i++)r.step();assert.equal(JSON.stringify(r.snapshot()),before);assert.equal(r.rotationTime,rotation);assert.equal(r.pause(),false);assert.equal(r.resume(),true);assert.equal(r.resume(),false);r.step();assert.notEqual(JSON.stringify(r.snapshot()),before);});
test('finish order is crossing time, not ball list; exact ties use seeded tie key',()=>{const r=new Race(cfg(3,'nth',2,'orbit'),1);r.map=structuredClone(r.map);r.map.exits=[100,240,380].map((x,i)=>({id:i+1,x,width:80}));r.map.rails=r.map.rails.filter(s=>s.ay<2000&&s.by<2000);r.state='racing';r.balls.forEach((b,i)=>Object.assign(b,{x:100+i*140,y:r.map.finish-(i===0?.5:.1),vx:0,vy:100,tieKey:[.1,.8,.2][i]}));r.step();assert.deepEqual(r.finishOrder.map(x=>x.id),[r.balls[2].id,r.balls[1].id,r.balls[0].id]);assert.equal(r.winner.id,r.balls[1].id);for(const b of r.balls)assert.equal(r.finish(b,0),false);assert.equal(r.finishOrder.length,3);});
test('fixed stepping: frame chunking cannot change winner or ordered finish times',()=>{const a=new Race(cfg(),123),b=new Race(cfg(),123);a.start();b.start();while(!done(a))a.step(STEP);while(!done(b))b.step(2*STEP);assert.deepEqual(a.finishOrder,b.finishOrder);});
test('one physical seed, all rules: choosing the winner never changes the race',()=>{const races=['first','last','nth'].map(rule=>run(new Race(cfg(20,rule,7),9182)));assert.deepEqual(races[0].finishOrder,races[1].finishOrder);assert.deepEqual(races[1].finishOrder,races[2].finishOrder);assert.equal(races[0].winner.rank,1);assert.equal(races[1].winner.rank,20);assert.equal(races[2].winner.rank,7);});
test('escape impulse after stagnation, invalid timeout cancels an earlier winner',()=>{const r=new Race(cfg(2),5);r.state='racing';const b=r.balls[0];Object.assign(b,{x:310,y:550,anchorX:310,anchorY:550,stuckTime:4.51});r.step();assert.equal(r.assists,1);r.finish(b,1);assert.ok(r.winner);r.raceTime=90;r.step();assert.equal(r.state,'invalid');assert.equal(r.winner,null);});
test('fast wall and pin impacts remain inside the board',()=>{for(const mapId of MAPS.map(m=>m.id)){const r=new Race(cfg(1,'first',1,mapId),2);r.state='racing';const b=r.balls[0];Object.assign(b,{x:42,y:240,vx:-9000,vy:20});r.step(.1);assert.ok(b.x>=40&&b.x<=580);if(r.map.pins.length){const p=r.map.pins[0];Object.assign(b,{x:p.x,y:p.y-24,vx:0,vy:10000});r.step();assert.ok(b.y<p.y,'must not tunnel through pin');}}});
test('all 5 maps × 10 seeds × 1/20/60 balls: complete, containment, unique ordering, finite values',async()=>{const report=[];for(const map of MAPS)for(const n of [1,20,60])for(let seed=1;seed<=10;seed++){const r=new Race(cfg(n,'nth',Math.max(1,Math.floor(n/2)),map.id),seed);r.start();const begin=performance.now();while(!done(r)){r.step();for(const b of r.balls){assert.ok(Number.isFinite(b.x+b.y+b.vx+b.vy));assert.ok(b.x>=40-1e-5&&b.x<=580+1e-5);assert.ok(b.y>=38-1e-5&&b.y<=r.map.finish+1e-5);}}assert.equal(r.state,'complete',`${map.id} ${n} ${seed}`);assert.equal(r.finishOrder.length,n);assert.equal(new Set(r.finishOrder.map(b=>b.id)).size,n);assert.deepEqual(r.finishOrder.map(b=>b.rank),Array.from({length:n},(_,i)=>i+1));assert.equal(r.winner.id,r.finishOrder[r.config.target-1].id);assert.ok(r.finishOrder.every((b,i,a)=>i===0||b.time>=a[i-1].time));report.push({map:map.id,balls:n,seed,duration:r.raceTime,assists:r.assists,cpuMs:performance.now()-begin,steps:r.stats.steps,collisionCount:r.stats.collisions});}await writeFile('evidence/physics-results.json',JSON.stringify(report,null,2));});

test('finish requires an exit throat; crossing between holes never ranks',()=>{const r=new Race(cfg(1,'first',1,'neon'),12);r.state='racing';const b=r.balls[0];Object.assign(b,{x:170,y:r.map.finish-.1,vx:0,vy:150});r.step();assert.equal(r.finishOrder.length,0);assert.equal(b.finished,false);assert.ok(b.y<r.map.finish);Object.assign(b,{x:310,y:r.map.finish-.1,vx:0,vy:150});r.step();assert.equal(r.finishOrder.length,1);assert.equal(r.finishOrder[0].exitId,1);});
