import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href),browser=await chromium.launch({channel:'chrome'}),report={at:new Date().toISOString(),tests:[]};
try{for(const width of [320,390,1440]){
 const c=await browser.newContext({viewport:{width,height:width<700?844:1000},isMobile:width<700,hasTouch:width<700,reducedMotion:'reduce'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.BASE_URL||'http://127.0.0.1:4189');await p.waitForFunction(()=>window.pinball);await p.locator('input[name=rule][value=last]').check();await p.locator('#focus-mode').click();await p.locator('#arena-start').click();await p.waitForFunction(()=>window.pinball.snapshot().time>7);await p.locator('#pause').click();const frozen=await p.evaluate(()=>window.pinball.snapshot());
 const geometry=await p.evaluate(()=>{const board=document.querySelector('#board').getBoundingClientRect(),overlay=document.querySelector('#pause-overlay').getBoundingClientRect();return {ratio:overlay.width*overlay.height/(board.width*board.height),controls:[...document.querySelectorAll('#pause,#reset,#view,#focus-mode,[data-speed]')].map(e=>{const b=e.getBoundingClientRect();return {text:e.textContent,x:b.x,y:b.y,right:b.right,bottom:b.bottom};}),w:innerWidth,h:innerHeight};});assert.ok(geometry.ratio<.13);for(const b of geometry.controls)assert.ok(b.x>=0&&b.y>=0&&b.right<=geometry.w+1&&b.bottom<=geometry.h+1,JSON.stringify({width,b,geometry}));
 await p.screenshot({path:`evidence/park-20260921/10-pause-${width}.png`,fullPage:true});await p.waitForTimeout(200);assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),frozen);
 for(let i=0;i<3;i++){await p.locator('.camera-angle').click();assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),frozen);}
 await p.locator('body').click({position:{x:2,y:2}});await p.keyboard.press('Space');assert.equal((await p.evaluate(()=>window.pinball.snapshot())).state,'racing');await p.keyboard.press('Space');assert.equal((await p.evaluate(()=>window.pinball.snapshot())).state,'paused');
 await p.locator('#reset').click();await p.locator('#focus-mode').click();await p.locator('#participants').fill('A');await p.locator('#participants').press('End');await p.keyboard.press('Space');assert.equal(await p.locator('#participants').inputValue(),'A ');assert.equal((await p.evaluate(()=>window.pinball.snapshot())).state,'ready');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);report.tests.push({width,status:'PASS',pauseOverlayArea:geometry.ratio,controlsInViewport:true,spacePauseResume:true,inputSpacePreserved:true,errors});console.log('PASS readable pause',width,geometry.ratio);await c.close();
}report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;console.error(e);}finally{await writeFile('evidence/park-20260921/10-pause-results.json',JSON.stringify(report,null,2));await browser.close();}
