import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {assertGameResult} from './assert-result.mjs';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href),browser=await chromium.launch({channel:'chrome'}),report={at:new Date().toISOString(),tests:[]};
const prefix=process.env.EVIDENCE_PREFIX||'11';
try{for(const mobile of [false,true])for(const map of ['orbit','split']){
 const device=mobile?'mobile':'desktop',c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile,reducedMotion:'reduce'});await c.addInitScript(()=>{crypto.getRandomValues=a=>{for(let i=0;i<a.length;i++)a[i]=61;return a;};});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.BASE_URL||'http://127.0.0.1:4189');await p.waitForFunction(()=>window.pinball);await p.locator('[data-map='+map+']').click();await p.locator('#participants').fill(Array.from({length:20},(_,i)=>`친구 ${i+1}`).join('\n'));await p.locator('input[value=nth]').check();await p.locator('#nth').fill('20');await p.locator('[data-speed="3"]').click();await p.locator('#focus-mode').click();await p.locator('#arena-start').click();
 await p.waitForFunction(()=>window.pinball.snapshot().balls.some(b=>b.returning),null,{timeout:60000});await p.locator('#pause').click();const paused=await p.evaluate(()=>window.pinball.snapshot());assert.ok(paused.returns>0);const returning=paused.balls.filter(b=>b.returning);assert.ok(returning.length>0);assert.ok(returning.every(b=>!b.finished&&b.rank===null&&!paused.finishOrder.some(r=>r.id===b.id)));assert.ok(paused.finishOrder.every(r=>r.exitId===1));await p.waitForTimeout(200);assert.deepEqual(await p.evaluate(()=>window.pinball.snapshot()),paused);await p.locator('#view').click();await p.locator('#board').screenshot({path:`evidence/park-20260921/${prefix}-${map}-${device}-return.png`});await p.locator('#view').click();await p.locator('#pause').click();
 await p.waitForFunction(()=>['complete','invalid'].includes(window.pinball.snapshot().state),null,{timeout:120000});const round=await p.evaluate(()=>window.pinball.exportRound());assertGameResult(round.result);assert.equal(round.result.finishOrder.length,20);assert.ok(round.result.finishOrder.every(r=>r.exitId===1));
 const replay=await p.evaluate(async round=>{const {Race}=await import(window.pinball.settings().physicsModule);const r=new Race(round.config,round.seed);r.start();while(!['complete','invalid'].includes(r.state))r.step();const {roundId,...s}=r.snapshot();return s;},round);const {roundId,...actual}=round.result;assert.deepEqual(actual,replay);assert.equal(await p.locator('#ranking li').count(),20);await p.screenshot({path:`evidence/park-20260921/${prefix}-${map}-${device}-winner.png`,fullPage:true});assert.deepEqual(errors,[]);report.tests.push({device,map,status:'PASS',returns:actual.returns,time:actual.time,goalOnlyRanks:actual.finishOrder.length,pausePreservesTransit:true,exactBrowserReplay:true,errors});console.log('PASS return portal',report.tests.at(-1));await c.close();
}report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;console.error(e);}finally{await writeFile(`evidence/park-20260921/${prefix}-return-browser-results.json`,JSON.stringify(report,null,2));await browser.close();}
