import assert from 'node:assert/strict';
import {test} from 'node:test';
import {ScreenAwake} from '../src/screen-awake.js';
import {assignLooks,BALL_LOOKS} from '../src/ball-looks.js';
import {placeLabels} from '../src/label-layout.js';
const tick=()=>new Promise(r=>setImmediate(r));
function sentinel(){const s=new EventTarget();s.released=false;s.release=async()=>{s.released=true;s.dispatchEvent(new Event('release'));};return s;}
test('one lock across active phases; pause, resume, finish release it',async()=>{const locks=[];const a=new ScreenAwake({wakeLock:{request:async type=>{assert.equal(type,'screen');const s=sentinel();locks.push(s);return s;}},visible:()=>true});a.setState('mixing');await tick();a.setState('countdown');a.setState('racing');await tick();assert.equal(locks.length,1);assert.equal(a.snapshot().held,true);a.setState('paused');assert.equal(locks[0].released,true);a.setState('racing');await tick();assert.equal(locks.length,2);a.setState('complete');assert.equal(locks[1].released,true);});
test('late request after reset cannot retain a lock',async()=>{let resolve;const a=new ScreenAwake({wakeLock:{request:()=>new Promise(r=>resolve=r)},visible:()=>true});a.setState('racing');await tick();a.setState('ready');const s=sentinel();resolve(s);await tick();assert.equal(s.released,true);assert.equal(a.snapshot().held,false);});
test('rapid restart keeps only the newest request',async()=>{const pending=[];const a=new ScreenAwake({wakeLock:{request:()=>new Promise(r=>pending.push(r))},visible:()=>true});a.setState('mixing');await tick();a.setState('paused');a.setState('mixing');await tick();const old=sentinel(),fresh=sentinel();pending[1](fresh);pending[0](old);await tick();assert.equal(old.released,true);assert.equal(fresh.released,false);assert.equal(a.snapshot().held,true);});
test('unsupported, denied and system release never poll requests each frame',async()=>{const missing=new ScreenAwake({wakeLock:null,visible:()=>true});missing.setState('racing');assert.equal(missing.snapshot().status,'unsupported');let count=0;const a=new ScreenAwake({wakeLock:{request:async()=>{count++;throw Error('low battery');}},visible:()=>true});a.setState('racing');await tick();for(let i=0;i<100;i++)a.setState('racing');assert.equal(count,1);assert.equal(a.snapshot().status,'unavailable');const s=sentinel(),b=new ScreenAwake({wakeLock:{request:async()=>s},visible:()=>true});b.setState('mixing');await tick();await s.release();b.setState('racing');assert.equal(b.snapshot().status,'released');});
test('hidden state releases, explicit resume can acquire again',async()=>{let visible=true;const s=sentinel(),a=new ScreenAwake({wakeLock:{request:async()=>s},visible:()=>visible});a.setState('mixing');await tick();visible=false;a.setState('mixing');assert.equal(s.released,true);assert.equal(a.snapshot().requested,false);});
test('looks use independent random bag, never mutate balls',()=>{const balls=Array.from({length:60},(_,i)=>({id:'b'+i,r:10})),before=structuredClone(balls);for(const theme of ['sports','animals']){const looks=assignLooks(balls,theme,()=>.4);assert.equal(looks.size,60);assert.deepEqual(new Set([...looks.values()].slice(0,6)),new Set(BALL_LOOKS[theme]));}assert.deepEqual(balls,before);assert.equal(assignLooks(balls,'classic').size,0);});
test('overlapping names are all retained and placements stay stable',()=>{const c=Array.from({length:60},(_,i)=>({id:'b'+i,x:200,y:200,width:55})),memory=new Map();const a=placeLabels(c,390,650,memory),b=placeLabels(c,390,650,memory);assert.equal(a.length,60);assert.deepEqual(b,a);assert.equal(new Set(a.map(l=>l.id)).size,60);assert.ok(a.every(l=>l.box.l>=0&&l.box.r<=390&&l.box.t>=0&&l.box.b<=650));});
