import { test, expect } from '@playwright/test';
test.use({contextOptions:{reducedMotion:'reduce'}});
test('Reference theme, actual GLB, battery focus, camera bounds and user selection',async({page})=>{
  test.setTimeout(300000); // Multiple detailed models and captures on the CPU WebGL renderer.
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/?user=U0002');
  const canvas=page.locator('canvas');
  await expect(canvas).toHaveAttribute('data-renderer','webgl-3d-mesh',{timeout:90000});
  await expect.poll(async()=>Number(await canvas.getAttribute('data-model-triangles'))).toBeGreaterThan(100000);
  await expect(page.getByTestId('odometer')).toContainText('95,454');
  await expect(page.getByTestId('health-score')).toHaveText('—');
  await expect(page.locator('img')).toHaveCount(0);
  await expect(page.getByRole('tab')).toHaveCount(4);
  await page.screenshot({path:'test-results/demo-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'배터리 정보 보기',exact:true}).click();
  await expect(page.locator('#battery-info-panel')).toBeVisible();
  await page.getByRole('button',{name:'점수는 어떻게 계산하나요?'}).click();
  await expect(page.locator('#score-attribution').getByRole('link')).toHaveAttribute('href','https://doi.org/10.1016/j.jpowsour.2014.02.012');
  await expect(page.locator('#score-attribution')).toContainText('배터리 종류를 확인해야');
  await page.screenshot({path:'test-results/demo-battery-focus.png',fullPage:true});
  await page.keyboard.press('Escape');await expect(page.locator('#battery-info-panel')).toHaveCount(0);
  await page.getByRole('button',{name:'배터리 위치 보기'}).click();
  await expect(page.locator('#battery-info-panel')).toBeVisible();
  await page.getByRole('button',{name:'배터리 상세 닫기'}).click();
  await page.getByRole('combobox',{name:'사용자 및 차량'}).selectOption('U0009');
  await expect(page.getByTestId('vehicle-model')).toHaveText('Model Y');
  await expect(canvas).toHaveAttribute('data-vehicle-id','tesla_modely_premium_rwd_2026',{timeout:90000});
  await expect.poll(async()=>Number(await canvas.getAttribute('data-model-triangles'))).toBeGreaterThan(100000);
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/demo-model-y.png',fullPage:true});
  await page.reload();await expect(page.getByRole('combobox',{name:'사용자 및 차량'})).toHaveValue('U0009');
  await expect(canvas).toHaveAttribute('data-renderer','webgl-3d-mesh',{timeout:90000});
  await canvas.scrollIntoViewIfNeeded();
  const area=(await canvas.boundingBox())!;
  for(const direction of [-1,1]){
    await page.mouse.move(area.x+area.width*.5,area.y+area.height*.5);await page.mouse.down();
    await page.mouse.move(area.x+area.width*.5+direction*1200,area.y+area.height*.5+direction*800,{steps:8});await page.mouse.up();
    await page.waitForTimeout(500);
    const polar=Number(await canvas.getAttribute('data-polar')),azimuth=Number(await canvas.getAttribute('data-azimuth'));
    expect(polar).toBeGreaterThanOrEqual(54.9);expect(polar).toBeLessThanOrEqual(78.1);
    expect(azimuth).toBeGreaterThanOrEqual(-65.1);expect(azimuth).toBeLessThanOrEqual(-14.9);
  }
  await page.getByRole('combobox',{name:'사용자 및 차량'}).selectOption('U0001');
  await expect(page.getByTestId('vehicle-model')).toHaveText('Ioniq 5');
  await expect(canvas).toHaveAttribute('data-vehicle-id','hyundai_ioniq5_standard_2wd_2026',{timeout:90000});
  await expect(canvas).toHaveAttribute('data-model-triangles','105109');
  expect(Math.abs(Number(await canvas.getAttribute('data-model-min-y')))).toBeLessThan(.01);
  expect(Number(await canvas.getAttribute('data-model-height'))).toBeLessThan(2);
  await expect(page.getByTestId('odometer')).toContainText('11,194');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/demo-ioniq5.png',fullPage:true});
  await page.getByRole('button',{name:'배터리 정보 보기',exact:true}).click();
  await page.getByRole('button',{name:'점수는 어떻게 계산하나요?'}).click();
  await expect(page.locator('#battery-info-panel')).toContainText('평가하기 어려운 충전 기록');
  await page.getByRole('combobox',{name:'사용자 및 차량'}).selectOption('U0017');
  await expect(canvas).toHaveAttribute('data-vehicle-id','hyundai_ioniq6_lr_2wd_2026',{timeout:90000});
  await expect(canvas).toHaveAttribute('data-renderer','webgl-3d-mesh');
  await expect(page.getByTestId('vehicle-model')).toHaveText('Ioniq 6');
  expect(errors).toEqual([]);
});
test('Mobile layout, user-scoped history, filters, CSV and session detail',async({page,request})=>{
  test.setTimeout(240000);
  await page.setViewportSize({width:390,height:844});await page.goto('/?user=U0002');
  await expect(page.locator('canvas')).toHaveAttribute('data-renderer','webgl-3d-mesh',{timeout:90000});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/demo-mobile.png',fullPage:true});
  await page.getByRole('tab',{name:'충전 이력',exact:true}).click();
  await expect(page.locator('tbody tr')).toHaveCount(5);
  const response=await request.get('/api/users/U0002/sessions');expect(response.status()).toBe(200);
  const data=await response.json();expect(data.sessions.length).toBe(6);
  expect(data.sessions.every((s:{userId:string;vehicleId:string})=>s.userId==='U0002'&&s.vehicleId==='tesla_model3_lr_rwd_2026')).toBe(true);
  const missing=await request.get('/api/users/unknown/sessions');expect(missing.status()).toBe(404);
  await page.getByRole('button',{name:'다음 페이지'}).click();await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.getByRole('combobox',{name:'충전 유형',exact:true}).selectOption('DC_FAST');
  await expect(page.getByText('선택한 조건에 맞는 충전 기록이 없습니다.')).toBeVisible();
  await page.getByRole('combobox',{name:'충전 유형',exact:true}).selectOption('all');
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'내보내기'}).click();
  expect((await downloadPromise).suggestedFilename()).toBe('U0002-charging-history.csv');
  await page.getByRole('button',{name:/세션 상세$/}).first().click();
  await expect(page.locator('#session-detail')).toContainText('이번 충전 기록');
  await expect(page.locator('#session-detail')).not.toContainText(/미제공|Mock|session_id|Score Attribution/);
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/demo-session-mobile.png',fullPage:true});
  await page.getByRole('combobox',{name:'사용자 및 차량'}).selectOption('U0001');
  await expect(page.locator('#session-detail')).toHaveCount(0);
  await expect(page.locator('tbody tr')).toHaveCount(5);
  const firstId=await page.locator('tbody tr').first().getAttribute('data-session-id');
  const other=await (await request.get('/api/users/U0001/sessions')).json();
  expect(other.sessions.some((s:{sessionId:string})=>s.sessionId===firstId)).toBe(true);
  await page.getByRole('tab',{name:'주요 정보',exact:true}).click();
  await page.getByRole('tab',{name:'주요 정보',exact:true}).press('ArrowRight');
  await expect(page.getByRole('tab',{name:'배터리 정보',exact:true})).toHaveAttribute('aria-selected','true');
});
