import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import path from 'node:path';
const root='park/reports';await mkdir(root,{recursive:true});
async function json(file){try{return JSON.parse(await readFile(path.join(root,file),'utf8'));}catch{return null;}}
const coverage=await json('coverage/coverage-summary.json'),unit=await json('unit/results.json'),golden=await json('golden/results.json');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=new Date().toLocaleString('ko-KR');
const base=`<style>*{box-sizing:border-box}body{margin:0;background:#f3f2e9;color:#304537;font:14px -apple-system,BlinkMacSystemFont,sans-serif;padding:60px 7%}a{color:#56744b}header{border-bottom:1px solid #d8dfcd;padding-bottom:30px;margin-bottom:30px}small{font-size:10px;letter-spacing:.15em;color:#8b997a}h1{font:42px Georgia}p{line-height:1.9;color:#7c8c71}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:18px}.card{background:#fffdf5;border:1px solid #e3e5d6;border-radius:10px;padding:24px;text-decoration:none;display:block}.card strong{display:block;font:36px Georgia;margin:16px 0}.card span{font-size:12px}.ok{color:#5b8050}.warn{color:#b38142}table{border-collapse:collapse;width:100%;background:#fffdf5;border-radius:10px;overflow:hidden;font-size:12px}td,th{text-align:left;padding:14px 18px;border-bottom:1px solid #e5e8dc}th{color:#849376;font-size:10px}h2{font-weight:500;font-size:20px;margin-top:35px}code{font-size:12px;background:#e7ebdf;padding:3px 7px;border-radius:4px}.note{padding:20px;background:#e9ecdf;border-radius:8px;margin:25px 0;font-size:12px}.thumbs{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:15px}.thumbs img{width:100%;border:1px solid #e0e5d4;border-radius:7px}.thumbs figcaption{font-size:11px;margin-top:8px;color:#879579}footer{border-top:1px solid #dce1d2;margin-top:40px;padding-top:20px;font-size:11px;color:#93a186}</style>`;
let browserFiles=[];try{browserFiles=(await readdir(path.join(root,'browser-coverage/raw'))).filter(f=>f.endsWith('.json'));}catch{}
const merged=new Map();
for(const file of browserFiles){for(const entry of (await json('browser-coverage/raw/'+file)||[])){
 const name=new URL(entry.url).pathname;let record=merged.get(name);if(!record){record={text:entry.source||entry.text||'',ranges:[]};merged.set(name,record);}
 // V8 nested ranges override their parents. Keep the executed intervals per run, then union runs.
 for(const fn of entry.functions||[]){const ranges=fn.ranges;const cuts=[...new Set(ranges.flatMap(r=>[r.startOffset,r.endOffset]))].sort((a,b)=>a-b);for(let i=0;i<cuts.length-1;i++){const a=cuts[i],b=cuts[i+1];const covering=ranges.filter(r=>r.startOffset<=a&&r.endOffset>=b).sort((x,y)=>(x.endOffset-x.startOffset)-(y.endOffset-y.startOffset));if(covering[0]?.count>0)record.ranges.push([a,b]);}}
}}
let rows='',totalBytes=0,coveredBytes=0;
for(const [name,record]of merged){const sorted=record.ranges.sort((a,b)=>a[0]-b[0]);let used=0,end=-1;for(const[a,b]of sorted){if(b>end){used+=b-Math.max(a,end);end=b;}}const total=record.text.length||Math.max(0,end);totalBytes+=total;coveredBytes+=used;rows+=`<tr><td>${esc(name)}</td><td>${total?(used/total*100).toFixed(1):'—'}%</td><td>${used.toLocaleString()} / ${total.toLocaleString()}</td></tr>`;}
await mkdir(path.join(root,'browser-coverage'),{recursive:true});
await writeFile(path.join(root,'browser-coverage/index.html'),`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>브라우저 실행 커버리지</title>${base}<header><small>WONDER PARK / BROWSER COVERAGE</small><h1>실제 브라우저에서 실행한 코드</h1><p>Chrome V8가 골든·기능 테스트 중 관측한 <code>park/src/</code> 스크립트 실행 범위입니다.</p></header><div class="note">${browserFiles.length}개 테스트에서 수집. Vite가 변환한 JavaScript 문자열 길이 기준이며, 원본 소스의 문장·분기 커버리지와는 다른 지표입니다. 라이브러리 코드는 제외합니다. 비동기 오류나 시각적 정확성을 이 숫자만으로 보장하지 않습니다.</div><table><thead><tr><th>모듈</th><th>실행 범위</th><th>실행 길이 / 스크립트 길이</th></tr></thead><tbody>${rows}</tbody></table><footer><a href="../">전체 보고서</a> · ${date}</footer></html>`);
const totals=coverage?.total||{};const unitPassed=unit?.numPassedTests??'—',unitFailed=unit?.numFailedTests??'—';const stats=golden?.stats;
const gallery=['park-desktop-day','park-desktop-night','castle-fireworks','disney-friends-directory','friend-daisy','friend-goofy','friend-pluto','friend-pooh','friend-stitch','friend-baymax','bumper-attraction','cinema-screen','park-mobile','voice-mobile'];
await mkdir(path.join(root,'screenshots'),{recursive:true});
for(const name of gallery){try{const data=await readFile(`park/tests/e2e/golden/${name}.png`);await writeFile(path.join(root,'screenshots',name+'.png'),data);}catch{}}
await writeFile(path.join(root,'index.html'),`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Wonder Park · 품질 보고서</title>${base}<header><small>TBD WONDER PARK / QUALITY & CRAFT</small><h1>작은 세계, 꼼꼼한 검증.</h1><p>코드 커버리지와 실제 Chrome WebGL 화면 비교, 기능 검증 결과를 한 곳에서 확인합니다.</p></header><div class="grid"><a class="card" href="coverage/"><small>NODE V8 / CORE MODULES</small><strong>${totals.lines?.pct??'—'}%</strong><span>핵심 로직 줄 커버리지 · 분기 ${totals.branches?.pct??'—'}%</span></a><a class="card" href="unit/results.json"><small>UNIT TESTS</small><strong>${unitPassed}<span> 통과</span></strong><span>실패 ${unitFailed} · 프로젝트 탐색, 테마 변경, 경로 보호, 동기화</span></a><a class="card" href="golden/"><small>CHROME / GOLDEN & INTERACTION</small><strong>${stats?.expected??'—'}<span> 통과</span></strong><span>실패 ${stats?.unexpected??'—'} · 건너뜀 ${stats?.skipped??'—'}</span></a><a class="card" href="browser-coverage/"><small>CHROME V8 / BROWSER SCRIPTS</small><strong>${totalBytes?(coveredBytes/totalBytes*100).toFixed(1):'—'}%</strong><span>브라우저 실행 범위 · ${merged.size}개 직접 작성 모듈</span></a></div><div class="note"><a href="circuit/">어트랙션 자동 입장 · 무한 순회 실시간 보고서 ↗</a> · <a href="circuit/screenshots/overview.png">전체 프로젝트가 표시된 최신 지도</a><br>각 프로젝트의 실제 화면에 순서대로 입장하고, 마지막 어트랙션 뒤에는 처음부터 반복합니다. 실패도 기록하며 다음 검증을 계속합니다.</div><h2>검증 범위</h2><table><tr><th>항목</th><th>실제 검사</th></tr><tr><td>새 어트랙션 / 테마 변경</td><td>폴더 탐색, README 의미 분류, 명시적 manifest 우선, 모델 교체, webpage 제외</td></tr><tr><td>다른 에이전트와의 협업</td><td>작업 파일 변경·분기 분기 시 자동 병합 보류, 깨끗한 상태에서만 fast-forward</td></tr><tr><td>3D 및 캐릭터</td><td>WebGL 2 컨텍스트·지오메트리 존재, 캐릭터 포즈 변화, 카메라 이동, 낮·야간 골든</td></tr><tr><td>극장</td><td>실제 30초 MP4의 VideoTexture, 재생·정지·탐색·음소거, 3D 스크린 골든</td></tr><tr><td>접근 및 미디어</td><td>모바일 폭, 접근 가능한 메뉴, HTTP Range, 원본 폴더 경로 보호, 외부 Origin 차단</td></tr></table><div class="note">핵심 문장·분기 커버리지는 <code>park/lib/</code> 대상입니다. 렌더러·UI는 별도의 실제 브라우저 실행 커버리지와 골든으로 검증합니다. 골든 기준 생성 후 독립 비교 실행 결과를 확인해야 합니다. 성능은 장치에 따라 달라지며, 소프트웨어 WebGL의 FPS는 실제 GPU 성능을 대표하지 않습니다.</div><h2>골든 기준 화면</h2><div class="thumbs">${gallery.map(name=>`<figure><a href="screenshots/${name}.png"><img src="screenshots/${name}.png" alt="${name}" loading="lazy"></a><figcaption>${name}</figcaption></figure>`).join('')}</div><h2>로컬에서 재현</h2><p><code>npm run test:coverage</code> → <code>npm run test:golden</code> → <code>npm run reports</code></p><footer>${date} 생성 · <a href="/">파크로 돌아가기</a></footer></html>`);
console.log(`HTML report: http://localhost:5190/reports/`);
