import {Race,makeConfig,SAMPLE_NAMES,STEP,MAPS,COLORS} from './physics.js';
import {Renderer} from './renderer.js';
import {ParkSoundscape} from './soundscape.js';
import {LANDS} from './lands.js';
import {makeLottoConfig,lottoResult} from './lotto.js';
const DEFAULT_NAMES=['병우','종호','동길','태성','순수'];
function shuffledDefaultNames(){const names=[...DEFAULT_NAMES],random=new Uint32Array(1);for(let i=names.length-1;i>0;i--){const limit=2**32-(2**32%(i+1));do{crypto.getRandomValues(random);}while(random[0]>=limit);const j=random[0]%(i+1);[names[i],names[j]]=[names[j],names[i]];}return names.join(', ');}
const $=id=>document.getElementById(id);const renderer=new Renderer($('board'));let playbackSpeed=1.5,gameMode='player';let race=null,config=null,overrides={},mapId='neon',accumulator=0,last=0,slowUntil=0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,sound=false,selected=null,lastState='',lastFinish=-1,lastUi=0;
const frameStats=[];let frames=0,totalFrameCost=0,lastCountdown=0,splashUntil=0,renderFault=false,contextLost=false,deviceMessage=null;
const locked=()=>race&&['mixing','countdown','racing','paused','complete','invalid'].includes(race.state);
function rule(){return document.querySelector('input[name=rule]:checked').value;}
function ruleText(c){if(c.mode==='lotto')return c.lottoOrder==='last'?'마지막 6개 + 보너스':'처음 6개 + 보너스';return c.rule==='first'?'첫 번째 도착':c.rule==='last'?'마지막 공으로 남기':`${c.target}번째 도착`;}
function ruleDescription(c){if(c.mode==='lotto')return `로또 · ${ruleText(c)}`;return c.rule==='last'?'마지막 한 공이 남으면 당첨':ruleText(c)+'하면 당첨';}
function readConfig(){return {...(gameMode==='lotto'?makeLottoConfig(document.querySelector('input[name=lotto-rule]:checked').value):{...makeConfig($('participants').value,$('default-count').value,rule(),$('nth').value,overrides),mode:'player'}),mapId,boardMotion:$('board-motion').checked,finishMode:'winner'};}
function setFocusMode(enabled){document.body.classList.toggle('play-focus',enabled);document.body.classList.toggle('expanded-map',enabled&&(renderer.overview||renderer.halfView));$('focus-mode').setAttribute('aria-pressed',String(enabled));$('focus-mode').textContent=enabled?'⤡ 원래 화면':'⤢ 크게 보기';if(enabled)window.scrollTo({top:0,behavior:reduced?'instant':'smooth'});}
function setMapView(mode){renderer.overview=mode==='full';renderer.halfView=mode==='half';$('view').setAttribute('aria-pressed',String(renderer.overview));$('view').textContent=renderer.overview?'따라가기':'전체 맵';$('half-view').setAttribute('aria-pressed',String(renderer.halfView));setFocusMode(mode!=='follow');announce(mode==='half'?'하프 모드. 코스 절반을 확대해 진행 구간을 따라갑니다.':mode==='full'?'전체 맵. 창 크기에 맞춰 코스 전체를 표시합니다.':'공을 가까이 따라갑니다.');}
function announce(text){$('announcement').textContent=text;}
const soundscape=new ParkSoundscape();
let soundToggle=0;
async function toggleSound(){const generation=++soundToggle;sound=!sound;updateSoundButton();try{await soundscape.setEnabled(sound);}catch{if(generation===soundToggle){sound=false;updateSoundButton('소리 사용 불가');}}}
function updateSoundButton(label){for(const id of ['sound','arena-sound']){$(id).setAttribute('aria-pressed',String(sound));$(id).setAttribute('aria-label',label||(sound?'소리 끄기':'소리 켜기'));$(id).querySelector('span').textContent=label||(id==='sound'?(sound?'소리 켜짐':'소리 꺼짐'):(sound?'켜짐':'꺼짐'));}}
function setReduced(){document.body.classList.toggle('reduced',reduced);$('motion').setAttribute('aria-pressed',String(reduced));if(reduced){slowUntil=0;$('confetti').replaceChildren();}}
function renderRoster(people){$('roster').replaceChildren();people.forEach((p,i)=>{const row=document.createElement('div');row.className='roster-row';const dot=document.createElement('span');dot.className='color-dot';dot.style.setProperty('--color',p.color);const label=document.createElement('label');label.textContent=p.label;label.htmlFor=`count-${i}`;const input=document.createElement('input');input.id=`count-${i}`;input.type='text';input.inputMode='numeric';input.value=p.count;input.setAttribute('aria-label',`${p.label} 공 개수`);input.addEventListener('input',()=>{if(locked())return;overrides[i]=input.value;refresh(false);});row.append(dot,label,input);$('roster').append(row);});}
function refresh(roster=true){if(locked())return;try{config=readConfig();$('input-error').textContent='';$('participant-summary').replaceChildren();const a=document.createElement('span');a.textContent=`참가자 ${config.people.length}명`;const b=document.createElement('strong');b.textContent=`공 ${config.total}개`;$('participant-summary').append(a,b);$('rule-summary').textContent=ruleText(config);$('live-rule').textContent=ruleDescription(config);$('nth-row').hidden=rule()!=='nth';if(roster)renderRoster(config.people);race=new Race(config);lastState='';lastFinish=-1;accumulator=0;resetResult();renderStatus();}catch(e){config=null;$('input-error').textContent=e.message;$('participant-summary').textContent='입력을 확인해 주세요.';$('nth-row').hidden=rule()!=='nth';$('start').disabled=renderFault;}}
function resetResult(preserveRanks=false){soundscape.stop();lastCountdown=0;for(const id of ['winner-lotto','splash-lotto']){$(id).hidden=true;$(id).replaceChildren();}document.body.classList.remove('lotto-complete');selected=null;splashUntil=0;deviceMessage=null;$('winner-splash').hidden=true;$('winner-card').classList.remove('celebrated');$('winner-name').textContent='아직 비밀!';$('winner-caption').textContent='오늘의 주인공은';$('winner-detail').textContent='당첨 조건을 달성하면 이름을 크게 알려드려요.';$('winner-orb').textContent='?';if(!preserveRanks){$('ranking').replaceChildren();$('ranking-empty').hidden=false;}$('confetti').replaceChildren();slowUntil=0;}
function start(){const fromResult=$('winner-splash').contains(document.activeElement);if(renderFault)return false;if(race&&['mixing','countdown','racing','paused'].includes(race.state))return false;try{const c=locked()?race.config:readConfig();race=new Race(c);config=c;frameStats.length=0;frames=0;totalFrameCost=0;resetResult();race.start();accumulator=0;lastFinish=-1;setFocusMode(true);renderStatus();if(fromResult)$('pause').focus({preventScroll:true});announce(`${LANDS[mapId].label}, 공 ${c.total}개. ${ruleDescription(c)}입니다. 공을 섞습니다.`);if(innerWidth<701&&!document.body.classList.contains('play-focus'))$('board').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});return true;}catch(e){$('input-error').textContent=e.message;announce(e.message);if(document.body.classList.contains('play-focus')){setFocusMode(false);$('input-error').scrollIntoView({block:'center'});}return false;}}
function reset(){race=null;lastState='';accumulator=0;overrides={...overrides};$('settings').disabled=false;refresh();$('start').textContent='공 섞고 시작하기 ↗';}
function pause(){if(renderFault)return;if(race.state==='paused')race.resume();else race.pause();accumulator=0;renderStatus();announce(race.state==='paused'?'경기가 일시정지되었습니다.':'경기를 재개합니다.');}
function showWinnerSplash(w,final=false){const newlyShown=$('winner-splash').hidden;$('splash-name').textContent=w.label;$('splash-name').dataset.long=String([...w.label].length>16);$('splash-detail').textContent=w.criterion==='last-remaining'?`마지막 남은 공 · ${w.number}번 공`:`${w.rank}번째 도착 · ${w.number}번 공 · ${w.exitLabel}`;$('splash-caption').textContent=final?'오늘의 당첨자':'당첨 공 도착!';$('splash-status').textContent=final?'당첨 조건 달성 · 최종 확정':'당첨 조건을 확인하고 있어요';$('splash-replay').hidden=!final;$('splash-close').textContent=final?'전체 순위 보기':'경기 계속 보기';$('winner-splash').hidden=false;$('winner-splash').dataset.final=String(final);splashUntil=final?0:performance.now()+3500;const lotto=lottoResult(race.config,race.snapshot());if(lotto){document.body.classList.add('lotto-complete');$('splash-name').textContent='행운의 번호';$('splash-name').dataset.long='false';renderLotto('splash-lotto',lotto);$('splash-caption').textContent=ruleText(race.config);$('splash-detail').textContent=lotto.bonusArrived?'7번째 도착까지 · 추첨 완료':'마지막 남은 공은 보너스 · 추첨 완료';$('splash-status').textContent=lotto.bonusArrived?'1~6등 당첨 · 7등 보너스':'39~44등 당첨 · 미도착 공 보너스';}if(newlyShown)$('splash-name').focus({preventScroll:true});}
function celebrate(w){showWinnerSplash(w,true);$('winner-card').classList.add('celebrated');$('winner-card').style.setProperty('--winner-color',w.color);$('winner-name').textContent=w.label;$('winner-caption').textContent='오늘의 당첨자 · 확정';$('winner-detail').textContent=w.criterion==='last-remaining'?`마지막 남은 공 · ${w.number}번 공 · 경기 ${w.time.toFixed(3)}초`:`${w.rank}번째 도착 · ${w.number}번 공 · ${w.exitLabel} · ${w.time.toFixed(3)}초`;$('winner-orb').textContent=w.criterion==='last-remaining'?'★':String(w.rank);selected=w.id;announce(w.criterion==='last-remaining'?`${w.label}, 마지막 남은 공으로 당첨!`:`${w.label}, ${w.rank}번째로 도착해 당첨!`);soundscape.cue('winner');
 const lotto=lottoResult(race.config,race.snapshot());if(lotto){$('winner-name').textContent='행운의 번호';$('winner-orb').textContent='6+1';$('winner-caption').textContent=ruleText(race.config);$('winner-detail').textContent=lotto.bonusArrived?'당첨 1~6등 · 보너스 7등':'당첨 39~44등 · 마지막 남은 공 보너스';renderLotto('winner-lotto',lotto);announce(`당첨 번호 ${lotto.numbers.join(', ')}, 보너스 ${lotto.bonus}번입니다.`);}
 if(!reduced){slowUntil=performance.now()+1000;for(let i=0;i<34;i++){const e=document.createElement('i');e.className='confetti-piece';e.style.setProperty('--x',`${(i*37)%100}%`);e.style.setProperty('--color',COLORS[i%8]);e.style.setProperty('--rot',`${i*19}deg`);e.style.animationDelay=`${i%6*.05}s`;$('confetti').append(e);}setTimeout(()=>$('confetti').replaceChildren(),2400);}}
function renderLotto(id,result){const root=$(id);root.replaceChildren();root.hidden=false;const main=document.createElement('div');main.className='lotto-main';for(const number of result.numbers){const n=document.createElement('b');n.className='lotto-number';n.dataset.number=number;n.textContent=number;n.setAttribute('aria-label',`${number}번 당첨 번호`);main.append(n);}const bonus=document.createElement('div');bonus.className='lotto-bonus';const caption=document.createElement('span');caption.textContent='BONUS';const n=document.createElement('b');n.className='lotto-number';n.dataset.number=result.bonus;n.textContent=result.bonus;n.setAttribute('aria-label',`${result.bonus}번 보너스`);bonus.append(caption,n);root.append(main,bonus);}
function showRanks(){if(lastFinish===race.finishOrder.length)return;lastFinish=race.finishOrder.length;$('ranking-empty').hidden=lastFinish>0;$('ranking').replaceChildren();const lotto=lottoResult(race.config,race.snapshot());for(const r of race.finishOrder){const li=document.createElement('li');li.className='rank-row'+(r.rank===race.config.target?' target':'');li.dataset.ballId=r.id;li.dataset.rank=r.rank;const num=document.createElement('span');num.className='rank-number';num.textContent=String(r.rank).padStart(2,'0');const dot=document.createElement('span');dot.className='color-dot';dot.style.setProperty('--color',r.color);const name=document.createElement('span');name.className='rank-name';name.textContent=r.label;const detail=document.createElement('small');detail.textContent=race.config.mode==='lotto'?`${r.label}번 숫자 · ${r.exitLabel}${lotto?.mainRanks.includes(r.rank)?' · 당첨 번호':lotto?.bonusArrived&&r.rank===7?' · 보너스':''}`:`${r.number}번 공 · ${r.exitLabel}${r.rank===race.config.target?' · 당첨':''}`;name.append(detail);const time=document.createElement('span');time.className='rank-time';time.textContent=r.time.toFixed(2)+'s';li.append(num,dot,name,time);$('ranking').append(li);}}
function renderStatus(){if(!race)return;const s=race.state,live=['mixing','countdown','racing','paused'].includes(s);soundscape.setState(s);document.body.dataset.state=s;$('settings').disabled=locked();document.querySelectorAll('[data-game-mode]').forEach(b=>b.disabled=locked());$('sample').disabled=locked();for(const b of document.querySelectorAll('.map-choice'))b.disabled=locked();$('start').disabled=live||renderFault;$('splash-replay').disabled=renderFault;$('arena-start').hidden=live;$('arena-start').disabled=renderFault;$('arena-start').textContent=['complete','invalid'].includes(s)?'↻ 다시 타기':'▶ 출발';$('pause').hidden=!live;$('start').textContent=s==='complete'||s==='invalid'?'다시 플레이 ↗':live?'레이스 진행 중':'공 섞고 시작하기 ↗';$('edit').hidden=!['complete','invalid'].includes(s);$('pause').disabled=!live||renderFault;$('pause').textContent=s==='paused'?'▶ 재개':'Ⅱ 일시정지';$('pause-overlay').hidden=s!=='paused';const stateLabels={ready:'READY',mixing:'MIXING',countdown:'GET READY',racing:'RACING',paused:'PAUSED',complete:'FINISHED',invalid:'VOID'};$('state-tag').textContent=stateLabels[s];$('countdown').hidden=s!=='countdown';if(s==='countdown'){const number=Math.max(1,Math.ceil(3-race.phaseTime));$('countdown').textContent=number;if(number!==lastCountdown){soundscape.cue('countdown',{number});lastCountdown=number;}}$('progress').textContent=`${race.finishOrder.length} / ${race.balls.length} 도착`;$('finished-count').textContent=`${race.finishOrder.length} FINISHED`;$('timer').textContent=`${String(Math.floor(race.raceTime/60)).padStart(2,'0')}:${(race.raceTime%60).toFixed(1).padStart(4,'0')}`;
 const message={ready:'공들이 출발을 기다리고 있어요',mixing:'출발 전에 공을 골고루 섞는 중',countdown:'게이트가 곧 열립니다',racing:race.winner?'당첨! 남은 공도 끝까지 달려요':'한 번의 충돌로, 순위는 다시 바뀌어요',paused:'일시정지 · 위치와 순위가 유지돼요',complete:race.winner?.criterion==='last-remaining'?'마지막 남은 공이 당첨! 경기가 끝났어요':'목표 순위 도착! 경기가 끝났어요',invalid:'완주하지 못한 경기 · 결과 무효, 다시 플레이해 주세요'};$('race-message').textContent=(s==='racing'&&deviceMessage&&race.raceTime<deviceMessage.until?deviceMessage.text:message[s])+(race.returnCount?` · 리턴 ${race.returnCount}회`:'')+(race.assists?` · 탈출 보조 ${race.assists}회`:'');if(s==='invalid'){resetResult(true);$('winner-name').textContent='무효 경기';$('winner-detail').textContent=`${race.map.timeLimit}초 내 미완주 또는 물리 오류. 당첨 결과를 사용하지 말고 다시 시작해 주세요.`;}
 const motion=race.motion();$('board-motion-state').textContent=!motion.enabled?'고정 보드':motion.active?`${motion.axis==='x'?'↔':'↕'} 흔들리는 중`:motion.nextIn<1.5&&s==='racing'?'✦ 곧 크게 흔들려요':'↔ 스윙 보드';$('board-motion-state').dataset.active=String(motion.active);$('exit-legend').textContent=race.map.returnPoint?(race.returnClosed()?'피날레 · 리턴 진입로 닫힘 · 노란 GOAL로':'노란 GOAL · 분홍 BACK · 60초에 리턴 닫힘'):'중앙 골인 구멍 1개';
 showRanks();if(lastState!==s){if(s==='racing'){announce('게이트가 열렸습니다. 출발!');}if(s==='complete'){$('winner-caption').textContent=race.config.mode==='lotto'?ruleText(race.config):'오늘의 당첨자 · 확정';if(race.winner)showWinnerSplash(race.winner,true);}if(s==='complete'){const l=lottoResult(race.config,race.snapshot());announce(l?`로또 당첨 번호 ${l.numbers.join(', ')}, 보너스 ${l.bonus}번입니다.`:`당첨 조건을 달성해 경기가 종료되었습니다. 당첨자는 ${race.winner?.label}입니다.`);}lastState=s;}}
function frame(now){const begin=performance.now();if(splashUntil&&now>splashUntil){$('winner-splash').hidden=true;splashUntil=0;}const rawDelta=last?now-last:0;const dt=Math.min(rawDelta/1000,.1);last=now;if(race){const scale=!reduced&&now<slowUntil?.32:1;accumulator+=dt*scale*playbackSpeed;if(!['mixing','countdown','racing'].includes(race.state))accumulator=0;while(accumulator>=STEP){race.step();accumulator-=STEP;}
 const events=race.events.splice(0);for(const ev of events){if(ev.type==='hit'){renderer.impact?.(ev,race.elapsed,reduced);soundscape.cue(ev.kind==='bumper'?'bumper':'hit',ev);}if(ev.type==='board-motion'){soundscape.cue('swing');announce(`보드가 ${ev.axis==='x'?'좌우로':'앞뒤로'} 크게 흔들립니다.`);}if(['capture','launch','release'].includes(ev.type)){const name=race.balls.find(b=>b.id===ev.ballId)?.label??'공';deviceMessage={until:race.raceTime+1.6,text:ev.type==='capture'?`${name} · ${ev.kind==='cannon'?'대포 회전 중…':'자석에 찰싹!'}`:ev.type==='launch'?`${name} · 대포 발사!`:`${name} · 자석에서 탈출!`};if(ev.type==='launch'){soundscape.cue('launch');renderer.impact?.({...ev,kind:'bumper'},race.elapsed,reduced);}else soundscape.cue(ev.type,ev);}if(ev.type==='finale'){deviceMessage={until:race.raceTime+3,text:'피날레! 리턴 진입로가 닫히고 골인으로 향해요'};announce('60초 피날레. 모든 공에 동일하게 리턴 진입로가 닫히고 골인 방향 안내 레일이 열립니다.');}if(ev.type==='return'){const name=race.balls.find(b=>b.id===ev.ballId)?.label??'공';deviceMessage={until:race.raceTime+1.6,text:`${name} · 중간 구간으로 다시 슝!`};soundscape.cue('return');}if(ev.type==='return-land')renderer.impact?.({...ev,kind:'bumper'},race.elapsed,reduced);if(ev.type==='finish')soundscape.cue('finish');if(ev.type==='winner')celebrate(ev.result);}
 if(!renderFault){try{renderer.draw(race,reduced,selected);}catch(error){showRenderError('경기장 표시 중 문제가 생겨 공을 멈췄어요. 위치와 순위는 보관되어 있어요. 화면 복구 버튼을 눌러 주세요.');console.error('Pinball rendering paused:',error);}}if(lastState!==race.state||now-lastUi>80){renderStatus();lastUi=now;}}
 const cost=performance.now()-begin;frames++;totalFrameCost+=cost;if(frameStats.length<1200)frameStats.push({delta:rawDelta,cost,state:race?.state,total:race?.balls.length});else{frameStats.shift();frameStats.push({delta:rawDelta,cost,state:race?.state,total:race?.balls.length});}requestAnimationFrame(frame);}
document.querySelectorAll('[data-speed]').forEach(button=>button.addEventListener('click',()=>{playbackSpeed=Number(button.dataset.speed);document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));announce(`${playbackSpeed}배속으로 재생합니다.`);}));
$('participants').value=shuffledDefaultNames();$('participants').addEventListener('input',()=>{if(locked())return;overrides={};refresh();});$('default-count').addEventListener('input',()=>{overrides={};refresh();});document.querySelectorAll('input[name=rule]').forEach(e=>e.addEventListener('change',()=>refresh(false)));$('nth').addEventListener('input',()=>refresh(false));$('sample').addEventListener('click',()=>{if(locked())return;
$('participants').value=SAMPLE_NAMES.join(', ');$('default-count').value='1';overrides={};refresh();});$('view').addEventListener('click',()=>setMapView(renderer.overview?'follow':'full'));$('half-view').addEventListener('click',()=>setMapView(renderer.halfView?'follow':'half'));$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('reset').addEventListener('click',reset);$('edit').addEventListener('click',()=>{reset();if(gameMode==='lotto')document.querySelector('input[name=lotto-rule]:checked').focus();else $('participants').focus();});$('sound').addEventListener('click',toggleSound);$('arena-sound').addEventListener('click',toggleSound);$('motion').addEventListener('click',()=>{reduced=!reduced;setReduced();});
MAPS.forEach((map,i)=>{const land=LANDS[map.id];const b=document.createElement('button');b.className='map-choice';b.dataset.map=map.id;b.style.setProperty('--accent',land.color);b.setAttribute('aria-pressed',String(i===0));b.setAttribute('aria-label',land.label);const n=document.createElement('b');n.textContent=land.icon;n.setAttribute('aria-hidden','true');const t=document.createElement('span');t.textContent=land.label;b.append(n,t);b.addEventListener('click',()=>{if(locked())return;mapId=map.id;document.body.dataset.land=map.id;document.querySelectorAll('.map-choice').forEach(e=>e.setAttribute('aria-pressed',String(e===b)));$('map-name').textContent=land.name;$('map-index').textContent=`${land.tag} / 0${i+1}`;$('map-description').textContent=land.description;$('exit-legend').textContent=map.returnPoint?'노란 GOAL · 분홍 BACK은 중간으로':'중앙 골인 구멍 1개';$('board').setAttribute('aria-label',`${land.label} 3D 경기장. 도착 순위 목록에서 결과를 확인할 수 있습니다.`);refresh(false);});$('map-selector').append(b);});
function showRenderError(message,waiting=false){renderFault=true;race?.pause();accumulator=0;$('render-error').hidden=false;$('render-error-message').textContent=message;$('recover-renderer').disabled=waiting;$('recover-renderer').textContent=waiting?'연결 복구 기다리는 중…':'화면 복구하기';renderStatus();announce(message);}
document.addEventListener('pinball-renderer-lost',()=>{contextLost=true;showRenderError('그래픽 연결이 끊겨 공을 멈췄어요. 위치와 순위는 보관 중이에요. 연결이 돌아오면 화면을 복구할 수 있어요.',true);});
document.addEventListener('pinball-renderer-restored',()=>{contextLost=false;showRenderError('그래픽 연결이 돌아왔어요. 화면 복구 버튼을 눌러 주세요. 진행 중이던 경기는 일시정지를 유지해요.');});
$('board-motion').addEventListener('change',()=>refresh(false));
$('recover-renderer').addEventListener('click',()=>{if(contextLost)return;renderer.requestRebuild?.();renderFault=false;$('render-error').hidden=true;renderStatus();const target=race?.state==='paused'?'pause':race?.state==='complete'?($('winner-splash').hidden?'winner-name':'splash-name'):'start';$(target).focus({preventScroll:true});announce(race?.state==='paused'?'화면을 복구했습니다. 준비되면 재개 버튼을 눌러 주세요.':'화면을 복구했습니다. 설정과 경기 기록을 유지합니다.');});
$('arena-start').addEventListener('click',start);$('focus-mode').addEventListener('click',()=>setFocusMode(!document.body.classList.contains('play-focus')));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('winner-splash').hidden){e.preventDefault();closeWinnerSplash();return;}if(e.key==='Escape'&&document.body.classList.contains('play-focus')){setFocusMode(false);$('focus-mode').focus();}});
function closeWinnerSplash(){if($('winner-splash').hidden)return;const final=$('winner-splash').dataset.final==='true';$('winner-splash').hidden=true;splashUntil=0;if(final){setFocusMode(false);$('winner-card').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});$('winner-name').focus({preventScroll:true});}}
$('splash-replay').addEventListener('click',start);$('splash-close').addEventListener('click',closeWinnerSplash);
document.addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat||e.target.closest('input,textarea,button,select,summary,[contenteditable=true]'))return;if(race&&['mixing','countdown','racing','paused'].includes(race.state)&&!renderFault){e.preventDefault();pause();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)soundscape.stop();if(document.hidden&&race?.pause()){accumulator=0;renderStatus();announce('화면을 떠나 경기를 일시정지했습니다.');}});
function setGameMode(mode){if(locked()||!['player','lotto'].includes(mode))return;gameMode=mode;document.body.dataset.gameMode=mode;document.querySelectorAll('[data-game-mode]').forEach(b=>{const active=b.dataset.gameMode===mode;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('player-options').hidden=mode!=='player';$('lotto-options').hidden=mode!=='lotto';$('sample').hidden=mode==='lotto';refresh();announce(mode==='lotto'?'로또 모드. 1부터45까지, 숫자마다 공 하나입니다.':'플레이어 모드. 콤마로 이름을 구분해 주세요.');}
document.querySelectorAll('[data-game-mode]').forEach(b=>{b.addEventListener('click',()=>setGameMode(b.dataset.gameMode));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||locked())return;e.preventDefault();const mode=e.key==='Home'?'player':e.key==='End'?'lotto':gameMode==='player'?'lotto':'player';setGameMode(mode);$('tab-'+mode).focus();});});
document.querySelectorAll('input[name=lotto-rule]').forEach(input=>input.addEventListener('change',()=>refresh(false)));
setReduced();refresh();requestAnimationFrame(frame);
// Read-only diagnostics: no route to inject a winner or advance the simulation.
window.pinball=Object.freeze({audio:()=>soundscape.snapshot(),snapshot:()=>structuredClone(race?.snapshot()),performance:()=>({frames,averageCostMs:totalFrameCost/frames,samples:frameStats.map(s=>({...s})),graphics:renderer.graphics?.()}),settings:()=>({gameMode,sound,reduced,mapId,playbackSpeed,renderFault,contextLost,focusMode:document.body.classList.contains('play-focus'),viewMode:renderer.overview?'full':renderer.halfView?'half':'follow',physicsModule:new URL('./physics.js',import.meta.url).href,renderer:renderer.mode,camera:renderer.camera?.type||'Canvas2D'}),exportRound:()=>structuredClone({config:race.config,seed:race.seed,result:race.snapshot(),lotto:lottoResult(race.config,race.snapshot())})});
const modelContext=document.modelContext;if(modelContext?.registerTool){for(const tool of [{name:'read_pinball_race',description:'Read the current actual race state and finish order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.pinball.snapshot()},{name:'start_pinball_race',description:'Start a race with the visible validated participant and rule settings. Fails when a race is active.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!start())throw new Error('Race is active or input is invalid');return window.pinball.snapshot();}}]){try{Promise.resolve(modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
