import {Race,makeConfig,SAMPLE_NAMES,STEP,MAPS,COLORS} from './physics.js';
import {Renderer} from './renderer.js';
const $=id=>document.getElementById(id);const renderer=new Renderer($('board'));let playbackSpeed=1;let race=null,config=null,overrides={},mapId='neon',accumulator=0,last=0,slowUntil=0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,sound=false,selected=null,lastState='',lastFinish=-1,lastUi=0;
const frameStats=[];let frames=0,totalFrameCost=0,audio=null,master=null,lastHit=0;
const locked=()=>race&&['mixing','countdown','racing','paused','complete','invalid'].includes(race.state);
function rule(){return document.querySelector('input[name=rule]:checked').value;}
function ruleText(c){return c.rule==='first'?'첫 번째 도착':c.rule==='last'?`마지막 도착 (${c.total}번째)`:`${c.target}번째 도착`;}
function readConfig(){return {...makeConfig($('participants').value,$('default-count').value,rule(),$('nth').value,overrides),mapId};}
function announce(text){$('announcement').textContent=text;}
function tone(freq,duration=.06,type='sine',volume=.05){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+duration);}
async function toggleSound(){sound=!sound;$('sound').setAttribute('aria-pressed',String(sound));$('sound').querySelector('span').textContent=sound?'소리 켜짐':'소리 꺼짐';if(sound){try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(!master){master=audio.createGain();master.connect(audio.destination);}master.gain.value=.65;await audio.resume();tone(560,.08);}catch{sound=false;$('sound').setAttribute('aria-pressed','false');$('sound').querySelector('span').textContent='소리 사용 불가';}}else if(master)master.gain.value=0;}
function setReduced(){document.body.classList.toggle('reduced',reduced);$('motion').setAttribute('aria-pressed',String(reduced));if(reduced){slowUntil=0;$('confetti').replaceChildren();}}
function renderRoster(people){$('roster').replaceChildren();people.forEach((p,i)=>{const row=document.createElement('div');row.className='roster-row';const dot=document.createElement('span');dot.className='color-dot';dot.style.setProperty('--color',p.color);const label=document.createElement('label');label.textContent=p.label;label.htmlFor=`count-${i}`;const input=document.createElement('input');input.id=`count-${i}`;input.type='text';input.inputMode='numeric';input.value=p.count;input.setAttribute('aria-label',`${p.label} 공 개수`);input.addEventListener('input',()=>{if(locked())return;overrides[i]=input.value;refresh(false);});row.append(dot,label,input);$('roster').append(row);});}
function refresh(roster=true){if(locked())return;try{config=readConfig();$('input-error').textContent='';$('participant-summary').replaceChildren();const a=document.createElement('span');a.textContent=`참가자 ${config.people.length}명`;const b=document.createElement('strong');b.textContent=`공 ${config.total}개`;$('participant-summary').append(a,b);$('rule-summary').textContent=ruleText(config);$('live-rule').textContent=ruleText(config)+'하면 당첨';$('nth-row').hidden=rule()!=='nth';if(roster)renderRoster(config.people);race=new Race(config);lastState='';lastFinish=-1;accumulator=0;resetResult();renderStatus();}catch(e){config=null;$('input-error').textContent=e.message;$('participant-summary').textContent='입력을 확인해 주세요.';$('nth-row').hidden=rule()!=='nth';$('start').disabled=false;}}
function resetResult(){selected=null;$('winner-card').classList.remove('celebrated');$('winner-name').textContent='아직 비밀!';$('winner-caption').textContent='오늘의 주인공은';$('winner-detail').textContent='공이 결승선을 통과하면 당첨자가 이곳에 나타나요.';$('winner-orb').textContent='?';$('ranking').replaceChildren();$('ranking-empty').hidden=false;$('confetti').replaceChildren();slowUntil=0;}
function start(){if(race&&['mixing','countdown','racing','paused'].includes(race.state))return false;try{const c=locked()?race.config:readConfig();race=new Race(c);config=c;frameStats.length=0;frames=0;totalFrameCost=0;resetResult();race.start();accumulator=0;lastFinish=-1;renderStatus();announce(`${MAPS.find(m=>m.id===mapId).name}, 공 ${c.total}개. ${ruleText(c)}하면 당첨입니다. 공을 섞습니다.`);if(innerWidth<701)$('board').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});return true;}catch(e){$('input-error').textContent=e.message;announce(e.message);return false;}}
function reset(){race=null;lastState='';accumulator=0;overrides={...overrides};$('settings').disabled=false;refresh();$('start').textContent='공 섞고 시작하기 ↗';}
function pause(){if(race.state==='paused')race.resume();else race.pause();accumulator=0;renderStatus();announce(race.state==='paused'?'경기가 일시정지되었습니다.':'경기를 재개합니다.');}
function celebrate(w){$('winner-card').classList.add('celebrated');$('winner-card').style.setProperty('--winner-color',w.color);$('winner-name').textContent=w.label;$('winner-caption').textContent='당첨 공 도착 · 완주 확인 중';$('winner-detail').textContent=`${w.rank}번째 도착 · ${w.number}번 공 · ${w.time.toFixed(3)}초`;$('winner-orb').textContent=String(w.rank);selected=w.id;announce(`${w.label}, ${w.rank}번째로 도착해 당첨!`);for(const [i,f]of [523,659,784,1046].entries())setTimeout(()=>tone(f,.2,'triangle',.08),i*90);
 if(!reduced){slowUntil=performance.now()+1000;for(let i=0;i<34;i++){const e=document.createElement('i');e.className='confetti-piece';e.style.setProperty('--x',`${(i*37)%100}%`);e.style.setProperty('--color',COLORS[i%8]);e.style.setProperty('--rot',`${i*19}deg`);e.style.animationDelay=`${i%6*.05}s`;$('confetti').append(e);}setTimeout(()=>$('confetti').replaceChildren(),2400);}}
function showRanks(){if(lastFinish===race.finishOrder.length)return;lastFinish=race.finishOrder.length;$('ranking-empty').hidden=lastFinish>0;$('ranking').replaceChildren();for(const r of race.finishOrder){const li=document.createElement('li');li.className='rank-row'+(r.rank===race.config.target?' target':'');li.dataset.ballId=r.id;li.dataset.rank=r.rank;const num=document.createElement('span');num.className='rank-number';num.textContent=String(r.rank).padStart(2,'0');const dot=document.createElement('span');dot.className='color-dot';dot.style.setProperty('--color',r.color);const name=document.createElement('span');name.className='rank-name';name.textContent=r.label;const detail=document.createElement('small');detail.textContent=`${r.number}번 공${r.rank===race.config.target?' · 당첨':''}`;name.append(detail);const time=document.createElement('span');time.className='rank-time';time.textContent=r.time.toFixed(2)+'s';li.append(num,dot,name,time);$('ranking').append(li);}}
function renderStatus(){if(!race)return;const s=race.state,live=['mixing','countdown','racing','paused'].includes(s);document.body.dataset.state=s;$('settings').disabled=locked();$('sample').disabled=locked();for(const b of document.querySelectorAll('.map-choice'))b.disabled=locked();$('start').disabled=live;$('start').textContent=s==='complete'||s==='invalid'?'다시 플레이 ↗':live?'레이스 진행 중':'공 섞고 시작하기 ↗';$('edit').hidden=!['complete','invalid'].includes(s);$('pause').disabled=!live;$('pause').textContent=s==='paused'?'▶ 재개':'Ⅱ 일시정지';$('pause-overlay').hidden=s!=='paused';const stateLabels={ready:'READY',mixing:'MIXING',countdown:'GET READY',racing:'RACING',paused:'PAUSED',complete:'FINISHED',invalid:'VOID'};$('state-tag').textContent=stateLabels[s];$('countdown').hidden=s!=='countdown';if(s==='countdown')$('countdown').textContent=Math.max(1,Math.ceil(3-race.phaseTime));$('progress').textContent=`${race.finishOrder.length} / ${race.balls.length} 도착`;$('finished-count').textContent=`${race.finishOrder.length} FINISHED`;$('timer').textContent=`${String(Math.floor(race.raceTime/60)).padStart(2,'0')}:${(race.raceTime%60).toFixed(1).padStart(4,'0')}`;
 const message={ready:'공들이 출발을 기다리고 있어요',mixing:'출발 전에 공을 골고루 섞는 중',countdown:'게이트가 곧 열립니다',racing:race.winner?'당첨! 남은 공도 끝까지 달려요':'한 번의 충돌로, 순위는 다시 바뀌어요',paused:'일시정지 · 위치와 순위가 유지돼요',complete:'모든 공 도착! 다음 레이스도 함께해요',invalid:'완주하지 못한 경기 · 결과 무효, 다시 플레이해 주세요'};$('race-message').textContent=message[s]+(race.assists?` · 탈출 보조 ${race.assists}회`:'');if(s==='invalid'){resetResult();$('winner-name').textContent='무효 경기';$('winner-detail').textContent='90초 내 미완주 또는 물리 오류. 당첨 결과를 사용하지 말고 다시 시작해 주세요.';}
 showRanks();if(lastState!==s){if(s==='racing'){tone(880,.2,'triangle');announce('게이트가 열렸습니다. 출발!');}if(s==='complete'){$('winner-caption').textContent='오늘의 당첨자 · 확정';}if(s==='complete')announce(`모든 공이 도착했습니다. 당첨자는 ${race.winner?.label}입니다.`);lastState=s;}}
function frame(now){const begin=performance.now();const rawDelta=last?now-last:0;const dt=Math.min(rawDelta/1000,.1);last=now;if(race){const scale=!reduced&&now<slowUntil?.32:1;accumulator+=dt*scale*playbackSpeed;if(!['mixing','countdown','racing'].includes(race.state))accumulator=0;while(accumulator>=STEP){race.step();accumulator-=STEP;}
 const events=race.events.splice(0);for(const ev of events){if(ev.type==='hit'&&now-lastHit>65){tone(160+Math.min(ev.speed,550),.04,'sine',.025);lastHit=now;}if(ev.type==='finish')tone(740,.09,'triangle',.045);if(ev.type==='winner')celebrate(ev.result);}
 renderer.draw(race,reduced,selected);if(now-lastUi>80){renderStatus();lastUi=now;}}
 const cost=performance.now()-begin;frames++;totalFrameCost+=cost;if(frameStats.length<1200)frameStats.push({delta:rawDelta,cost,state:race?.state,total:race?.balls.length});else{frameStats.shift();frameStats.push({delta:rawDelta,cost,state:race?.state,total:race?.balls.length});}requestAnimationFrame(frame);}
document.querySelectorAll('[data-speed]').forEach(button=>button.addEventListener('click',()=>{playbackSpeed=Number(button.dataset.speed);document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));announce(`${playbackSpeed}배속으로 재생합니다.`);}));
$('participants').value=SAMPLE_NAMES.join('\n');$('participants').addEventListener('input',()=>{if(locked())return;overrides={};refresh();});$('default-count').addEventListener('input',()=>{overrides={};refresh();});document.querySelectorAll('input[name=rule]').forEach(e=>e.addEventListener('change',()=>refresh(false)));$('nth').addEventListener('input',()=>refresh(false));$('sample').addEventListener('click',()=>{if(locked())return;document.querySelectorAll('[data-speed]').forEach(button=>button.addEventListener('click',()=>{playbackSpeed=Number(button.dataset.speed);document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));announce(`${playbackSpeed}배속으로 재생합니다.`);}));
$('participants').value=SAMPLE_NAMES.join('\n');$('default-count').value='1';overrides={};refresh();});$('view').addEventListener('click',()=>{renderer.overview=!renderer.overview;$('view').setAttribute('aria-pressed',String(renderer.overview));$('view').textContent=renderer.overview?'따라가기':'전체 맵';});$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('reset').addEventListener('click',reset);$('edit').addEventListener('click',()=>{reset();$('participants').focus();});$('sound').addEventListener('click',toggleSound);$('motion').addEventListener('click',()=>{reduced=!reduced;setReduced();});
MAPS.forEach((map,i)=>{const b=document.createElement('button');b.className='map-choice';b.dataset.map=map.id;b.style.setProperty('--accent',map.accent);b.setAttribute('aria-pressed',String(i===0));const n=document.createElement('b');n.textContent=['⠿','◎','ϟ','⋈'][i];const t=document.createElement('span');t.textContent=map.subtitle;b.append(n,t);b.addEventListener('click',()=>{if(locked())return;mapId=map.id;document.querySelectorAll('.map-choice').forEach(e=>e.setAttribute('aria-pressed',String(e===b)));$('map-name').textContent=map.name;$('map-index').textContent=`THE ORIGINAL / MAP 0${i+1}`;refresh(false);});$('map-selector').append(b);});
document.addEventListener('pinball-renderer-lost',()=>{race?.pause();renderStatus();announce('그래픽 연결이 끊겨 일시정지했습니다. 페이지를 새로고침해 주세요.');});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&race?.pause()){accumulator=0;renderStatus();announce('화면을 떠나 경기를 일시정지했습니다.');}});
setReduced();refresh();requestAnimationFrame(frame);
// Read-only diagnostics: no route to inject a winner or advance the simulation.
window.pinball=Object.freeze({snapshot:()=>race?.snapshot(),performance:()=>({frames,averageCostMs:totalFrameCost/frames,samples:frameStats.slice()}),settings:()=>({sound,reduced,mapId,playbackSpeed,renderer:renderer.mode}),exportRound:()=>({config:race.config,seed:race.seed,result:race.snapshot()})});
const modelContext=document.modelContext;if(modelContext?.registerTool){for(const tool of [{name:'read_pinball_race',description:'Read the current actual race state and finish order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.pinball.snapshot()},{name:'start_pinball_race',description:'Start a race with the visible validated participant and rule settings. Fails when a race is active.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!start())throw new Error('Race is active or input is invalid');return window.pinball.snapshot();}}]){try{Promise.resolve(modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
