import {assetPath} from '../base.js';
import '@fontsource-variable/dm-sans';
import '@fontsource-variable/noto-sans-kr';
import './style.css';
import {analyzeSvg} from '../core/analysis.js';
import {sampleRoute} from '../core/routing.js';
import {filterMobilitySources,parkingEnvelope,vehicleRoute} from '../core/mobility.js';

const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories={all:'전체 자료',plans:'도면·실제 주행',vehicles:'차량 제원',charging:'충전 위치·수요'};
const number=n=>Number.isFinite(n)?n.toFixed(2):'미확인';
let data,plan,vehicle,category='all',query='',result,playing=false,travel=0,last=0,frame;
document.querySelector('#mobility-app').innerHTML=`
 <header><a class="brand" href="${assetPath('/')}">▱ <strong>ATLAS</strong><span>SPATIAL INTELLIGENCE</span></a><nav aria-label="주 메뉴"><a href="${assetPath('/')}">도면 연구소</a><a href="${assetPath('/mobility.html')}" aria-current="page">실차·충전 데이터</a><a href="${assetPath('/reports/mobility/')}">검증 보고서 ↗</a></nav></header>
 <main><section class="intro"><div><span class="eyebrow">MOBILITY DATA COLLECTION / 01</span><h1>실차 경로·<br><em>충전 데이터.</em></h1><p>실제 도면과 차량 제원, 충전 위치·수요를 한 곳에서.<br>공간마다 무엇이 확인됐는지 살펴보고 다음 검토로 이어가세요.</p></div><aside class="collection-note"><span class="eyebrow">EVIDENCE BEFORE ESTIMATION</span><p>도면의 선 위에,<br><strong>차량의 크기를 더합니다.</strong></p><div id="collection-stats">공개 자료를 읽고 있습니다.</div></aside></section>
 <section class="route-section" aria-labelledby="route-title"><div class="section-heading"><div><span class="eyebrow">01 / ROUTE EXPLORER</span><h2 id="route-title">실제 B2 도면에서 동선 후보 비교</h2></div><a href="${assetPath('/?workspace=source-drive')}">3D 주행 화면 열기 ↗</a></div><div class="route-workbench"><div class="plan-view"><div class="plan-top"><span>동북권 복합시설 · B2</span><span class="status">수동 주석 · 추정 축척</span></div><svg id="route-map" role="img" aria-label="실제 B2 원본 도면과 차폭으로 비교한 동선 후보"></svg><div class="plan-legend"><span><i></i> 차폭 기준 동선 후보</span><span>회전 궤적·벽체 간섭 미검증</span></div></div><aside class="route-settings"><span class="eyebrow">VEHICLE PROFILE</span><label>제조사 제원<select id="vehicle" aria-label="차량 제원 선택"></select></label><div id="vehicle-dimensions" class="dimensions"></div><label>도착 지점<select id="destination" aria-label="도착 지점"></select></label><label>편측 여유 폭 <output id="clearance-value">0.35 m</output><input id="clearance" aria-label="편측 여유 폭" type="range" min="0.1" max="2" value="0.35" step="0.05"></label><div id="route-summary" role="status"></div><button id="drive" class="primary" disabled>동선 재생</button><p class="small-note">실제 차량 제원으로 차폭 조건을 비교합니다. 미러·문 개방과 조향 시 차체 궤적은 별도 검토가 필요합니다.</p></aside></div></section>
 <section class="charging-section" aria-labelledby="charging-title"><div class="section-heading"><div><span class="eyebrow">02 / CHARGING LOCATION EVIDENCE</span><h2 id="charging-title">설치 위치를 검토할 수 있는 자료</h2></div></div><div class="charging-grid"><article class="featured-source"><span class="pill">새로 확인한 실제 설계 도면</span><h3>차로와 충전 주차면을<br>함께 보는 주차 계획.</h3><p>Palo Alto · 3606 El Camino Real<br>AP0.10 · 1·2층 주차 계획 · 2024.05.31</p><div class="evidence-numbers"><div><strong>41<span>면</span></strong><small>원문에 기재된 EV Charger 계획</small></div><div><strong>9 × 18<span>ft</span></strong><small>일반 EV 주차면 표기</small></div></div><a id="palo-source" target="_blank" rel="noopener">원본 10쪽에서 위치 보기 ↗</a><p class="small-note">계획 위치이며 현재 설치·가동 여부는 미확인입니다. 자동으로 산출한 최적 위치를 뜻하지 않습니다.</p></article><article class="fit-card"><span class="eyebrow">VEHICLE × PARKING FOOTPRINT</span><h3>선택한 차량과 주차면</h3><div class="envelope"><svg id="envelope" viewBox="0 0 200 210" role="img" aria-label="제조사 차량 외곽과 원문 EV 주차면 크기 비교"></svg><div id="envelope-summary"></div></div><p class="small-note">원문의 9 × 18ft를 미터로 환산한 외곽 치수 비교입니다. 차량을 가운데 놓았을 때의 여유이며, 승하차·충전 케이블·접근성 공간을 포함하지 않습니다.</p></article><article class="readiness-card"><span class="eyebrow">NEXT / SITE SURVEY</span><h3>추천 후보를 계산하려면</h3><ul><li><span>선택 도면·층</span><b class="ready">B2 연결됨</b></li><li><span>배선 경로·회로 여유 용량</span><b>현장 입력</b></li><li><span>사업자별 실내 통신 측정</span><b>현장 입력</b></li><li><span>설치·보행 접근 공간</span><b>현장 확인</b></li><li><span>충전량·체류 시간</span><b>ACN 연구 자료</b></li></ul><a class="secondary" href="${assetPath('/?workspace=source-charging')}">B2 충전기 설치 검토 열기 ↗</a><p class="small-note">서로 다른 시설의 데이터는 하나의 실측값으로 합치지 않습니다. 필수 자료가 없으면 추천을 보류합니다.</p></article></div></section>
 <section class="catalog-section" aria-labelledby="data-title"><div class="section-heading"><div><span class="eyebrow">03 / SOURCE LIBRARY</span><h2 id="data-title">필요한 데이터를 찾아보세요.</h2></div><button id="export" class="text-button">현재 자료 목록 내려받기 ↓</button></div><div class="catalog-tools"><div class="filters" role="group" aria-label="자료 카테고리">${Object.entries(categories).map(([id,name])=>`<button data-category="${id}" aria-pressed="${id==='all'}">${name}</button>`).join('')}</div><label class="search"><span>⌕</span><input id="query" type="search" aria-label="자료 검색" placeholder="차로, 회로, 충전량, 기관 검색"></label></div><p id="result-count" class="result-count" role="status"></p><div id="source-grid" class="source-grid"></div></section>
 <footer><span>ATLAS / SOURCE-BASED MOBILITY</span><span>원문 확인 2026.09.21 · 실시간 API 연결 전</span><a href="${assetPath('/reports/mobility/')}">새 카테고리 검증 결과 ↗</a></footer></main>
 <dialog id="source-dialog"><button id="close-dialog" aria-label="자료 상세 닫기">×</button><div id="source-detail"></div></dialog><div id="load-error" role="alert" hidden></div>`;

function renderCatalog(){
 const sources=filterMobilitySources(data.sources,{category,query});$('#result-count').textContent=`${sources.length}개 자료 · 출처와 확보 상태를 함께 확인하세요`;
 $('#source-grid').innerHTML=sources.length?sources.map(s=>`<article class="source-card" data-source="${s.id}"><div class="source-meta"><span>${esc(categories[s.category])}</span><span class="access ${s.access==='키 필요'?'key':''}">${esc(s.access)}</span></div><h3>${esc(s.title)}</h3><p class="provider">${esc(s.provider)}<br>${esc(s.region)}</p><p>${esc(s.summary)}</p><div class="tags">${s.fields.map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="use"><strong>활용</strong> ${esc(s.use)}</p><div class="card-actions"><button data-detail="${s.id}">근거·활용 범위 보기 +</button><a href="${esc(s.url)}" target="_blank" rel="noopener" aria-label="${esc(s.title)} 원문">원문 ↗</a></div></article>`).join(''):'<div class="empty"><h3>일치하는 자료가 없습니다.</h3><p>다른 검색어를 입력하거나 전체 자료를 선택하세요.</p><button id="clear-search">검색 초기화</button></div>';
 $('#clear-search')?.addEventListener('click',()=>{query='';category='all';$('#query').value='';updateFilters();renderCatalog();});
 document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>showSource(button.dataset.detail));
}
function updateFilters(){document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));}
function showSource(id){
 const s=data.sources.find(s=>s.id===id);
 $('#source-detail').innerHTML=`<span class="eyebrow">${esc(categories[s.category])} / ${esc(s.access)}</span><h2>${esc(s.title)}</h2><p>${esc(s.provider)} · ${esc(s.region)}</p><h3>확인된 내용</h3><p>${esc(s.summary)}</p><div class="tags">${s.fields.map(f=>`<span>${esc(f)}</span>`).join('')}</div><h3>활용 범위</h3><p>${esc(s.use)}</p><p class="detail-note">${esc(s.limits)}</p><dl><dt>이용 조건</dt><dd>${esc(s.license)}</dd><dt>원문 확인일</dt><dd>${s.verifiedAt}</dd>${s.sourceSha256?`<dt>확인한 원문 SHA-256</dt><dd class="hash">${s.sourceSha256}</dd>`:''}</dl><div class="detail-links"><a href="${esc(s.url)}" target="_blank" rel="noopener">공식 원문 열기 ↗</a>${s.local?`<a href="${assetPath(s.local)}" target="_blank" rel="noopener">로컬 원본 열기 ↗</a>`:''}${s.related?`<a href="${esc(s.related)}" target="_blank" rel="noopener">관련 공식 자료 ↗</a>`:''}</div>`;
 $('#source-dialog').showModal();
}
function renderRoute(){
 playing=false;travel=0;vehicle=data.vehicles.find(v=>v.id===$('#vehicle').value);
 const clearance=Number($('#clearance').value);$('#clearance-value').textContent=clearance.toFixed(2)+' m';
 result=vehicleRoute(plan,'entrance',$('#destination').value,vehicle,clearance);
 $('#vehicle-dimensions').innerHTML=`<div><b>${vehicle.length.toFixed(3)} m</b><small>전장</small></div><div><b>${vehicle.width.toFixed(2)} m</b><small>차체 폭</small></div><div><b>${number(vehicle.turningDiameter)}${vehicle.turningDiameter?' m':''}</b><small>최소 회전 원 지름</small></div><p>${esc(vehicle.variant)} · <button id="vehicle-source">제원 출처 ↗</button></p>`;
 $('#vehicle-source').onclick=()=>showSource(vehicle.sourceId);
 $('#route-summary').innerHTML=result.path?`<strong>${result.path.distance.toFixed(1)}<span> m</span></strong><p>차로 폭 ${result.minimumWidth.toFixed(2)} m 이상으로 연결<br>추정 축척의 차로 중심선 거리</p>`:'<strong class="no-route">동선 후보 없음</strong><p>차폭과 여유 폭을 충족하는 연결이 없습니다.</p>';
 $('#drive').disabled=!result.path;$('#drive').textContent='동선 재생';
 const box=[-plan.width/2,-plan.depth/2,plan.width,plan.depth];$('#route-map').setAttribute('viewBox',box.join(' '));
 $('#route-map').innerHTML=`<defs><pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="#dde5db" stroke-width=".07"/></pattern></defs><rect x="${box[0]}" y="${box[1]}" width="${box[2]}" height="${box[3]}" fill="url(#grid)"/><image href="${assetPath('/plans/changdong-parking-b2.png')}" x="-95.85" y="-67.05" width="162" height="121.5" opacity=".6"/>${plan.edges.map(e=>{const a=plan.nodes.find(n=>n.id===e.from),b=plan.nodes.find(n=>n.id===e.to);return `<line x1="${a.x}" y1="${a.z}" x2="${b.x}" y2="${b.z}" stroke="${result.blocked.includes(e.id)?'#d7a48d':'#a4b7ae'}" stroke-width=".45" stroke-dasharray="1 1"/>`;}).join('')}${result.path?`<polyline points="${result.path.points.map(p=>`${p.x},${p.z}`).join(' ')}" fill="none" stroke="#287761" stroke-width="1.05" stroke-linejoin="round"/>`:''}${plan.nodes.filter(n=>n.kind==='building'||n.kind==='entrance').map(n=>`<g><circle cx="${n.x}" cy="${n.z}" r="1.7" fill="${n.kind==='entrance'?'#ad8154':'#2f6c58'}" stroke="white" stroke-width=".3"/><text x="${n.x}" y="${n.z+.5}" text-anchor="middle" fill="white" font-size="1.6">${n.id==='entrance'?'IN':n.id}</text></g>`).join('')}<g id="route-car"><rect x="${-vehicle.width/2-.25}" y="${-vehicle.length/2-.2}" width="${vehicle.width+.5}" height="${vehicle.length+.4}" fill="#fff" rx=".45"/><rect x="${-vehicle.width/2}" y="${-vehicle.length/2}" width="${vehicle.width}" height="${vehicle.length}" rx=".4" fill="#c17d45"/><rect x="${-vehicle.width*.38}" y="${vehicle.length*.1}" width="${vehicle.width*.76}" height="${vehicle.length*.23}" rx=".15" fill="#f5eacb"/></g>`;
 moveCar();renderEnvelope();
}
function renderEnvelope(){
 const stall={width:2.7432,length:5.4864},fit=parkingEnvelope(vehicle,stall),scale=30;
 $('#envelope').innerHTML=`<rect x="${100-stall.width*scale/2}" y="16" width="${stall.width*scale}" height="${stall.length*scale}" fill="#e4eede" stroke="#97ac90" stroke-width="2"/><path d="M 64 23 H 136" stroke="#718d73" stroke-width="5"/><rect x="${100-vehicle.width*scale/2}" y="${16+(stall.length-vehicle.length)*scale/2}" width="${vehicle.width*scale}" height="${vehicle.length*scale}" rx="9" fill="#3b6b5d"/><rect x="${100-vehicle.width*scale*.35}" y="48" width="${vehicle.width*scale*.7}" height="25" rx="4" fill="#adc6ba"/><text x="100" y="200" text-anchor="middle" fill="#607365" font-size="11">2.743 × 5.486 m</text>`;
 $('#envelope-summary').innerHTML=`<strong>${esc(vehicle.name)}</strong><p>가운데 정렬 시 편측 여유<br><b>${fit.side.toFixed(3)} m</b></p><p>전후 여유 합계<br><b>${fit.length.toFixed(3)} m</b></p>`;
}
function moveCar(){const p=sampleRoute(result.path,travel)||plan.nodes.find(n=>n.id==='entrance');$('#route-car').setAttribute('transform',`translate(${p.x} ${p.z}) rotate(${-(p.heading||0)*180/Math.PI})`);}
function animate(now){const dt=Math.min((now-last)/1000,.1);last=now;if(playing&&result?.path){travel=Math.min(result.path.distance,travel+dt*3.5);moveCar();if(travel===result.path.distance){playing=false;$('#drive').textContent='다시 재생';}}frame=requestAnimationFrame(animate);}

try{
 const responses=await Promise.all([fetch(assetPath('/mobility/catalog.json')),fetch(assetPath('/plans/changdong-parking-annotated.svg'))]);if(responses.some(r=>!r.ok))throw new Error('자료를 불러오지 못했습니다. 새로고침해 주세요.');
 data=await responses[0].json();plan=analyzeSvg(await responses[1].text());
 $('#collection-stats').innerHTML=`<div><b>${data.sources.length}</b><span>출처별 자료</span></div><div><b>${data.vehicles.length}</b><span>제조사 차량 제원</span></div><div><b>3</b><span>데이터 분류</span></div>`;
 $('#vehicle').innerHTML=data.vehicles.map(v=>`<option value="${v.id}">${v.name} · ${v.variant}</option>`).join('');$('#destination').innerHTML=plan.nodes.filter(n=>n.kind==='building').map(n=>`<option value="${n.id}">${n.id} · ${n.label}</option>`).join('');
 $('#palo-source').href=data.sources.find(s=>s.id==='palo-alto').url;
 for(const id of ['vehicle','destination','clearance'])$('#'+id).addEventListener('input',renderRoute);
 $('#drive').onclick=()=>{if(travel===result.path.distance)travel=0;playing=!playing;$('#drive').textContent=playing?'일시정지':'동선 재생';};
 document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;updateFilters();renderCatalog();});
 $('#query').oninput=e=>{query=e.target.value;renderCatalog();};$('#close-dialog').onclick=()=>$('#source-dialog').close();
 $('#export').onclick=()=>{const content={...data,sources:filterMobilitySources(data.sources,{category,query})};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='atlas-mobility-sources.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 renderCatalog();renderRoute();frame=requestAnimationFrame(animate);document.body.dataset.ready='true';
 window.__mobility={get state(){return {category,query,vehicle,result,playing,travel};}};
}catch(error){$('#load-error').hidden=false;$('#load-error').textContent=error.message;}
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;$('#drive').textContent='동선 재생';}});window.addEventListener('pagehide',()=>cancelAnimationFrame(frame));
