import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const read=name=>fs.readFileSync(path.join(root,name));
const json=name=>JSON.parse(read(name).toString('utf8'));
const report=json('report.json'),denied=json('denied-cases.json'),forwarded=json('forwarded-requests.json'),results=json('valid-results.json'),initial=json('initial-state.json'),final=json('final-state.json');
const events=read('events.jsonl').toString('utf8').trim().split(/\r?\n/).map(JSON.parse);
assert.equal(report.complete,true);assert.equal(denied.length,11);
for(const row of denied){assert.equal(row.http_status,403);assert.equal(row.ws_status,403);assert.equal(row.backend_forward_delta,0);}
assert.equal(forwarded.length,12);assert.equal(events.filter(x=>x.event==='backend_forward').length,12);
assert.ok(forwarded.every(x=>x.headers.origin===undefined));
assert.ok(forwarded.some(x=>x.url==='/api/commands'&&x.headers['x-session-token']==='demo-user-02'));
const firstDeny=events.findIndex(x=>x.event==='http_result'&&x.request_body?.request_id==='denied-cross-origin');
const lastDeny=events.findLastIndex(x=>x.event==='ws_handshake_response');
assert.ok(firstDeny>=0&&lastDeny>firstDeny);
assert.equal(events.slice(firstDeny,lastDeny+1).filter(x=>x.event==='backend_forward').length,0);
assert.equal(events.filter(x=>x.event==='ws_handshake_response'&&x.result.status===403).length,11);
assert.equal(events.filter(x=>x.event==='ws_handshake_upgrade'&&x.status===101).length,1);
assert.ok(events.some(x=>x.event==='ws_frame'&&x.opcode===8&&x.close_code===1000));
const frameStates=events.filter(x=>x.event==='ws_frame'&&x.opcode===1).map(x=>x.value.state);
assert.deepEqual(frameStates.find(x=>x.event_seq===0),initial);assert.deepEqual(frameStates.find(x=>x.event_seq===3),final);
assert.equal(final.command_seq,3);assert.equal(final.volume,2);assert.deepEqual(final.bids,[]);assert.deepEqual(final.asks,[]);
assert.equal(final.accounts.reduce((sum,x)=>sum+x.points_available+x.points_reserved,0),15000000);
assert.equal(final.accounts.reduce((sum,x)=>sum+x.hours_available+x.hours_reserved,0),15000);
assert.ok(final.accounts.every(x=>x.points_reserved===0&&x.hours_reserved===0));
assert.deepEqual(results.retry.body,{...results.taker.body,duplicate:true});assert.deepEqual(results.lookup.body,results.taker.body);
assert.equal(results.taker.body.trades[0].price,1000);assert.equal(results.taker.body.trades[0].quantity,2);assert.equal(results.invalidToken.status,401);
assert.deepEqual(report.protected_after,report.protected_before);assert.equal(report.protected_before.processes.length,18);
assert.equal(report.engine_exit.success,true);assert.equal(report.engine_exit.exit_code,0);assert.equal(report.engine_exit.forced,false);assert.equal(report.engine_pid_absent,true);
assert.deepEqual(Object.values(report.remaining_fixture_sockets),[0,0,0,0]);
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
const crc=buffer=>{let n=0xffffffff;for(const byte of buffer)n=table[(n^byte)&255]^(n>>>8);return(n^0xffffffff)>>>0;};
const journal=read('data/journal.bin'),records=[];
for(let offset=0;offset<journal.length;){const h=journal.subarray(offset,offset+32),length=h.readUInt32LE(12),payload=journal.subarray(offset+32,offset+32+length);assert.equal(h.toString('ascii',0,8),'LVJRNL01');assert.equal(h.readUInt16LE(8),1);assert.equal(crc(h.subarray(0,28)),h.readUInt32LE(28));assert.equal(crc(payload),h.readUInt32LE(24));records.push({sequence:Number(h.readBigUInt64LE(16)),command:JSON.parse(payload)});offset+=32+length;}
assert.deepEqual(records.map(x=>x.sequence),[1,2,3,4]);assert.deepEqual(records.map(x=>x.command.request_id),['proxy-maker','proxy-taker','proxy-taker','proxy-cancel']);
const analysis={verified:true,analyzed_at:new Date().toISOString(),scope:'Offline recomputation from one real isolated integration run',forwarded_requests:12,invalid_cases:11,invalid_http_and_ws_responses:22,backend_forwards_during_denied_cases:0,ws_state_sequences:frameStates.map(x=>x.event_seq),unique_admitted_commands:3,journal_records_including_duplicate:4,journal_sha256:crypto.createHash('sha256').update(journal).digest('hex'),journal:records,assets:{points:15000000,hours:15000,reserves:0,volume:2},protected_pids_unchanged:18,engine_exit0:true,engine_pid_absent:true,all_fixture_sockets_closed:true,no_main_services_controlled:true,no_performance_claim:true};
fs.writeFileSync(path.join(root,'analysis.json'),JSON.stringify(analysis,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(analysis));
