import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { resourceMemoryRows, resourceProcessIdentity, sameResourceProcessIdentity } from './source/resource-memory.mjs';
import { resourceCpu } from './source/resource-cpu.mjs';
const run=path.dirname(fileURLToPath(import.meta.url));const evidence=path.dirname(run);
const previous=path.join(evidence,'2026-09-21T13-42-38-482Z-observer-pid-reuse-review-3dbd3323');
const bytes=fs.readFileSync(path.join(previous,'observer-prefix-2522.raw.jsonl'));
const sha=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(sha,'d87a03738565ac0b39ec117bb3c5fefcf5837438b36426cd2a4b73c86a9aec4e');
const samples=bytes.toString('utf8').trim().split(/\r?\n/).map(JSON.parse);
const original=JSON.parse(fs.readFileSync(path.join(previous,'analysis-original.json')));
const independent=JSON.parse(fs.readFileSync(path.join(previous,'review.json')));
const corrected=JSON.parse(fs.readFileSync(path.join(evidence,'2026-09-21T13-42-39-992Z-observation-analysis-8a1b6dc1','analysis.json')));
const resourceObservations=samples.filter(row=>Object.hasOwn(row,'resources'));
const baseline=resourceObservations.find(row=>resourceProcessIdentity(row.resources,14)!==null);
const identity=resourceProcessIdentity(baseline.resources,14);
const accepted=resourceObservations.filter(row=>resourceMemoryRows(row.resources,14,identity)!==null);
const changed=resourceObservations.filter(row=>resourceProcessIdentity(row.resources,14)!==null&&!sameResourceProcessIdentity(row.resources,identity)).map(row=>({at:row.at,reason:'process_set_changed_from_initial_sample'}));
const totals=accepted.map(row=>({at:row.at,process_count:row.resources.length,working_set_bytes:row.resources.reduce((sum,p)=>sum+p.WorkingSet64,0),private_bytes:row.resources.reduce((sum,p)=>sum+p.PrivateMemorySize64,0)}));
const cpu=resourceCpu(samples,16,14);
const engineRows=accepted.map(row=>({at:row.at,event_seq:row.event_seq,...row.resources.find(p=>p.Id===20540&&p.ProcessName==='leave-engine')}));
const firstEngine=engineRows[0],lastEngine=engineRows.at(-1);
assert.equal(samples.length,2522);assert.equal(accepted.length,313);assert.equal(totals.at(-1).at,'2026-09-21T12:44:21.449Z');assert.deepEqual(changed,[{at:'2026-09-21T13:28:15.297Z',reason:'process_set_changed_from_initial_sample'}]);
assert.deepEqual(totals.at(-1),corrected.tracked_process_total_memory_windows.last);
assert.equal(totals.at(-1).working_set_bytes,independent.memory_effect.baseline_identity_last.working_set_bytes);
assert.equal(totals.at(-1).private_bytes,independent.memory_effect.baseline_identity_last.private_bytes);
assert.equal(cpu.interval_count,312);assert.deepEqual(cpu.intervals,original.cpu_windows.intervals);assert.deepEqual(cpu.intervals,corrected.cpu_windows.intervals);
for(const key of ['cpu_seconds','covered_interval_seconds','mean_percent_total_capacity','max_interval_percent_total_capacity'])assert.equal(cpu[key],original.cpu_windows[key]);
assert.deepEqual(cpu.process_identity_baseline.processes,identity);assert.deepEqual(corrected.memory_sample_validation.process_identity_baseline.processes,identity);
assert.equal(lastEngine.PrivateMemorySize64,110759936);assert.equal(lastEngine.PrivateMemorySize64-firstEngine.PrivateMemorySize64,76017664);
assert.equal(engineRows.length,corrected.engine_memory_windows[0].sample_count);
const result={status:'passed',scope:'Offline recomputation of the frozen2522-row original prefix with frozen reviewed helper copies. No API/service/test workload.',prefix_rows:samples.length,prefix_sha256:sha,first_at:samples[0].at,last_at:samples.at(-1).at,process_identity_baseline:{at:baseline.at,processes:identity},memory:{valid_samples:accepted.length,last:totals.at(-1),observed_max_working_set_bytes:Math.max(...totals.map(r=>r.working_set_bytes)),observed_max_private_bytes:Math.max(...totals.map(r=>r.private_bytes)),changed_membership:changed},engine:{sample_count:engineRows.length,last:lastEngine,max_private_bytes:Math.max(...engineRows.map(r=>r.PrivateMemorySize64)),private_change_bytes:lastEngine.PrivateMemorySize64-firstEngine.PrivateMemorySize64},cpu:{interval_count:cpu.interval_count,latest_interval:cpu.latest_interval,cpu_seconds:cpu.cpu_seconds,covered_interval_seconds:cpu.covered_interval_seconds,mean_percent_total_capacity:cpu.mean_percent_total_capacity,max_interval_percent_total_capacity:cpu.max_interval_percent_total_capacity,accepted_intervals_exactly_equal_original:true,accepted_intervals_exactly_equal_corrected:true},corrected_analysis_comparison:{run_id:'2026-09-21T13-42-39-992Z-observation-analysis-8a1b6dc1',sample_count:corrected.sample_count,cutoff:corrected.last_at,memory_last_and_identity_match:true,cpu_accepted_intervals_match:true},limitations:['No new unit tests were run; existing17/17 output was read.','First-complete PID/name membership is an available historical baseline, not OS start-time proof. Same-name PID reuse cannot be excluded.','Corrected analysis has its own later live cutoff; comparisons above are only the unchanged accepted memory/CPU fields, not all sample totals.']};
fs.writeFileSync(path.join(run,'recomputed.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify({status:result.status,prefix_rows:samples.length,memory_valid:accepted.length,memory_last:totals.at(-1),cpu_intervals:cpu.interval_count,changed},null,2));
