import {test,expect} from '@playwright/test';

const errors=[];
test.beforeEach(async({page})=>{errors.length=0;page.on('pageerror',e=>errors.push(e.message));await page.goto('/?capture=1');await page.waitForFunction(()=>window.__atlas?.state.catalog.length===10);await page.evaluate(()=>document.fonts.ready);});
test.afterEach(()=>expect(errors).toEqual([]));
const lab=async page=>{await page.locator('[data-nav="lab"]').click();await expect(page.locator('#route-panel')).toBeVisible();await page.waitForFunction(()=>__atlas.state.screen==='lab'&&__atlas.state.route);};

test('Google entry, original sources, search, and all 10 distinct plans render',async({page})=>{
 await expect(page.locator('#google-map iframe')).toHaveAttribute('src',/maps.google.com/);await expect(page.locator('.site-card')).toHaveCount(10);
 await page.locator('#search').fill('없는장소');await expect(page.locator('.empty')).toBeVisible();await page.locator('#search').fill('');
 for(const site of await page.evaluate(()=>__atlas.state.catalog.map(s=>({id:s.id,name:s.name})))){await page.locator(`[data-site="${site.id}"]`).first().click();await page.waitForFunction(id=>__atlas.state.plan?.sourceType==='raster'&&__atlas.state.plan.name===__atlas.state.catalog.find(s=>s.id===id).name,site.id);await expect(page.locator('#plan-info h2')).toHaveText(site.name);expect(await page.evaluate(()=>__atlas.state.plan.walls.length)).toBeGreaterThan(0);}
 await page.locator('[data-model="2d"]').click();await expect(page.locator('#flat-image')).toBeVisible();expect(await page.locator('#flat-image').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
 await page.locator('#scale').fill('22');await page.locator('#calibrate').click();expect(await page.evaluate(()=>__atlas.state.plan.width)).toBe(22);await page.locator('[data-model="exterior"]').click();expect(await page.evaluate(()=>__atlas.scene.mode)).toBe('exterior');
});
test('car animation reaches every building and supports first/third person and pause',async({page})=>{
 test.setTimeout(240000);await lab(page);await page.locator('[data-camera="first"]').click();expect(await page.evaluate(()=>__atlas.state.camera)).toBe('first');await page.locator('[data-camera="third"]').click();
 for(const id of ['A','B','C','D']){await page.locator('#restart').click();await page.waitForFunction(()=>__atlas.state.route);await page.locator('#destination').selectOption(id);await page.locator('#speed').selectOption('4');const start=await page.evaluate(()=>({...__atlas.state.pose}));await page.locator('#start').click();await expect.poll(async()=>page.evaluate(()=>__atlas.state.travel)).toBeGreaterThan(2);expect(await page.evaluate(()=>__atlas.state.pose.z)).not.toBe(start.z);await page.locator('#start').click();const frozen=await page.evaluate(()=>__atlas.state.travel);await page.waitForTimeout(180);expect(await page.evaluate(()=>__atlas.state.travel)).toBe(frozen);await page.locator('#start').click();await expect(page.locator('#start')).toContainText('도착', {timeout:60000});expect(await page.evaluate(()=>__atlas.state.pose.arrived)).toBe(true);expect(await page.evaluate(()=>__atlas.state.route.destination.id)).toBe(id);}
});
test('fire reroutes from current position, animates a person, and stops when exits are blocked',async({page})=>{
 await lab(page);await page.locator('#speed').selectOption('4');await page.locator('#start').click();await expect.poll(async()=>page.evaluate(()=>__atlas.state.travel)).toBeGreaterThan(5);await page.locator('#start').click();const p=await page.evaluate(()=>({...__atlas.state.pose}));await page.locator('#fire-toggle').click();expect(await page.evaluate(()=>__atlas.state.mode)).toBe('person');const start=await page.evaluate(()=>__atlas.state.route.points[0]);expect(start.x).toBeCloseTo(p.x);expect(start.z).toBeCloseTo(p.z);
 await page.locator('#fire-location').selectOption('west');expect(await page.evaluate(()=>__atlas.state.route.destination.id)).toBe('exit-east');await page.locator('#speed').selectOption('4');await page.locator('#start').click();await expect.poll(async()=>page.evaluate(()=>__atlas.state.travel)).toBeGreaterThan(2);expect(await page.evaluate(()=>__atlas.scene.person.visible)).toBe(true);await page.locator('#fire-location').selectOption('all');await expect(page.locator('.no-route')).toBeVisible();await expect(page.locator('#start')).toBeDisabled();expect(await page.evaluate(()=>__atlas.state.playing)).toBe(false);
});
test('keyboard motion stays on a lane and audio is opt-in',async({page})=>{
 await lab(page);await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','false');await page.locator('#sound').click();await expect(page.locator('#sound')).toHaveAttribute('aria-pressed','true');await page.keyboard.down('w');await page.waitForTimeout(1000);await page.keyboard.up('w');expect(await page.evaluate(()=>__atlas.state.pose.z)).toBeLessThan(27);expect(await page.evaluate(()=>__atlas.state.playing)).toBe(false);await page.locator('#sound').click();
});
test('golden parking overview, first person, evacuation, library and source analysis',async({page})=>{
 await lab(page);await page.waitForTimeout(800);await expect(page).toHaveScreenshot('parking-overview.png');
 await page.locator('[data-camera="first"]').click();await page.waitForTimeout(400);await expect(page).toHaveScreenshot('parking-first-person.png');
 await page.locator('[data-camera="orbit"]').click();await page.locator('#fire-toggle').click();await page.locator('#notification').evaluate(el=>el.classList.remove('visible'));await page.waitForTimeout(400);await expect(page).toHaveScreenshot('evacuation-overview.png');
 await page.locator('[data-nav="plans"]').click();await expect(page).toHaveScreenshot('plan-library.png');await page.locator('.library-grid button').first().click();await page.waitForFunction(()=>__atlas.state.plan.sourceType==='raster');await page.waitForTimeout(500);await expect(page).toHaveScreenshot('plan-analysis.png');
});
test('mobile layout keeps controls and animation usable; golden mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844});await lab(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.locator('#destination').selectOption('D');await page.locator('#start').click();await expect.poll(async()=>page.evaluate(()=>__atlas.state.travel)).toBeGreaterThan(1);await page.locator('#start').click();await page.locator('#restart').click();await page.waitForFunction(()=>__atlas.state.route);await page.waitForTimeout(500);await expect(page).toHaveScreenshot('parking-mobile.png',{fullPage:true});
});

test('actual parking PDF pages are analyzed from local source bytes',async({page})=>{await page.locator('[data-nav="plans"]').click();await page.locator('#public-parking').click();await expect(page.locator('#pdf-page')).toHaveValue('16');expect(await page.evaluate(()=>__atlas.state.plan.walls.length)).toBeGreaterThan(0);await page.locator('[data-model="2d"]').click();await expect(page.locator('#flat-image')).toHaveAttribute('src',/^data:image\/png/);await page.locator('#pdf-page').selectOption('17');await expect(page.locator('#crumb-title')).toContainText('17쪽');});
test('actual parking annotations drive to all core approaches without fabricating an evacuation exit',async({page})=>{await page.locator('[data-nav="plans"]').click();await page.locator('#source-drive').click();await page.waitForFunction(()=>__atlas.state.plan?.layoutType==='source-traced'&&__atlas.state.route);await expect(page.locator('#destination option')).toHaveCount(3);for(const id of ['A','B','C']){await page.locator('#destination').selectOption(id);expect(await page.evaluate(()=>__atlas.state.route.destination.id)).toBe(id);}await page.locator('#speed').selectOption('4');await page.locator('#start').click();await expect.poll(async()=>page.evaluate(()=>__atlas.state.travel)).toBeGreaterThan(3);await page.locator('#start').click();await page.locator('#fire-toggle').click();await expect(page.locator('#notification')).toContainText('지상 대피 연결이 미확인');expect(await page.evaluate(()=>__atlas.state.mode)).toBe('car');});
