'use client';
import { useEffect, useMemo, useState } from 'react';
import type { ChargeSession } from '@/types/vehicle';
import { DashboardIcon } from './DashboardIcon';
export const sessionType=(type:string)=>type==='AC_SLOW'?'완속':type==='DC_FAST'?'급속':'초급속';
const timestamp=(value:string)=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
export function ChargingHistory({userId}:{userId:string}){
  const [sessions,setSessions]=useState<ChargeSession[]|null>(null),[error,setError]=useState('');
  const [type,setType]=useState('all'),[period,setPeriod]=useState('all'),[page,setPage]=useState(1),[selected,setSelected]=useState<ChargeSession|null>(null);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/users/${encodeURIComponent(userId)}/sessions`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(data=>setSessions(data.sessions)).catch(e=>{if(e.name!=='AbortError')setError(`충전 이력을 불러오지 못했습니다: ${e.message}`);});return()=>controller.abort();},[userId]);
  const filtered=useMemo(()=>{const cutoff=sessions?.[0]?Date.parse(sessions[0].endedAt)-Number(period)*86400000:0;return (sessions??[]).filter(s=>(type==='all'||s.chargerType===type)&&(period==='all'||Date.parse(s.endedAt)>=cutoff));},[sessions,type,period]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/5)),visible=filtered.slice((page-1)*5,page*5);
  const exportCsv=()=>{const fields=['sessionId','userId','vehicleId','startedAt','chargerType','chargedKwh','durationMinutes','idleMinutes'] as const;const csv='\uFEFF'+[fields.join(','),...filtered.map(s=>fields.map(f=>JSON.stringify(s[f])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${userId}-charging-history.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <>
    <section className="history-panel" aria-label="선택 사용자 충전 이력"><header className="panel-heading"><div><span className="section-kicker">CHARGING HISTORY · {userId}</span><h2>충전 이력</h2></div><div className="table-controls"><select aria-label="충전 기간" value={period} onChange={e=>{setPeriod(e.target.value);setPage(1);}}><option value="all">전체 기간</option><option value="7">최근 7일</option><option value="30">최근 30일</option></select><select aria-label="충전 유형" value={type} onChange={e=>{setType(e.target.value);setPage(1);}}><option value="all">전체 충전기</option><option value="AC_SLOW">완속</option><option value="DC_FAST">급속</option><option value="ULTRA_FAST">초급속</option></select><button className="export-button" disabled={!filtered.length} onClick={exportCsv}><DashboardIcon name="download" size={15}/> 내보내기</button></div></header>
      {error?<p role="alert" className="empty-state">{error}</p>:sessions===null?<p role="status" className="empty-state">충전 기록을 불러오는 중입니다…</p>:<><div className="table-scroll"><table><thead><tr><th>날짜</th><th>충전 위치</th><th>유형</th><th>충전 에너지</th><th>충전 시간</th><th>방치 시간</th><th>세션 상태</th><th>상세</th></tr></thead><tbody>{visible.map(s=><tr key={s.sessionId} data-session-id={s.sessionId}><td><strong>{timestamp(s.startedAt)}</strong><small>{s.sessionId}</small></td><td>{s.stationType??'미제공'}</td><td><span className={`charge-type ${s.chargerType==='AC_SLOW'?'slow':'fast'}`}>{sessionType(s.chargerType)}</span></td><td>{s.chargedKwh.toFixed(1)} <small>kWh</small></td><td>{Math.round(s.durationMinutes)} <small>분</small></td><td className={s.idleMinutes>=120?'risk-value':''}>{Math.round(s.idleMinutes)} <small>분</small></td><td><span className={`session-state ${s.isHighSocIdle||s.isDeepDischarge?'caution':''}`}>{s.isHighSocIdle?'고SOC 방치':s.isDeepDischarge?'저SOC':s.isNightSlow?'심야 완속':'일반'}</span></td><td><button className="table-detail" aria-label={`${s.sessionId} 세션 상세`} onClick={()=>setSelected(s)}>분석 ↗</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty-state">선택한 조건에 맞는 충전 기록이 없습니다.</p>}</div><div className="pagination"><div><button aria-label="이전 페이지" disabled={page===1} onClick={()=>setPage(page-1)}>‹</button>{Array.from({length:totalPages},(_,i)=><button key={i} aria-label={`${i+1} 페이지`} aria-current={page===i+1?'page':undefined} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button aria-label="다음 페이지" disabled={page>=totalPages} onClick={()=>setPage(page+1)}>›</button></div><span>총 {filtered.length}건 · {filtered.length?(page-1)*5+1:0}–{Math.min(page*5,filtered.length)} 표시</span></div></>}
      <p className="card-note">기간 필터는 해당 사용자의 마지막 Mock 충전일 기준입니다. 각 행의 ‘분석’에서 원본 값과 파생 계산을 확인하세요.</p>
    </section>
    {selected&&<SessionDetail key={selected.sessionId} session={selected} onClose={()=>setSelected(null)}/>}
  </>;
}
function SessionDetail({session:s,onClose}:{session:ChargeSession;onClose:()=>void}){
  useEffect(()=>{document.getElementById('session-detail')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});},[]);
  const raw=[['session_id',s.sessionId],['user_id',s.userId],['vehicle_id',s.vehicleId],['charger_type',s.chargerType],['started_at',s.startedAt],['ended_at',s.endedAt],['unplugged_at',s.unpluggedAt],['energy_kwh',s.chargedKwh],['cost_krw',s.paymentAmountKrw??'미제공']];
  const features=[['avg_power_kw',s.averagePowerKw.toFixed(2)],['estimated_c_rate',s.estimatedCRate.toFixed(3)],['idle_minutes',s.idleMinutes.toFixed(1)],['is_fast_charge',String(s.isFast)],['is_high_soc_idle',String(s.isHighSocIdle)],['is_deep_discharge',String(s.isDeepDischarge)],['is_night_slow',String(s.isNightSlow)]];
  return <section id="session-detail" className="history-panel session-detail" aria-label="세션 상세 분석"><header className="panel-heading"><div><span className="section-kicker">SESSION ANALYSIS</span><h2>세션 상세 분석</h2></div><span className="session-id">Session ID: {s.sessionId}</span><button className="close-button" aria-label="세션 상세 닫기" onClick={onClose}>×</button></header><div className="session-detail-grid">
    <article className="analysis-card"><h3>1. 원본 거래 데이터 <small>Raw Transaction</small></h3><dl className="code-values">{raw.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></article>
    <article className="analysis-card"><h3>2. 추출된 특징 <small>Extracted Features</small></h3><dl className="code-values">{features.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p className="card-note">평균 전력 = 충전 에너지 ÷ 시간<br/>추정 C-rate = 평균 전력 ÷ 가용 배터리 용량</p></article>
    <article className="analysis-card"><h3>3. 점수 계산 과정 <small>Score Attribution</small></h3><div className="unavailable-analysis"><span>세션 단위 점수 영향</span><strong>Mock 데이터 미제공</strong><p>원본은 사용자 전체 기간의 합산 점수를 산정합니다. 세션별 감점과 스트레스 수치는 임의 생성하지 않습니다.</p></div></article>
    <article className="analysis-card"><h3>4. 충전 기록 시각화</h3><div className="session-timeline"><div className="timeline-labels"><span>충전 {Math.round(s.durationMinutes)}분</span><span>방치 {Math.round(s.idleMinutes)}분</span></div><div className="timeline-bar"><i style={{flexGrow:s.durationMinutes}}/><i style={{flexGrow:s.idleMinutes}}/></div><div className="soc-anchors"><div><span>시작 SOC</span><strong>{s.startSoc===null?'—':`${s.startSoc}%`}</strong></div><span>→</span><div><span>종료 SOC</span><strong>{s.endSoc===null?'—':`${s.endSoc}%`}</strong></div></div><p className="card-note">사용자 입력 SOC만 표시합니다. 연속 SOC 측정값이 없어 시안의 추세선은 생성하지 않습니다.</p></div></article>
  </div></section>;
}
