import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));const evidence=path.dirname(dir);
const originalDir=path.join(evidence,'2026-09-21T13-45-56-887Z-supplementary-resource-analysis-1bb6f8c2');
const testDir=path.join(evidence,'2026-09-21T13-45-29-498Z-supplementary-analysis-validation-db65adb1');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const prefix=fs.readFileSync(path.join(dir,'samples-prefix.jsonl'));
const runBytes=fs.readFileSync(path.join(dir,'source-run.json'));
const capture=JSON.parse(fs.readFileSync(path.join(dir,'capture.json')));
const originalBytes=fs.readFileSync(path.join(originalDir,'analysis.json'));
const result=JSON.parse(originalBytes);const run=JSON.parse(runBytes);
assert.equal(hash(prefix),capture.complete_prefix_sha256);assert.equal(hash(runBytes),capture.source_run_sha256);assert.equal(prefix.at(-1),10);
const samples=prefix.toString('utf8').trimEnd().split('\n').map(JSON.parse);
const key=row=>JSON.stringify([row.Id,row.StartTimeUtc,row.role,row.ProcessName]);
const baseline=new Map(samples[0].resources.map(row=>[key(row),row]));
assert.equal(samples.length,56);assert.equal(baseline.size,14);assert.equal(run.logical_processors,16);
const same=(actual,expected)=>assert.ok(Math.abs(actual-expected)<=1e-10,actual+' != '+expected);
const groups=new Map([...baseline].map(([id,row])=>[id,{Id:row.Id,StartTimeUtc:row.StartTimeUtc,role:row.role,ProcessName:row.ProcessName,cpu_seconds:0,covered_seconds:0,intervals:[],working_set:[],private_memory:[]} ]));
const intervals=[];const totals=[];const parsedTimes=[];
for(let i=0;i<samples.length;i++){
 const sample=samples[i];assert.equal(sample.complete,true);assert.equal(sample.expected_process_count,14);assert.equal(sample.resources.length,14);assert.deepEqual(sample.missing_processes,[]);assert.ok(!sample.collection_error);
 assert.equal(new Set(sample.resources.map(row=>row.Id)).size,14);assert.equal(new Set(sample.resources.map(row=>row.role)).size,14);
 const current=new Map(sample.resources.map(row=>[key(row),row]));assert.deepEqual([...current.keys()].sort(),[...baseline.keys()].sort());
 assert.equal(typeof sample.at,'string');assert.match(sample.at,/(?:Z|\+00:00)$/);const atMs=Date.parse(sample.at),finishMs=Date.parse(sample.collection_finished_at);assert.ok(finishMs>=atMs);assert.ok(finishMs-atMs<=65000);parsedTimes.push(atMs);
 let ws=0,priv=0;for(const [id,row] of current){assert.ok(Number.isSafeInteger(row.WorkingSet64)&&row.WorkingSet64>=0);assert.ok(Number.isSafeInteger(row.PrivateMemorySize64)&&row.PrivateMemorySize64>=0);assert.ok(Number.isFinite(row.CPU)&&row.CPU>=0);ws+=row.WorkingSet64;priv+=row.PrivateMemorySize64;groups.get(id).working_set.push({at:sample.at,bytes:row.WorkingSet64});groups.get(id).private_memory.push({at:sample.at,bytes:row.PrivateMemorySize64});}
 totals.push({at:sample.at,working_set_bytes:ws,private_bytes:priv});
 if(i===0)continue;
 const before=samples[i-1];const previous=new Map(before.resources.map(row=>[key(row),row]));const seconds=(sample.elapsed_ms-before.elapsed_ms)/1000;const wallSeconds=(atMs-parsedTimes[i-1])/1000;assert.ok(seconds>0&&seconds<=65);assert.ok(wallSeconds>0&&wallSeconds<=65);assert.ok(Math.abs(seconds-wallSeconds)<=1);assert.equal(sample.demo_run_id,before.demo_run_id);
 let cpu=0;for(const [id,row] of current){const delta=row.CPU-previous.get(id).CPU;assert.ok(delta>=0&&delta<=seconds*16);const group=groups.get(id);group.cpu_seconds+=delta;group.covered_seconds+=seconds;group.intervals.push({from:before.at,to:sample.at,seconds,cpu_seconds:delta,percent_total_capacity:delta/seconds/16*100});cpu+=delta;}
 assert.ok(cpu<=seconds*16);intervals.push({from:before.at,to:sample.at,seconds,cpu_seconds:cpu,percent_total_capacity:cpu/seconds/16*100});
}
const covered=intervals.reduce((sum,row)=>sum+row.seconds,0);const cpuSeconds=intervals.reduce((sum,row)=>sum+row.cpu_seconds,0);const weighted=intervals.reduce((sum,row)=>sum+row.percent_total_capacity*row.seconds,0)/covered;
same(weighted,cpuSeconds/covered/16*100);assert.equal(intervals.length,55);same(cpuSeconds,result.cpu.full_group.cpu_seconds);same(covered,result.cpu.full_group.covered_interval_seconds);same(weighted,result.cpu.full_group.mean_percent_total_capacity);same(Math.max(...intervals.map(row=>row.percent_total_capacity)),result.cpu.full_group.max_interval_percent_total_capacity);
assert.equal(result.memory.full_groups_by_membership.length,1);const fullMemory=result.memory.full_groups_by_membership[0];assert.equal(fullMemory.membership.length,14);
assert.equal(totals.at(-1).working_set_bytes,fullMemory.working_set_bytes.last.bytes);assert.equal(totals.at(-1).private_bytes,fullMemory.private_bytes.last.bytes);
const perProcess=[...groups].map(([id,group])=>{const sourceCpu=result.cpu.per_process.find(row=>key(row)===id);const sourceMemory=result.memory.per_process.find(row=>key(row)===id);assert.ok(sourceCpu&&sourceMemory);same(group.cpu_seconds,sourceCpu.cpu_seconds);same(group.covered_seconds,sourceCpu.covered_interval_seconds);same(group.cpu_seconds/group.covered_seconds/16*100,sourceCpu.mean_percent_total_capacity);assert.equal(sourceCpu.interval_count,55);assert.equal(sourceMemory.working_set_bytes.sample_count,56);assert.equal(sourceMemory.private_bytes.sample_count,56);assert.equal(group.working_set.at(-1).bytes,sourceMemory.working_set_bytes.last.bytes);assert.equal(group.private_memory.at(-1).bytes,sourceMemory.private_bytes.last.bytes);assert.equal(Math.min(...group.working_set.map(row=>row.bytes)),sourceMemory.working_set_bytes.observed_min_bytes);assert.equal(Math.max(...group.working_set.map(row=>row.bytes)),sourceMemory.working_set_bytes.observed_max_bytes);assert.equal(Math.min(...group.private_memory.map(row=>row.bytes)),sourceMemory.private_bytes.observed_min_bytes);assert.equal(Math.max(...group.private_memory.map(row=>row.bytes)),sourceMemory.private_bytes.observed_max_bytes);return {identity:{Id:group.Id,StartTimeUtc:group.StartTimeUtc,role:group.role,ProcessName:group.ProcessName},cpu_seconds:group.cpu_seconds,covered_seconds:group.covered_seconds,mean_percent_total_capacity:group.cpu_seconds/group.covered_seconds/16*100,last_working_set_bytes:group.working_set.at(-1).bytes,last_private_bytes:group.private_memory.at(-1).bytes};});
same(perProcess.reduce((sum,row)=>sum+row.cpu_seconds,0),cpuSeconds);assert.equal(perProcess.reduce((sum,row)=>sum+row.last_working_set_bytes,0),totals.at(-1).working_set_bytes);assert.equal(perProcess.reduce((sum,row)=>sum+row.last_private_bytes,0),totals.at(-1).private_bytes);
const testRunBytes=fs.readFileSync(path.join(testDir,'test-run.json'));const testRun=JSON.parse(testRunBytes);const testOutput=fs.readFileSync(path.join(testDir,'tests.stdout.log'));assert.equal(testRun.exit_code,0);assert.match(testOutput.toString('utf8'),/pass 13/);assert.match(testOutput.toString('utf8'),/fail 0/);
const sourceHashes=testRun.sources.map(source=>{const bytes=fs.readFileSync(path.join(dir,'source',path.basename(source.path)));const sha=hash(bytes);assert.equal(sha,source.sha256);const actualCapture=capture.analysis_sources.find(item=>item.path===source.path);if(actualCapture)assert.equal(sha,actualCapture.sha256);return {path:source.path,sha256:sha,bytes:bytes.length,matches_tested_source:true,matches_analysis_capture:actualCapture?true:null};});
const report={status:'passed',method:'Independent direct arithmetic over frozen56 raw samples; production analyzer/helper not imported. Existing test output read, no tests or live collection rerun.',source_run_status:run.status,source_reported_completed:result.source_reported_completed,prefix_bytes:prefix.length,prefix_sha256:hash(prefix),source_run_sha256:hash(runBytes),original_analysis_sha256:hash(originalBytes),source_hashes:sourceHashes,existing_tests:{count:13,pass:13,fail:0,exit_code:testRun.exit_code,test_run_sha256:hash(testRunBytes),stdout_sha256:hash(testOutput)},raw_utc:{first_at:samples[0].at,last_at:samples.at(-1).at,unchanged_as_strings:true},samples:samples.length,identity_count:baseline.size,intervals:intervals.length,complete_four_field_membership_identical_at_all_samples:true,cpu:{cpu_seconds:cpuSeconds,covered_seconds:covered,weighted_mean_percent_total_capacity:weighted,independent_sum_delta_percent:cpuSeconds/covered/16*100,max_interval_percent_total_capacity:Math.max(...intervals.map(row=>row.percent_total_capacity)),matches_original:true},memory:{last:totals.at(-1),min_working_set_bytes:Math.min(...totals.map(row=>row.working_set_bytes)),max_working_set_bytes:Math.max(...totals.map(row=>row.working_set_bytes)),min_private_bytes:Math.min(...totals.map(row=>row.private_bytes)),max_private_bytes:Math.max(...totals.map(row=>row.private_bytes)),per_identity_last_sums_match_full_group:true},per_process:perProcess,findings:[],limitations:['No original observer missing counters are reconstructed.','Four-field identity segments observed processes but is not proof of executable ownership.','UTC strings with submillisecond precision are retained verbatim; Date.parse is used only for millisecond wall-clock interval comparison with the recorded tolerance.','CPU describes 16-logical-processor host capacity over this fixed27.59-minute prefix, not instantaneous use or six-hour completion.']};
fs.writeFileSync(path.join(dir,'review.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(dir,'independent-intervals.json'),JSON.stringify(intervals,null,2));fs.writeFileSync(path.join(dir,'independent-memory-totals.json'),JSON.stringify(totals,null,2));
console.log(JSON.stringify({status:report.status,prefix_sha256:report.prefix_sha256,samples:report.samples,identity_count:report.identity_count,intervals:report.intervals,raw_utc:report.raw_utc,cpu:report.cpu,memory_last:report.memory.last,source_hashes:sourceHashes,actionable_findings:0},null,2));
