import { test, expect } from '@playwright/test';

test('3D dashboard renders, supports interaction, and has no browser errors', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/health/');
  await expect(page.getByRole('heading', { name: '오늘의 나를, 더 건강하게.' })).toBeVisible();
  await expect(page.locator('.body-canvas')).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('canvas')).toBeVisible();
  await page.getByRole('button', { name: '인체 확대' }).click();
  await page.getByRole('button', { name: '인체 정면으로 초기화' }).click();
  await page.getByRole('button', { name: '자동 회전 시작' }).click();
  await page.getByRole('button', { name: '자동 회전 정지' }).click();
  await page.getByRole('button', { name: '장기 단계', exact: true }).click();
  await page.getByRole('button', { name: '피부 단계', exact: true }).click();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/desktop-dashboard.png', fullPage: true });
  await page.getByRole('button', { name: /간 수치 48 U\/L/ }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('설정한 간 효소 상한보다 높아요');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  expect(errors).toEqual([]);
});

test('personal record is saved, survives reload and remains separate from demo data', async ({ page }) => {
  await page.goto('/health/');
  await page.getByRole('button', { name: '건강 기록하기', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('button', { name: '건강 기록 저장' }).click();
  await expect(dialog.getByRole('alert')).toContainText('하나 이상');
  await dialog.getByLabel('수축기 혈압', { exact: true }).fill('185');
  await dialog.getByLabel('이완기 혈압', { exact: true }).fill('95');
  await dialog.getByLabel('LDL 콜레스테롤', { exact: true }).fill('98');
  await dialog.getByLabel('공복 혈당', { exact: true }).fill('94');
  await dialog.getByLabel('요산', { exact: true }).fill('7.8');
  await dialog.getByLabel('간 수치 ALT', { exact: true }).fill('27');
  await dialog.getByLabel('간 수치 AST', { exact: true }).fill('25');
  await dialog.getByRole('button', { name: '건강 기록 저장' }).click();
  await expect(page.getByText('MY DATA', { exact: true })).toBeVisible();
  await expect(page.locator('.urgent-strip')).toContainText('119');
  await expect(page.getByRole('button', { name: /혈압 185\/95 mmHg 즉시 확인 상세 보기/ })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: /혈압 185\/95/ })).toBeVisible();
  await page.getByRole('button', { name: '건강 기록', exact: true }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.getByRole('button', { name: '수정', exact: true }).click();
  await page.getByRole('dialog').getByLabel('수축기 혈압', { exact: true }).fill('118');
  await page.getByRole('dialog').getByLabel('이완기 혈압', { exact: true }).fill('76');
  await page.getByRole('button', { name: '변경 내용 저장' }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody')).toContainText('118/76');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '내보내기', exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/^vitalis-\d{4}-\d{2}-\d{2}\.csv$/);
  await page.getByRole('button', { name: '설정 및 참고범위' }).click();
  await page.getByRole('button', { name: '예시 데이터 보기', exact: true }).click();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(page.locator('tbody tr')).toHaveCount(30);
  await page.getByRole('button', { name: '설정 및 참고범위' }).click();
  await page.getByRole('button', { name: '내 기록 보기', exact: true }).click();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
});

test('guides, habits, historical dates and report filters work', async ({ page }) => {
  await page.goto('/health/');
  await page.getByRole('button', { name: '이전 주' }).click();
  const date = page.locator('.day-button').first();
  await date.click();
  await expect(date).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '오늘로' }).click();
  await page.getByRole('button', { name: '건강 가이드', exact: true }).click();
  await page.getByRole('button', { name: '운동', exact: true }).click();
  await expect(page.locator('.guide-library-item')).toHaveCount(1);
  await page.locator('.guide-library .guide-card').click();
  await expect(page.getByRole('dialog')).toContainText('14분');
  await page.getByRole('button', { name: '오늘 실천했어요', exact: true }).click();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(page.locator('.habit-check')).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '변화 리포트', exact: true }).click();
  await expect(page.locator('.calendar-heatmap button')).toHaveCount(30);
  await page.getByRole('button', { name: '30일', exact: true }).click();
  await page.getByRole('button', { name: '콜레스테롤', exact: true }).click();
  await expect(page.getByRole('img', { name: /최근 30일 LDL 콜레스테롤 변화/ })).toBeVisible();
});

test('mobile layout stays within viewport and navigation and records are usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/health/');
  await expect(page.locator('.body-canvas')).toHaveAttribute('data-ready', 'true');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile-dashboard.png', fullPage: true });
  await page.getByRole('button',{name:'신장 구조 보기',exact:true}).click();
  await page.getByRole('button',{name:'세포 단계',exact:true}).click();
  await expect(page.locator('.body-canvas')).toHaveAttribute('data-layer','cells');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('region',{name:'나와 정상 참고 인체 비교'}).screenshot({path:'test-results/mobile-cells.png'});
  await page.getByRole('button', { name: '메뉴 열기' }).click();
  await page.getByRole('button', { name: '건강 기록', exact: true }).click();
  await expect(page.getByRole('heading', { name: '건강 기록 모아보기' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: '건강 기록하기', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile-record-form.png', fullPage: true });
  await page.getByLabel('공복 혈당', { exact: true }).fill('97');
  await page.getByRole('button', { name: '건강 기록 저장' }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
});

test('lab reference changes reclassify personal readings and liver charts keep ALT and AST separate', async ({ page }) => {
  await page.goto('/health/');
  await page.getByRole('button', { name: '건강 기록하기', exact: true }).click();
  await page.getByLabel('요산', { exact: true }).fill('6.8');
  await page.getByLabel('간 수치 AST', { exact: true }).fill('45');
  await page.getByRole('button', { name: '건강 기록 저장' }).click();
  await expect(page.getByRole('button', { name: /요산 6.8 mg\/dL 범위 내/ })).toBeVisible();
  await page.getByRole('button', { name: /간 수치 45 U\/L 관심/ }).click();
  await expect(page.getByRole('img', { name: /ALT와 AST 별도 표시/ })).toBeVisible();
  await expect(page.getByRole('dialog').locator('g[aria-label*="AST 45 U/L"]')).toHaveCount(1);
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '설정 및 참고범위' }).click();
  await page.getByLabel('요산 상한', { exact: true }).fill('6.0');
  await page.getByLabel('AST 상한', { exact: true }).fill('50');
  await page.getByRole('button', { name: '설정 저장', exact: true }).click();
  await expect(page.getByRole('button', { name: /요산 6.8 mg\/dL 높음/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /간 수치 45 U\/L 범위 내/ })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: /간 수치 45 U\/L 범위 내/ })).toBeVisible();
});

test('failed browser persistence is shown in the open record form without claiming a save', async ({ page }) => {
  await page.addInitScript(() => {
    Storage.prototype.setItem = () => { throw new DOMException('Storage quota exceeded', 'QuotaExceededError'); };
  });
  await page.goto('/health/');
  await page.getByRole('button', { name: '건강 기록하기', exact: true }).click();
  await page.getByLabel('공복 혈당', { exact: true }).fill('95');
  await page.getByRole('button', { name: '건강 기록 저장' }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('저장하지 못했어요');
  await expect(page.getByText('DEMO', { exact: true })).toBeVisible();
});

test('anatomical comparison explores skin, a kidney section, skeleton and cells with shared controls', async ({ page }) => {
  const errors: string[]=[]; page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/health/');
  const atlas=page.getByRole('region',{name:'나와 정상 참고 인체 비교'});
  const canvas=atlas.locator('.body-canvas');
  await expect(canvas).toHaveAttribute('data-ready','true');
  await expect(canvas).toHaveAttribute('data-layer','skin');
  await expect(atlas.getByText('나의 기록',{exact:true})).toBeVisible();
  await expect(atlas.getByText('정상 참고 모델',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'신장 구조 보기'}).click();
  await expect(canvas).toHaveAttribute('data-layer','organs');
  await expect(canvas).toHaveAttribute('data-focus','uricAcid');
  await expect(atlas.getByText('신장 피질',{exact:true})).toBeVisible();
  await page.waitForTimeout(650);
  await atlas.screenshot({path:'test-results/kidney-comparison.png'});
  await page.getByRole('button',{name:'뼈 단계',exact:true}).click();
  await expect(canvas).toHaveAttribute('data-layer','skeleton');
  await expect(atlas).toContainText('골밀도나 뼈 손상을 판단하지');
  await page.waitForTimeout(650);
  await atlas.screenshot({path:'test-results/skeleton-comparison.png'});
  await page.getByRole('button',{name:'세포 단계',exact:true}).click();
  await expect(canvas).toHaveAttribute('data-layer','cells');
  await expect(atlas.getByText('미토콘드리아',{exact:true})).toBeVisible();
  await page.waitForTimeout(650);
  await atlas.screenshot({path:'test-results/cell-comparison.png'});
  await page.getByRole('button',{name:'비교 중',exact:true}).click();
  await expect(canvas).toHaveAttribute('data-comparison','false');
  await expect(atlas.getByText('정상 참고 모델',{exact:true})).toHaveCount(0);
  await page.getByRole('slider',{name:'인체 탐색 깊이'}).fill('0');
  await expect(canvas).toHaveAttribute('data-layer','skin');
  expect(errors).toEqual([]);
});

test('heart and flow motion can be paused and restarted, and blood cells have no nuclei', async ({ page }) => {
  await page.goto('/health/');
  await page.getByRole('button',{name:'심장 구조 보기'}).click();
  const atlas=page.getByRole('region',{name:'나와 정상 참고 인체 비교'});
  await expect(atlas.locator('.body-canvas')).toHaveAttribute('data-focus','bloodPressure');
  const canvas=atlas.locator('canvas');
  await expect(canvas).toHaveAttribute('data-animation-time',/\d+\.\d+/);
  const first=await canvas.getAttribute('data-animation-time');
  await expect.poll(()=>canvas.getAttribute('data-animation-time')).not.toBe(first);
  await page.getByRole('button',{name:'생리 애니메이션 일시정지'}).click();
  await page.waitForTimeout(100);
  const paused=await canvas.getAttribute('data-animation-time');
  await page.waitForTimeout(350);
  expect(await canvas.getAttribute('data-animation-time')).toBe(paused);
  await atlas.screenshot({path:'test-results/heart-comparison.png'});
  await page.getByRole('button',{name:'생리 애니메이션 재생'}).click();
  await expect.poll(()=>canvas.getAttribute('data-animation-time')).not.toBe(paused);
  await page.getByRole('button',{name:'혈류 표시',exact:true}).click();
  await expect(page.getByRole('button',{name:'혈류 표시',exact:true})).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button',{name:'세포 단계',exact:true}).click();
  await expect(atlas.getByText('핵이 없는 성숙 세포',{exact:true})).toBeVisible();
  await expect(atlas.getByText('미토콘드리아',{exact:true})).toHaveCount(0);
});

test('extended lab results and recorded pulse survive reload and appear in the clinical panel', async ({ page }) => {
  await page.goto('/health/');
  await page.getByRole('button',{name:'건강 기록하기',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('안정 시 맥박',{exact:true}).fill('84');
  await dialog.getByLabel('간 수치 ALT',{exact:true}).fill('75');
  await dialog.locator('summary').click();
  await dialog.getByLabel('당화혈색소 HbA1c',{exact:true}).fill('6.1');
  await dialog.getByLabel('총콜레스테롤',{exact:true}).fill('210');
  await dialog.getByLabel('HDL 콜레스테롤',{exact:true}).fill('50');
  await dialog.getByLabel('중성지방 TG',{exact:true}).fill('150');
  await dialog.getByLabel('크레아티닌',{exact:true}).fill('1.05');
  await dialog.getByLabel('추정 사구체여과율 eGFR',{exact:true}).fill('87');
  await dialog.getByRole('button',{name:'건강 기록 저장'}).click();
  await expect(page.locator('.pulse-reading')).toContainText('84');
  await expect(page.locator('.clinical-table-row.flagged')).toContainText('75');
  await expect(page.locator('.liver-multiples')).toContainText('1.88');
  await expect(page.locator('.additional-labs')).toContainText('6.1');
  await page.reload();
  await expect(page.locator('.pulse-reading')).toContainText('84');
  await expect(page.locator('.additional-labs')).toContainText('1.05');
  await page.getByRole('button',{name:'검사 조건',exact:true}).click();
  await expect(page.locator('.clinical-explanation-text')).toContainText('복용약');
});
