import { ArrowRight, ChevronRight, Crown, Gamepad2, Sparkles, Star, Swords, Trophy } from 'lucide-react';
import { type Dispatch } from 'react';
import Challenge from './Challenge';
import { playTone } from './audio';
import { IDOLS, level, SKILLS, SKILL_LABEL, TILES, type Action, type GameState, type Player } from './engine';
import { Avatar, Modal, skillIcons } from './ui';
function Thinking({ player, label }: { player: Player; label: string }) { return <div className="thinking"><Avatar player={player} size="large" /><span className="eyebrow">AI PLAYER</span><h2>{player.name}의 {label}</h2><p>무대 위에서 실력을 보여주고 있어요.</p><div className="thinking-dots"><i /><i /><i /></div></div>; }
export default function GameEvents({ state, dispatch, sound, onNew }: { state: GameState; dispatch: Dispatch<Action>; sound: boolean; onNew: () => void }) {
  const active = state.players[state.active]; const tile = TILES[active.position];
  const battlePlayer = state.battle ? state.battle.attack === null ? active : state.players[state.battle.opponent] : active;
  if (state.phase === 'training') return <Modal title={`${tile.name} 트레이닝`}><div className="event-label"><span style={{ background: tile.color }} />{tile.name} ENTERTAINMENT <ChevronRight size={13} /> {tile.subtitle}</div>{active.cpu ? <Thinking player={active} label="트레이닝" /> : <Challenge key={`${state.turn}-training`} name={active.name} skill={tile.skill!} sound={sound} onComplete={score => dispatch({ type: 'TRAIN', performance: score })} />}</Modal>;
  if (state.phase === 'battle' && state.battle) return <Modal title="1 대 1 배틀"><div className="event-label"><Swords size={15} /> SAME SPACE. NEW RIVAL.</div>{!state.battle.skill ? <div className="battle-intro"><span className="eyebrow">HEAD TO HEAD</span><h2>피할 수 없는, 무대 위의 만남.</h2><div className="versus"><div><Avatar player={active} size="large" /><b>{active.name}</b><small>도전자</small></div><span>VS</span><div><Avatar player={state.players[state.battle.opponent]} size="large" /><b>{state.players[state.battle.opponent].name}</b><small>라이벌</small></div></div><p>{active.name}님, 자신 있는 배틀을 선택하세요.</p><div className="battle-choices">{SKILLS.map(skill => { const Icon = skillIcons[skill]; return <button key={skill} disabled={active.cpu} onClick={() => dispatch({ type: 'CHOOSE', skill })}><Icon size={23} /><b>{SKILL_LABEL[skill]} 배틀</b><small>{active.stats[skill]} vs {state.players[state.battle!.opponent].stats[skill]}</small></button>; })}</div><span className="battle-note">능력치 55% + 퍼포먼스 45% · 승리 보상 45P</span>{active.cpu && <p>AI가 장르를 선택하고 있어요…</p>}</div> : battlePlayer.cpu ? <Thinking player={battlePlayer} label={`${SKILL_LABEL[state.battle.skill]} 배틀`} /> : <><div className="handoff"><Avatar player={battlePlayer} /><div><b>{battlePlayer.name}의 차례입니다</b><small>{state.battle.attack === null ? '첫 번째' : '두 번째'} 퍼포먼스 · 기기를 넘겨주세요</small></div></div><Challenge key={`${state.turn}-${state.battle.opponent}-${battlePlayer.id}`} name={battlePlayer.name} skill={state.battle.skill} sound={sound} onComplete={score => dispatch({ type: 'PERFORM', performance: score })} /></>}</Modal>;
  if (state.phase === 'result' && state.result) return <Modal title="턴 결과"><div className="result-modal"><div className={`result-symbol ${state.result.kind}`}><span>{state.result.kind === 'battle' ? <Trophy size={38} /> : <Sparkles size={38} />}</span><i>✦</i><i>✧</i><i>✦</i></div><span className="eyebrow">{state.result.kind === 'battle' ? 'BATTLE COMPLETE' : state.result.kind === 'training' ? 'A LITTLE BETTER EVERY DAY' : 'A LITTLE SURPRISE FOR YOU'}</span><h2>{state.result.title}</h2><p>{state.result.description}</p><div className="reward-row"><span><Star size={20} /><b>+{state.result.points}<small>P</small></b><small>{state.players[state.result.player].name}의 점수</small></span>{state.result.skill && <span><Sparkles size={20} /><b>+{state.result.gain}</b><small>{SKILL_LABEL[state.result.skill]} 능력치</small></span>}{state.result.performance !== undefined && <span><Gamepad2 size={20} /><b>{state.result.performance}<small>%</small></b><small>퍼포먼스</small></span>}</div><button className="primary wide" onClick={() => { dispatch({ type: 'CONTINUE' }); playTone(660,sound,.13); }}>{state.players.some(p => p.lineup && p.score >= state.target) ? '데뷔 무대로!' : state.rivals.length ? '라이벌과 배틀하기' : '다음 턴으로'}<ArrowRight size={18} /></button>{active.cpu && <small className="auto-hint">잠시 후 자동으로 진행됩니다</small>}</div></Modal>;
  if (state.phase === 'evaluation') return <Modal title="월말 평가" wide><div className="evaluation-heading"><span className="award-icon"><Crown size={36} /></span><span className="eyebrow">MONTH {String(state.month).padStart(2,'0')} · THE EVALUATION</span><h2>당신의 노력이, 빛나는 순간.</h2><p>이번 달의 성장 기록과 데뷔조 선발 결과를 공개합니다.</p></div><div className="evaluation-list">{state.evaluation.map(entry => { const player = state.players[entry.player]; return <div key={player.id}><span className="eval-rank">{entry.rank === 1 ? <Crown size={22} /> : String(entry.rank).padStart(2,'0')}</span><Avatar player={player} /><span className="eval-name"><b>{player.name}</b><small>{entry.selected ? '★ 데뷔조 멤버' : '다음 달에도 도전해요'}</small></span><span className="eval-score"><b>{entry.score}P</b><small>평가 보너스 +{entry.bonus}P</small></span></div>; })}</div><p className="evaluation-rule">목표 점수의 25% 이상 + 상위 절반이면 데뷔조에 선발돼요.<br />데뷔조 자격을 얻고 {state.target}P를 모으면 데뷔!</p><button className="primary wide" onClick={() => dispatch({ type: 'NEXT_MONTH' })}>{state.players.some(p => p.lineup && p.score >= state.target) ? '데뷔 결과 확인' : '다음 달을 향해'} <ArrowRight size={18} /></button></Modal>;
  if (state.phase === 'finished') return <Modal title="데뷔 성공" wide><div className="debut-celebration"><div className="confetti">{Array.from({ length: 28 },(_,i) => <i key={i} style={{ left: `${i*3.7}%`, animationDelay: `${i*.13}s`, background: IDOLS[i%4].color }} />)}</div><span className="eyebrow">THE WORLD IS YOUR STAGE</span><h2>HELLO,<br /><span>SUPERSTAR.</span></h2><div className="debut-winners">{state.winners.map(id => <div key={id}><Avatar player={state.players[id]} size="hero" /><h3>{state.players[id].name}</h3><p>{state.players[id].score}P · Lv.{level(state.players[id])}</p></div>)}</div><p className="debut-message">연습실에서 시작된 꿈이 드디어 무대가 되었어요.<br />{state.month}개월의 여정, 당신의 데뷔를 축하합니다!</p><button className="primary wide" onClick={onNew}><Sparkles size={18} /> 새로운 데뷔 스토리 만들기 <ArrowRight size={18} /></button></div></Modal>;
  return null;
}
