import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {validateSurvey,signalAt,signalColor,cableRoute,recommendCharging} from '../../src/core/charging.js';
const fixture=()=>JSON.parse(readFileSync(new URL('../../public/infrastructure/demo-survey.json',import.meta.url),'utf8'));
it('validates provenance and rejects a survey for a different floor',()=>{const d=fixture();expect(validateSurvey(d,'parking-lab')).toBe(d);expect(()=>validateSurvey(d,'another-floor')).toThrow();for(const bad of [null,{...d,version:2},{...d,source:'unknown'},{...d,sourceName:''},{...d,nodes:null},{...d,signals:Array(2001)}])expect(()=>validateSurvey(bad,'parking-lab')).toThrow();});
it('rejects malformed infrastructure instead of recommending a false connection',()=>{const base=fixture();for(const changes of [{nodes:[{id:'x',x:NaN,z:0}]},{nodes:[...base.nodes,base.nodes[0]]},{cables:[{from:'missing',to:'a'}]},{cables:[{from:'a',to:'a'}]},{powerSources:[{...base.powerSources[0],availableKw:-2}]},{powerSources:[{...base.powerSources[0],kind:'unknown'}]},{powerSources:[...base.powerSources,base.powerSources[0]]},{candidates:[{...base.candidates[0],x:Infinity}]},{candidates:[...base.candidates,base.candidates[0]]},{signals:[{...base.signals[0],dbm:-150}]},{signals:[{...base.signals[0],metric:'RSSI'}]},{signals:[{...base.signals[0],operator:''}]},{signals:[{...base.signals[0],observedAt:''}]}])expect(()=>validateSurvey({...base,...changes},'parking-lab')).toThrow();});
it('interpolates local measured RSRP and leaves distant points unknown',()=>{const d=fixture();expect(signalAt(d.signals[0],d.signals)).toMatchObject({dbm:-78,kind:'measured'});const v=signalAt({x:-15,z:-18},d.signals);expect(v.dbm).toBeCloseTo(-84.5);expect(v.kind).toBe('interpolated');expect(signalAt({x:500,z:500},d.signals)).toBeNull();expect(signalAt(d.signals[0],d.signals,{operator:'different'})).toBeNull();expect(signalAt(d.signals[0],d.signals,{operator:'예시 LTE'}).dbm).toBe(-78);});
it('maps weak to red, strong to green, midpoint to amber, and unknown to gray',()=>{expect(signalColor(-130)).toBe('#d84d46');expect(signalColor(-70)).toBe('#28a46f');expect(signalColor(-97.5)).toBe('#e2b747');expect(signalColor(null)).toBe('#a7afb7');});
it('uses connected cable trays and does not invent a straight-line wire through an unknown area',()=>{const d=fixture();expect(cableRoute(d,'panel-a','d').distance).toBe(61);expect(cableRoute(d,'d','panel-a').distance).toBe(61);expect(cableRoute(d,'a','a').distance).toBe(0);expect(cableRoute(d,'panel-a','panel-b')).toBeNull();expect(cableRoute(d,'missing','a')).toBeNull();d.cables[1].blocked=true;expect(cableRoute(d,'panel-a','d')).toBeNull();});
it('ranks feasible candidates and respects shared circuit capacity for simultaneous chargers',()=>{const d=fixture(),r=recommendCharging(d,{powerKw:7,count:8});expect(r.selected.length).toBe(6);expect(r.capacityUsedKw).toBe(42);expect(r.remaining['DB-A']).toBe(0);expect(r.remaining['DB-B']).toBe(0);expect(r.ranked[0].id).toBe('EV-01');expect(r.selected.every(c=>c.source.kind==='panel'&&c.id!=='EV-08')).toBe(true);expect(r.ranked.some(c=>c.reasons.includes('동시 설치 시 회로 여유 용량 부족'))).toBe(true);expect(recommendCharging(d,{powerKw:50}).selected).toEqual([]);});
it('never treats a regular outlet, missing power, missing signal or blocked space as ready',()=>{const d=fixture();d.candidates[0].clearanceVerified=false;d.signals=[];const r=recommendCharging(d);expect(r.selected).toEqual([]);expect(r.ranked.every(c=>c.score===null)).toBe(true);expect(r.ranked.some(c=>c.status==='survey-needed')).toBe(true);d.powerSources=d.powerSources.filter(p=>p.kind==='outlet');expect(recommendCharging(d).ranked.every(c=>c.status==='excluded')).toBe(true);});
it('handles empty surveys, defaults and invalid charger requests',()=>{const d=fixture();expect(recommendCharging(d).selected.length).toBe(3);expect(recommendCharging({...d,candidates:[]}).selected).toEqual([]);delete d.candidates[0].accessScore;expect(recommendCharging(d).ranked.find(c=>c.id==='EV-01').scores.access).toBe(.5);for(const options of [{powerKw:0},{powerKw:NaN},{count:0},{count:21},{count:1.5}])expect(()=>recommendCharging(d,options)).toThrow();});

it('does not combine measurements from competing operators or treat string flags as verified',()=>{const d=fixture();d.signals.push({...d.signals[0],operator:'다른 통신사',dbm:-125});expect(signalAt(d.signals[0],d.signals).dbm).toBe(-78);expect(signalAt(d.signals[0],d.signals,{operator:'다른 통신사'}).dbm).toBe(-125);for(const p of d.powerSources)p.verified='false';expect(recommendCharging(d).selected).toEqual([]);});
it('recalculates cable scores after capacity forces a different supply route',()=>{
 const d={source:'demo',nodes:[{id:'a',x:0,z:0},{id:'b',x:100,z:0},{id:'c',x:10,z:0}],cables:[{from:'a',to:'c'},{from:'b',to:'c'}],powerSources:[{id:'A',nodeId:'a',verified:true,dedicated:true,availableKw:7},{id:'B',nodeId:'b',verified:true,dedicated:true,availableKw:7}],candidates:[{id:'1',nodeId:'a',x:0,z:0,clearanceVerified:true},{id:'2',nodeId:'c',x:10,z:0,clearanceVerified:true}],signals:[{x:0,z:0,dbm:-80,operator:'LTE'}]};
 const r=recommendCharging(d,{count:2});expect(r.selected[1].source.id).toBe('B');expect(r.selected[1].cable.distance).toBe(90);expect(r.selected[1].scores.cable).toBeCloseTo(.1);expect(r.selected[1].score).toBe(47);
});
