import {describe,it,expect,beforeEach,afterEach} from 'vitest';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {inferTheme,normalizeManifest,safeName,discoverAttractions,resolveAsset,gitState} from '../../lib/registry.mjs';
let root;
beforeEach(async()=>{root=await mkdtemp(path.join(os.tmpdir(),'wonder-registry-'));});
afterEach(async()=>{await rm(root,{recursive:true,force:true});});
async function project(name,files={'README.md':'A project'}){await mkdir(path.join(root,name),{recursive:true});for(const [file,value]of Object.entries(files))await writeFile(path.join(root,name,file),typeof value==='string'?value:JSON.stringify(value));}
describe('project discovery and theme selection',()=>{
 it.each([['racing challenge','bumper'],['영화 제작','theater'],['음성 command','music'],['우주 rocket','space'],['marine sea','ocean'],['flower garden','garden'],['science lab','laboratory'],['arcade game','arcade'],['book club','fantasy']])('classifies %s as %s',(text,theme)=>expect(inferTheme(text)).toBe(theme));
 it('keeps the requested fixed attraction concepts even when README keywords differ',()=>{expect(normalizeManifest('dopamin',{},'music')).toMatchObject({theme:'bumper',character:'mickey'});expect(normalizeManifest('movie')).toMatchObject({theme:'theater',character:'minnie'});expect(normalizeManifest('voice')).toMatchObject({theme:'music',character:'donald'});});
 it.each(['daisy','goofy','pluto','pooh','stitch','baymax'])('accepts the new %s character in an attraction manifest',character=>{expect(normalizeManifest('new',{character}).character).toBe(character);});
 it('accepts a manifest theme change, custom character, color and relative GLB',()=>{expect(normalizeManifest('new-park',{theme:'ocean',character:'olaf',color:'#12aBcF',model:'assets/castle.glb',name:'  Sea room  ',english:'OCEAN',description:'Coral',url:'https://example.com/ride'})).toMatchObject({name:'Sea room',theme:'ocean',character:'olaf',color:'#12aBcF',model:'/api/project-asset/new-park/assets/castle.glb',url:'https://example.com/ride'});});
 it('does not trust malformed manifest values or executable URLs',()=>{const item=normalizeManifest('new',{theme:'<script>',character:'x',color:'red;}',model:'../../secrets.glb',url:'javascript:alert(1)',name:'',description:42});expect(item.theme).toBe('fantasy');expect(item.model).toBeUndefined();expect(item.url).toBeUndefined();expect(normalizeManifest('new',{url:':::bad'}).url).toBeUndefined();expect(normalizeManifest('new',{url:'file:///etc/passwd'}).url).toBeUndefined();});
 it('limits user supplied display strings',()=>{expect(normalizeManifest('x',{name:'x'.repeat(1000),description:'y'.repeat(1000)}).name).toHaveLength(80);expect(normalizeManifest('x',{description:'y'.repeat(1000)}).description).toHaveLength(260);});
 it.each([null,[],false,12])('treats invalid manifest object %j as defaults',value=>expect(normalizeManifest('x',value).theme).toBe('fantasy'));
 it('supports construction status, themed cranes and custom entry actions',()=>{expect(normalizeManifest('map',{theme:'construction',status:'construction',action:'연구소 미리보기'})).toMatchObject({theme:'construction',status:'construction',action:'연구소 미리보기'});expect(inferTheme('a construction site')).toBe('construction');expect(inferTheme('핀볼')).toBe('pinball');expect(normalizeManifest('pinball').theme).toBe('pinball');});
 it.each(['../x','.hidden','x/y','foo..bar','x\\y',''])('rejects unsafe project name %s',value=>expect(safeName(value)).toBe(false));
 it('allows real Korean project names',()=>expect(safeName('우주-여행_01')).toBe(true));
 it('excludes webpage and infrastructure and discovers a new project without changing code',async()=>{for(const id of ['webpage','park','node_modules','.hidden','voice','movie','dopamin','new-space'])await project(id,{'README.md':id==='new-space'?'우주 로켓':'project'});await mkdir(path.join(root,'empty'));const list=await discoverAttractions(root);expect(list.map(a=>a.id)).toEqual(['dopamin','movie','voice','new-space']);expect(list[3].theme).toBe('space');expect(list[1].canLaunch).toBe(true);expect(list[2].canLaunch).toBe(false);});
 it('rebuilds the catalog revision and 3D template after a theme change',async()=>{await project('new',{'package.json':{description:'A flower garden',devDependencies:{vite:'7'}},'attraction.json':{theme:'garden'}});const [before]=await discoverAttractions(root);expect(before.hasWebApp).toBe(true);await writeFile(path.join(root,'new/attraction.json'),JSON.stringify({theme:'space',character:'olaf'}));const [after]=await discoverAttractions(root);expect(after.theme).toBe('space');expect(after.revision).not.toBe(before.revision);});
 it('reports invalid JSON without removing or breaking the attraction',async()=>{await project('broken',{'package.json':'{broken','attraction.json':'{bad'});const [a]=await discoverAttractions(root);expect(a.status).toBe('attention');expect(a.warning).toContain('package.json');await writeFile(path.join(root,'broken/package.json'),'{}');expect((await discoverAttractions(root))[0].warning).toContain('attraction.json');});
 it('sorts extra projects deterministically and reads optional manifest-only folders',async()=>{await project('zebra',{'attraction.json':{}});await project('apple',{'package.json':{dependencies:{vite:'7'}}});expect((await discoverAttractions(root)).map(a=>a.id)).toEqual(['apple','zebra']);});
 it('launches static web apps without needing a package manager',async()=>{await project('static',{'README.md':'A static app','index.html':'<html>App</html>'});expect((await discoverAttractions(root))[0]).toMatchObject({hasStaticApp:true,hasWebApp:false,canLaunch:true});});
 it('handles valid JSON that is not a package object',async()=>{await project('bad',{'package.json':'null'});expect((await discoverAttractions(root))[0].status).toBe('attention');});
});
describe('asset confinement',()=>{
 it('resolves allowed project assets within their project',()=>expect(resolveAsset(root,'movie','output/film.mp4')).toBe(path.join(root,'movie/output/film.mp4')));
 it.each([['movie','../../.ssh/id_rsa'],['webpage','asset.png'],['movie','.env'],['movie','assets/key.pem'],['movie','assets/key.key'],['../movie','file.mp4'],['movie','assets/../.env'],['movie','/private/tmp/secret.mp4']])('rejects %s / %s',(id,relative)=>expect(resolveAsset(root,id,relative)).toBeNull());
});
describe('repository state',()=>{
 it('handles a folder with no Git repository',async()=>expect(await gitState(root)).toEqual({head:null,branch:null,dirty:false,commits:[]}));
 it('reports actual clean and dirty worktrees and commit metadata',async()=>{const git=(...args)=>execFileSync('git',args,{cwd:root,stdio:'pipe'});git('init','-b','main');git('config','user.name','Park test');git('config','user.email','park@example.test');await writeFile(path.join(root,'README.md'),'fixture');git('add','README.md');git('commit','-m','Test fixture');const state=await gitState(root);expect(state.branch).toBe('main');expect(state.dirty).toBe(false);expect(state.commits[0].subject).toBe('Test fixture');await writeFile(path.join(root,'README.md'),'changed');expect((await gitState(root)).dirty).toBe(true);});
});
