import {it,expect,beforeEach,afterEach,vi} from 'vitest';
import {mkdtemp,mkdir,writeFile,rm,readFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {synchronize,readState,INTERVAL_MS} from '../../lib/sync.mjs';
let root;
beforeEach(async()=>{root=await mkdtemp(path.join(os.tmpdir(),'wonder-sync-'));await mkdir(path.join(root,'space'));await writeFile(path.join(root,'space/README.md'),'A rocket launch');});
afterEach(async()=>rm(root,{recursive:true,force:true}));
function runner({ahead=0,behind=0,dirty='',fail=false}={}){return vi.fn(async(cmd,args)=>{if(fail&&args[0]==='fetch')throw Object.assign(new Error('network failed'),{stderr:'https://token-secret@github.com denied'});return {stdout:args[0]==='rev-list'?`${ahead}\t${behind}\n`:args[0]==='status'?dirty:''};});}
it('uses an exact ten-minute interval and persists a readable atomic snapshot',async()=>{const now=new Date('2026-09-21T00:00:00Z');const state=await synchronize(root,{now,fetchRemote:false});expect(INTERVAL_MS).toBe(600000);expect(state.nextCheckAt).toBe('2026-09-21T00:10:00.000Z');expect(state.remote).toBe('local');expect(await readState(root)).toEqual(state);expect(state.events[0]).toMatchObject({id:'space',type:'added'});});
it('avoids duplicate events when nothing changed, but records real theme changes',async()=>{await synchronize(root,{fetchRemote:false});expect((await synchronize(root,{fetchRemote:false})).events).toEqual([]);await writeFile(path.join(root,'space/attraction.json'),' {"theme":"ocean"} ');const changed=await synchronize(root,{fetchRemote:false});expect(changed.events[0]).toMatchObject({id:'space',type:'updated'});expect(changed.attractions[0].theme).toBe('ocean');expect(changed.history).toHaveLength(2);});
it('reports current remote state without merging unnecessarily',async()=>{const run=runner();const s=await synchronize(root,{run});expect(s.remote).toBe('connected');expect(s.pending).toBe(0);expect(run.mock.calls.map(c=>c[1][0])).not.toContain('merge');});
it('fast-forwards a clean worktree when new remote commits exist',async()=>{const run=runner({behind:2});const s=await synchronize(root,{run});expect(run).toHaveBeenCalledWith('git',['merge','--ff-only','origin/main'],expect.anything());expect(s.pending).toBe(0);expect(s.message).toContain('2개 반영');});
it.each([{behind:3,dirty:' M voice/src/cli.mjs'},{behind:2,ahead:1}])('preserves other agents’ work and divergent commits: %j',async setup=>{const run=runner(setup);const s=await synchronize(root,{run});expect(s.remote).toBe('pending');expect(s.pending).toBe(setup.behind);expect(run.mock.calls.map(c=>c[1][0])).not.toContain('merge');});
it('keeps local attractions available on network failure and redacts credentials',async()=>{const s=await synchronize(root,{run:runner({fail:true})});expect(s.remote).toBe('offline');expect(s.attractions[0].id).toBe('space');expect(s.error).not.toContain('token-secret');});
it('supports ordinary error messages when stderr is absent',async()=>{const s=await synchronize(root,{run:async()=>{throw new Error('offline');}});expect(s.error).toBe('offline');});
it('treats corrupt or missing runtime state as a first scan',async()=>{expect(await readState(root)).toBeNull();await mkdir(path.join(root,'.park-runtime'));await writeFile(path.join(root,'.park-runtime/state.json'),'bad');expect(await readState(root)).toBeNull();expect((await synchronize(root,{fetchRemote:false})).events).toHaveLength(1);});
it('limits the event history to forty entries',async()=>{await mkdir(path.join(root,'.park-runtime'));await writeFile(path.join(root,'.park-runtime/state.json'),JSON.stringify({history:Array(50).fill({type:'old'})}));expect((await synchronize(root,{fetchRemote:false})).history).toHaveLength(40);});
