import {optimizeCharging,scoreColor} from './core/charging.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function chargingPanel(host,{plan,site,radioData,scene,download}){
 const stations=radioData?.stations||[],operators=[...new Set(stations.map(s=>s.operator))].sort();let result,selectedId;
 const basement=Number((site.sourceAsset?.floor||site.parkingEvidence?.floor||'').match(/^B(\d+)/)?.[1]||0);
 host.innerHTML=`<p class="eyebrow">CHARGING / SITE SCREENING</p><h3>충전기 입지 비교</h3><p class="charging-summary">도면 구획 × 주변 기지국</p><div class="charging-fields"><label class="field">비교 대수<select id="charge-count">${[1,2,3,5,10].map(n=>`<option ${n===3?'selected':''}>${n}</option>`).join('')}</select></label><label class="field">통신 방식<select id="charge-radio"><option>LTE</option><option>5G</option><option value="all">전체 비교</option></select></label></div><label class="field">사업자<select id="charge-operator"><option value="all">전체 사업자 중 최대 추정 신호</option>${operators.map(o=>`<option>${esc(o)}</option>`).join('')}</select></label><details class="charging-assumptions"><summary>전파 추정 조건 조정</summary><div class="charging-fields"><label class="field">지하층 수<input id="charge-basement" type="number" min="0" max="8" value="${basement}"></label><label class="field">벽 1개 감쇠 (dB)<input id="charge-wall-loss" type="number" min="0" max="30" value="6"></label></div><p>경로손실 지수 3 · 지하층당 18 dB · 주변 환경 15 dB · 불확실성 ±12 dB. 실측 전의 비교용 가정입니다.</p></details><div class="score-legend"><span>빨강 · 부정 &lt;40</span><span>초록 · 긍정 ≥65</span></div><p class="score-unknown">회색: 자료 부족 또는 제외 · 중간 점수는 황색. 초록 후보만 우선 검토합니다.</p><p id="charge-summary"></p><div id="charge-candidates" class="charge-candidates"></div><div id="charge-detail"></div><details class="charging-evidence"><summary>기지국 자료와 산정 근거</summary><p>${stations.length}개 공개 LTE·5G 지상 기지국 표본 · 반경 1km${radioData?' · '+esc(radioData.acquiredAt.slice(0,10)):''}</p><p>통신사·방식별 가까운 8개를 최대 48개까지 조회했습니다. 현재 가동 여부와 안테나 방향은 확인되지 않았습니다.</p><p>공개 송신출력·주파수·이득과 거리, 도면 벽 통과를 사용한 추정 수신전력입니다. RSRP 실측값이 아닙니다.</p><p>차로 있음: 통신 50% · 접근 30% · 공간 20%. 차로 미확인: 통신 80% · 공간 20%. 비교 기준 −105~−65 dBm, 통신사 품질 보증 기준 아님.</p><a href="https://spectrummap.kr/gis/mobile_service.do?menuNo=300480" target="_blank" rel="noopener">전파누리 공개 원본 ↗</a><p><a href="https://www.itu.int/rec/R-REC-P.525/en" target="_blank" rel="noopener">ITU-R P.525 자유공간 손실식 ↗</a></p></details><p class="charging-note">전원 용량·배선·현장 여유 공간은 미확인입니다. 후보 위치와 점수는 설치 전 검토용이며, 장애인·전용 구역은 일반 후보에서 제외합니다.</p><button id="charge-export" class="import-button">후보·기지국·계산 근거 다운로드 ↓</button>`;
 const $=s=>host.querySelector(s);
 function draw(){
  const settings={count:Number($('#charge-count').value),operator:$('#charge-operator').value,radio:$('#charge-radio').value,basements:Number($('#charge-basement').value),wallLossDb:Number($('#charge-wall-loss').value)};
  try{result=optimizeCharging(plan,site,stations,settings);}catch(error){$('#charge-summary').textContent=error.message;return;}
  if(!result.ranked.some(c=>c.id===selectedId))selectedId=result.selected[0]?.id||result.ranked[0]?.id;
  $('#charge-summary').textContent=`${result.ranked.length}개 구획 · ${result.selected.length}곳 우선 검토 · ${result.ranked.filter(c=>c.excluded).length}곳 제외`;
  $('#charge-candidates').innerHTML=result.ranked.map(c=>`<button data-candidate="${esc(c.id)}" class="charge-candidate ${c.id===selectedId?'selected':''}" style="--score-color:${scoreColor(c.score)}"><span><b>${esc(c.label)}</b><small>${c.excluded?'보존·제외':c.selected?'우선 검토':c.score===null?'자료 필요':'비교 후보'}</small></span><strong>${c.score??'—'}<small>점</small></strong></button>`).join('')||'<p class="empty-state">주차면 의미 레이어가 없는 도면입니다. 원본에서 구획을 확인한 뒤 후보를 생성할 수 있습니다.</p>';
  const c=result.ranked.find(c=>c.id===selectedId),r=c?.signal.best;
  $('#charge-detail').innerHTML=c?`<h4>${esc(c.label)} · 판단 근거</h4><div class="charge-rf" style="color:${scoreColor(c.rfScore)}"><strong>${r?Math.round(r.dbm):'—'}</strong> dBm <small>추정 수신전력</small></div>${r?`<p>범위 ${Math.round(r.lowDbm)} ~ ${Math.round(r.highDbm)} dBm<br>${esc(r.station.operator)} · ${r.frequencyMHz} MHz<br>거리 ${Math.round(r.distanceM)}m · 벽 ${r.walls}개<br>출력 ${r.station.powerW} W · 이득 ${r.station.gainDbi} dBi</p><p class="station-id">출처 기지국 ${esc(r.stationId)}</p>`:'<p>건물 위치 또는 기지국 제원 부족으로 전파 점수를 계산하지 않았습니다.</p>'}<p>${c.reasons.map(esc).join(' · ')||'도면의 일반 주차면에서 비교한 후보입니다.'}</p>${c.signal.alignment==='assumed-north-up-at-site-center'?'<p>도면 중심을 장소 좌표에 맞추고 위쪽을 북쪽으로 가정했습니다. 방위 정합이 필요합니다.</p>':''}`:'';
  for(const b of host.querySelectorAll('[data-candidate]'))b.onclick=()=>{selectedId=b.dataset.candidate;draw();};
  scene.showCharging(result,selectedId);host.dataset.ready='true';
 }
 for(const input of host.querySelectorAll('select,input'))input.onchange=draw;
 $('#charge-export').onclick=()=>download({site:{id:site.id,source:site.source},radio:radioData,result},`${site.id}-charging-screening.json`);
 draw();return {get result(){return result;},get selectedId(){return selectedId;},dispose(){host.innerHTML='';}};
}
