import './style.css';
import {TwinScene} from './graphics/scene.js';
import {googleMap,kakaoPhoto} from './graphics/providers.js';
import {route,evacuation,attachPosition,pointAt,moveAgent,DEFAULT_VEHICLE} from './core/navigation.js';
import {analyzeSvg,analyzeBlueprint,validatePlan,compileMeshes} from './core/analysis.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),base=import.meta.env.BASE_URL,asset=s=>base+s;
document.querySelector('#app').innerHTML=`
<header class="topbar"><a class="brand" href="${base}" aria-label="ATLAS 홈"><i>⌁</i> ATLAS<small>PARKING<br>INTELLIGENCE</small></a><nav aria-label="작업 공간"><button data-tab="plan" class="active">주차장 탐색</button><button data-tab="map">공간 지도</button><button data-tab="photo">사진과 외관</button></nav><a class="park-link" href="/park/">Wonder Park ↗</a></header>
<main class="workspace"><aside class="sidebar"><div><p class="eyebrow">FROM DRAWING TO DESTINATION</p><h1>도면 속 공간에,<br>길을 더하다.</h1><p class="intro">공개 도면에서 시작하는 입체적인 여정.<br>공간을 살펴보고, 다음 경로를 찾아보세요.</p></div><div class="library-heading">공개 도면 라이브러리 <span id="count">—</span></div><input id="search" class="search" aria-label="도면 검색" placeholder="⌕  건물, 주소 또는 층 검색"><div id="sites" class="site-list"></div><button id="lab" class="import-button">도로 → 주차·EV 시나리오 ↗</button><button id="import" class="import-button">＋ 내 도면 가져오기</button><input id="file" type="file" accept=".svg,.json,.png,.jpg,.jpeg,.pdf" hidden><div class="source-card"><p class="eyebrow">THE ORIGINAL DRAWING</p><img id="source-thumb" alt="선택한 도면 원본"><p id="source-note"></p><a id="source-link" target="_blank" rel="noopener">출처와 원본 확인 ↗</a></div></aside>
<section class="stage" aria-label="3D 공간"><canvas id="world" aria-label="3D 주차장 · 드래그 회전, 스크롤 확대"></canvas><div id="google-map" hidden></div><div class="stage-head"><div class="crumb">ATLAS / <span id="crumb">PUBLIC BLUEPRINTS</span></div><h2 id="scene-title">도면을 불러오고 있습니다</h2><span id="evidence" class="badge">원본 확인 중</span></div><label class="source-toggle"><input type="checkbox" id="source-overlay" checked> 원본 도면 겹쳐 보기</label><div id="map-note" class="map-note" hidden></div>
<section id="route-panel" class="route-panel" aria-label="경로 설정"><div class="panel-heading"><h3>어디로 갈까요?</h3><small>ROUTE PLANNER</small></div><div class="segmented"><button data-mode="car" class="active">▱ 차량</button><button data-mode="person">♙ 보행자</button></div><label class="field">출발<select id="start-node" aria-label="출발 위치"></select></label><label class="field">목적지<select id="destination" aria-label="목적지"></select></label><div class="vehicle-fields"><label class="field">차폭 (m)<input id="car-width" type="number" min="1" max="4" step=".1" value="1.9"></label><label class="field">회전반경 (m)<input id="car-radius" type="number" min="1" max="15" step=".1" value="5.2"></label></div><div class="metrics"><div><strong id="distance">—</strong><small>m</small><span>경로 거리</span></div><div><strong id="eta">—</strong><small>초</small><span>예상 이동 시간</span></div></div><p id="route-message" class="route-message">진입점과 동선을 확인합니다.</p><button id="play" class="primary" disabled>▷ 안내 시작</button><div class="controls-row"><button id="reset">↺ 출발점으로</button><label>재생 속도 <select id="speed" aria-label="재생 속도"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div><div class="fire"><button id="fire" aria-pressed="false">♧ 화재 우회 시뮬레이션 <span></span></button><p>위험 구역을 피해서 확인된 집결지를 탐색합니다.</p><label id="fire-field" class="field" hidden>화재 위치<select id="fire-location" aria-label="화재 위치"><option value="center">중앙 차로</option><option value="west">서측 차로</option><option value="east">동측 차로</option><option value="all">모든 집결지 차단</option></select></label></div></section>
<aside class="photo-panel" hidden><img id="photo" alt="건물 외관 출처 사진"><p id="photo-note"></p><a id="photo-source" target="_blank" rel="noopener">서울시 · 사진과 네이버 위치 ↗</a><button id="roadview" class="import-button">카카오 로드뷰</button></aside><div class="legend" hidden><span><i></i>주택</span><span><i></i>공동주택</span><span><i></i>빌딩</span><span><i></i>공공시설</span></div><div class="camera" aria-label="카메라 시점"><button data-camera="orbit" class="active">⊞ 전체 보기</button><button data-camera="third">3인칭</button><button data-camera="first">1인칭</button></div><div class="stage-bottom"><span><i class="status-dot"></i>WEBGL 2</span><span id="geometry-info">—</span><span>드래그하여 공간 둘러보기</span></div><div class="compass">↕</div></section></main>
<footer class="footer"><span>ATLAS RESEARCH · DRAWINGS BECOME PLACES</span><a href="/reports/map_new/" target="_blank" rel="noopener">검증 현황 <b id="quality-status">확인 중</b> ↗</a><a id="export" href="#">모델 데이터 ↓</a><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a><a href="/map/">기존 ATLAS ↗</a></footer><div id="toast" role="status" hidden></div><dialog id="dialog"><button aria-label="닫기">×</button><div id="dialog-content"></div></dialog>`;
let scene,catalog=[],selected,plan,model,activeRoute,pose,travel=0,playing=false,mode='car',camera='orbit',tab='plan',hazards=[],fire=false,version=0,mapView,ownedUrl,lastUi=0,toastTimer;
const keys=new Set();
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function modal(content){$('#dialog-content').innerHTML=content;$('#dialog').showModal();}$('#dialog>button').onclick=()=>$('#dialog').close();
const vehicle=()=>({...DEFAULT_VEHICLE,width:Number($('#car-width').value),turnRadius:Number($('#car-radius').value)});
function options(){return {mode,hazards,vehicle:vehicle()};}
function sites(query=''){$('#sites').innerHTML=catalog.filter(s=>!s.synthetic&&(!query||`${s.name} ${s.address}`.includes(query))).map(s=>`<button class="site ${s.id===selected?.id?'active':''}" data-site="${esc(s.id)}"><span class="site-icon">${s.buildingType==='house'?'⌂':'▥'}</span><span><b>${esc(s.name)}</b><small>${s.routingReady?'차로 주석 포함 · 3D 주행':'원본 분석 · 벽체 후보'}${s.photo?' · 외관 사진':''}</small></span></button>`).join('');$('#sites').querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>select(b.dataset.site));}
function fillControls(){
  $('#start-node').innerHTML=plan.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.label||n.id)}</option>`).join('');
  $('#start-node').value=plan.nodes.find(n=>n.id==='road-west')?.id||plan.nodes.find(n=>n.kind==='road')?.id||plan.nodes.find(n=>n.kind==='entrance')?.id||plan.nodes[0]?.id||'';
  const goals=plan.nodes.filter(n=>mode==='car'?['ev','parking','building'].includes(n.kind):['shelter','exit','ev','building','parking'].includes(n.kind));
  $('#destination').innerHTML=goals.map(n=>`<option value="${esc(n.id)}">${esc(n.label||n.id)}</option>`).join('');
  $('#destination').value=goals.find(n=>n.kind==='ev')?.id||goals[0]?.id||'';
  $('#start-node').disabled=!plan.routingReady;$('#destination').disabled=!plan.routingReady||fire;
}
function updateMetrics(){
  $('#distance').textContent=activeRoute?Math.max(0,Math.round(activeRoute.distance-travel)):'—';$('#eta').textContent=activeRoute?Math.max(0,Math.ceil((activeRoute.distance-travel)/(mode==='car'?vehicle().speed:1.3))):'—';
}
function calculate(fromCurrent=false){
  playing=false;travel=0;activeRoute=null;
  if(plan.routingReady){const attached=fromCurrent&&pose?attachPosition(plan,pose,options()):{plan,startId:$('#start-node').value};if(attached)activeRoute=fire?evacuation(attached.plan,attached.startId,options()):route(attached.plan,attached.startId,$('#destination').value,options());}
  if(!fromCurrent){const origin=plan.nodes.find(n=>n.id===$('#start-node').value);pose=origin?{...origin,y:origin.y||0,heading:Math.PI}:null;}
  if(activeRoute&&activeRoute.points.length>1){pose=pointAt(activeRoute,0);}
  if(pose)scene?.setPose(pose,mode);scene?.setRoute(activeRoute);scene?.setHazards(hazards);updateMetrics();
  $('#play').disabled=!activeRoute||activeRoute.distance===0;$('#play').textContent='▷ 안내 시작';
  $('#route-message').textContent=!plan.routingReady?'동선 레이어가 없는 도면입니다. 벽체 분석만 표시합니다.':!activeRoute?(fire?'위험을 피해서 도달할 수 있는 확인된 집결지가 없습니다.':'차량 제원과 통로 조건에 맞는 경로가 없습니다.'):fire?`${activeRoute.destination.label}까지 보행 대피 · ${activeRoute.edges.length}개 구간`:`${activeRoute.ids.some(id=>id.startsWith('road-'))?'외부 도로 → 건물 진입 → ':''}${activeRoute.destination.label} · ${mode==='car'?'회전반경 '+vehicle().turnRadius+'m':'보행 1.3m/s'}`;
}
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('.vehicle-fields').hidden=mode!=='car';fillControls();}
async function select(id){
  const token=++version;playing=false;const site=catalog.find(s=>s.id===id);if(!site)return;
  try{const response=await fetch(asset(site.modelFile));if(!response.ok)throw Error('도면 데이터를 읽지 못했습니다.');const data=await response.json();validatePlan(data.plan);if(token!==version)return;
    selected=site;plan=data.plan;model=data.model;fire=false;hazards=[];setMode('car');$('#fire').setAttribute('aria-pressed','false');$('#fire-field').hidden=true;sites($('#search').value);$('#source-thumb').src=asset(site.sourceAsset.file);$('#source-link').href=site.source||asset(site.sourceAsset.file);$('#source-note').textContent=site.parkingEvidence?.note||(site.synthetic?'합성 시나리오 · 실제 시설 아님':'공개 평면도 · 축척과 문 위치 검토 필요');
    try{localStorage.setItem('atlas-parking-site',id);}catch{}await showTab('plan');
  }catch(error){notify(error.message);}
}
async function showTab(next){
  if(!plan)return;tab=next;playing=false;scene.canvas.onclick=null;mapView?.dispose?.();mapView=null;
  document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#google-map').hidden=true;$('.photo-panel').hidden=tab!=='photo';$('.legend').hidden=tab!=='map';$('#map-note').hidden=tab!=='map';$('#route-panel').hidden=tab!=='plan';$('.source-toggle').hidden=tab!=='plan';$('.camera').hidden=tab==='map';camera='orbit';document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera==='orbit'));
  if(tab==='plan'){
    $('#scene-title').textContent=selected.name;$('#crumb').textContent='PUBLIC BLUEPRINTS';$('#evidence').textContent=selected.synthetic?'검증용 합성 도면':plan.graphAnalysis?'공개 원본 · 주차 레이어 → 자동 그래프':plan.provenance?.kind==='source-traced'?'공개 원본 · 수동 동선 주석 · 추정 축척':'공개 원본 · 구조선 자동 분석';$('#evidence').classList.toggle('warn',!!selected.synthetic);
    scene.showPlan(plan,model,selected.sourceAsset?.file?asset(selected.sourceAsset.file):ownedUrl);scene.sourceOverlay&&(scene.sourceOverlay.visible=$('#source-overlay').checked);$('#geometry-info').textContent=`${model.meshes.length} WALLS / ${plan.nodes.length} NODES`;calculate();
  }else if(tab==='map'){
    $('#scene-title').textContent='도면이 있는 장소들';$('#crumb').textContent='GEOREFERENCED PLACES';$('#evidence').textContent='주소 좌표 · 유형별 개념 건물';$('#geometry-info').textContent='WGS84 / SEOUL';$('#map-note').textContent='좌표 기반 개념 지도 · 지형·건물 크기는 축약 표시합니다. Google 지도를 연결하려면 브라우저 API 키를 설정하세요.';scene.showLocations(catalog,select);
    if(import.meta.env.VITE_GOOGLE_MAPS_API_KEY){$('#google-map').hidden=false;try{const view=await googleMap($('#google-map'),catalog,select,{key:import.meta.env.VITE_GOOGLE_MAPS_API_KEY,mapId:import.meta.env.VITE_GOOGLE_MAPS_MAP_ID});if(tab!=='map'){view.dispose?.();return;}mapView=view;$('#map-note').textContent='Google 지도 · 주소 좌표에 3D 건물 배치';}catch(error){$('#google-map').hidden=true;notify(error.message);}}
  }else{
    const photoSite=catalog.find(s=>s.photo);$('#scene-title').textContent='너나들이 · 사진에서 읽은 외관';$('#crumb').textContent='PHOTO-INFORMED BUILDING';$('#evidence').textContent='서울시 사진 + 네이버 위치 · 개념 재구성';scene.showExterior(photoSite);$('#photo').src=asset(photoSite.photo.file);$('#photo-note').textContent='OSM 건물 윤곽에 공개 도면·입주표의 4개 주거층과 사진의 외관 색상을 반영했습니다. 높이와 세부 입면은 추정값입니다.';$('#photo-source').href=photoSite.photo.source;$('#geometry-info').textContent='NAVER LOCATION / PUBLIC PHOTO';
  }
}
function update(dt){
  if(tab!=='plan'||!pose)return;
  if(playing&&activeRoute){travel+=dt*(mode==='car'?vehicle().speed:1.3)*Number($('#speed').value);pose=pointAt(activeRoute,travel);scene.setPose(pose,mode);if(pose.arrived){playing=false;$('#play').textContent='✓ 도착했습니다';$('#play').disabled=true;notify(activeRoute.destination.label+'에 도착했습니다.');}}
  else if(keys.size){pose=moveAgent(plan,pose,{forward:(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),turn:(keys.has('a')||keys.has('arrowleft')?1:0)-(keys.has('d')||keys.has('arrowright')?1:0)},dt,options());scene.setPose(pose,mode);}
  lastUi+=dt;if(lastUi>.15){updateMetrics();lastUi=0;}
}
function setHazards(){
  const key=$('#fire-location').value;
  hazards=key==='all'?plan.nodes.filter(n=>n.safe).map(n=>({x:n.x,y:n.y||0,z:n.z,radius:6})):[{x:key==='west'?-24:key==='east'?24:0,z:0,radius:5}];
}
$('#fire').onclick=()=>{if(!plan.routingReady)return notify('대피 경로를 구성할 동선 레이어가 필요합니다.');fire=!fire;if(fire){setMode('person');setHazards();}else{hazards=[];}$('#fire').setAttribute('aria-pressed',String(fire));$('#fire-field').hidden=!fire;$('#destination').disabled=fire;calculate(true);};
$('#fire-location').onchange=()=>{setHazards();calculate(true);};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(fire&&b.dataset.mode==='car')return notify('화재 대피 중에는 보행 모드를 사용합니다.');setMode(b.dataset.mode);calculate(true);});
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{if(b.dataset.camera!=='orbit'&&(tab!=='plan'||!pose))return notify('이동 경로가 있는 도면에서 사용할 수 있습니다.');camera=b.dataset.camera;scene.setView(camera);document.querySelectorAll('[data-camera]').forEach(x=>x.classList.toggle('active',x===b));});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#play').onclick=()=>{if(!activeRoute)return;playing=!playing;$('#play').textContent=playing?'Ⅱ 안내 일시정지':'▷ 안내 재개';};$('#reset').onclick=()=>calculate();
for(const id of ['start-node','destination','car-width','car-radius'])$('#'+id).onchange=()=>{try{calculate(id==='destination');}catch(e){playing=false;activeRoute=null;$('#play').disabled=true;notify(e.message);}};
$('#source-overlay').onchange=e=>{if(scene.sourceOverlay)scene.sourceOverlay.visible=e.target.checked;};$('#source-thumb').onclick=()=>modal(`<img src="${esc($('#source-thumb').src)}" alt="원본 도면 확대"><p>${esc($('#source-note').textContent)}</p>`);$('#search').oninput=e=>sites(e.target.value);$('#lab').onclick=()=>select('integration-lab');
$('#roadview').onclick=async()=>{modal('<h2>카카오 로드뷰</h2><p id="roadview-status">주변 거리 사진을 확인합니다.</p><div id="roadview-map" class="roadview"></div>');try{const result=await kakaoPhoto($('#roadview-map'),catalog.find(s=>s.photo),import.meta.env.VITE_KAKAO_MAPS_APP_KEY);$('#roadview-status').textContent={connected:'건물 좌표 반경 50m 이내의 거리 사진입니다.','missing-key':'카카오 JavaScript 키가 설정되지 않았습니다. map_new/.env.local에 VITE_KAKAO_MAPS_APP_KEY를 설정하세요.','no-imagery':'이 위치 주변에서 거리 사진을 찾지 못했습니다.','missing-location':'건물 좌표가 없습니다.'}[result.status];}catch(e){$('#roadview-status').textContent=e.message;}};
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export').onclick=e=>{e.preventDefault();download({plan,model},`${plan.id||'import'}-model.json`);};
async function pixels(url){const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,1200/Math.max(image.width,image.height)),c=document.createElement('canvas');c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,c.width,c.height);return ctx.getImageData(0,0,c.width,c.height);}
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const token=++version;try{if(file.size>20e6)throw Error('20MB 이하의 도면을 선택하세요.');let result,url;
  if(/\.svg$/i.test(file.name))result=analyzeSvg(await file.text());else if(/\.json$/i.test(file.name)){const data=JSON.parse(await file.text());result=validatePlan(data.plan||data);}else if(/\.pdf$/i.test(file.name)){const {openPdf,pdfPage}=await import('../../map/src/graphics/pdf.js');const doc=await openPdf(await file.arrayBuffer());try{const page=await pdfPage(doc,1);result=analyzeBlueprint(page.pixels);url=page.image;}finally{await doc.destroy();}}else{url=URL.createObjectURL(file);result=analyzeBlueprint(await pixels(url));}
  if(token!==version){if(url?.startsWith('blob:'))URL.revokeObjectURL(url);return;}if(ownedUrl?.startsWith('blob:'))URL.revokeObjectURL(ownedUrl);ownedUrl=url;plan=result;model=compileMeshes(plan);selected={id:'import',name:file.name,sourceAsset:null};setMode('car');fire=false;hazards=[];$('#fire-field').hidden=true;$('#fire').setAttribute('aria-pressed','false');await showTab('plan');notify('도면을 변환했습니다. 축척과 동선 정보를 확인하세요.');
 }catch(error){notify(error.message);}finally{$('#file').value='';}};
document.addEventListener('keydown',e=>{if(tab!=='plan'||!pose||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||$('#dialog').open)return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();playing=false;keys.add(key);}});document.addEventListener('keyup',e=>{const had=keys.delete(e.key.toLowerCase());if(had&&!keys.size&&plan)calculate(true);});window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();playing=false;}});
async function quality(){try{const r=await fetch('/reports/map_new/latest.json',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();$('#quality-status').textContent=`${d.status==='passed'?'통과':d.status==='running'?'검증 중':'확인 필요'} · ${new Date(d.at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`;}catch{$('#quality-status').textContent='아직 검증 기록 없음';}}
try{scene=new TwinScene($('#world'),update);const response=await fetch(asset('generated/catalog.json'));if(!response.ok)throw Error('생성된 도면 목록이 없습니다. convert 명령을 실행하세요.');catalog=await response.json();$('#count').textContent=catalog.filter(s=>!s.synthetic).length;let remembered;try{remembered=localStorage.getItem('atlas-parking-site');}catch{}const initial=new URLSearchParams(location.search).get('site')||remembered;await select(catalog.some(s=>s.id===initial)?initial:'10000901-0');}catch(error){$('#scene-title').textContent='공간을 열지 못했습니다';$('#route-message').textContent=error.message;notify(error.message);}
quality();const qualityTimer=setInterval(quality,15000);window.__parking={get state(){return {selected,plan,model,mode,camera,tab,hazards,route:activeRoute,pose,travel,playing,fire,provider:mapView?.status||'not-connected'};},scene,select};window.addEventListener('pagehide',()=>{clearInterval(qualityTimer);scene?.dispose();mapView?.dispose?.();if(ownedUrl?.startsWith('blob:'))URL.revokeObjectURL(ownedUrl);});
