import '@fontsource-variable/dm-sans';
import '@fontsource-variable/noto-sans-kr';
import './style.css';
import './charging.css';
import {floorDetails,complexReferences} from './library-details.js';
import {chargingWorkspace} from './charging-workspace.js';
import {prepareVehicle} from './graphics/vehicle.js';
import { AtlasScene } from './graphics/scene.js';
import { createGoogleMap } from './graphics/google-map.js';
import { AudioGuide } from './graphics/audio.js';
import { analyzeBlueprint,analyzeSvg,validatePlan } from './core/analysis.js';
import { route,evacuation,attachPosition,sampleRoute,canMove } from './core/routing.js';

const icons={map:'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Zm6-3v15m6-12v15"/>',cube:'<path d="m12 3 9 5v9l-9 5-9-5V8l9-5Zm0 19V12m-9-4 9 4 9-4m-14-7 9 5"/>',layers:'<path d="m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',car:'<path d="m5 8 2-5h10l2 5M4 9h16v9H4V9Zm2 9v3m12-3v3M7 12h2m6 0h2"/>',fire:'<path d="M12 2c2 5 8 7 8 13a8 8 0 0 1-16 0c0-3 2-6 4-8 0 4 2 5 3 5 1-3 2-5 1-10Z"/>',sound:'<path d="m3 9 4 0 5-4v14l-5-4H3V9Zm13-2a8 8 0 0 1 0 10m3-13a12 12 0 0 1 0 16"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6"/>',check:'<path d="m5 12 4 4L20 5"/>',close:'<path d="m5 5 14 14M5 19 19 5"/>',play:'<path d="m8 4 12 8-12 8V4Z"/>',reset:'<path d="M4 10a8 8 0 1 1 1 8M4 3v7h7"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',pin:'<path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="9" r="2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-11v2"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.cube}</svg>`;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s),capture=new URLSearchParams(location.search).has('capture');
let pdfDocument=null,pdfModule=null,charging=null;
let catalog=[],scene,googleView,plan=null,selected=null,currentAsset=0,screen='map',labSource='lab',mapStyle='google',mode='car',camera='orbit',activeRoute=null,travel=0,playing=false,hazards=[],pose={x:0,z:27,heading:Math.PI},loadVersion=0,noticeTimer;
const audio=new AudioGuide(),keys=new Set();
document.querySelector('#app').innerHTML=`
<header class="header"><a class="brand" href="./" aria-label="ATLAS 처음으로"><span class="brand-mark">${icon('layers')}</span>ATLAS<span class="brand-sub">SPATIAL INTELLIGENCE</span></a><nav aria-label="주 메뉴"><button class="nav active" data-nav="map">공간 탐색</button><button class="nav" data-nav="plans">도면 라이브러리 <span id="catalog-count">—</span></button><button class="nav" data-nav="lab">주차장 시뮬레이션</button><button class="nav" data-nav="charging">충전기 설치 추천</button></nav><div class="header-right"><span class="preview-label"><i></i> RESEARCH PREVIEW</span><button class="icon-button" id="sound" aria-label="소리 안내 켜기" aria-pressed="false">${icon('sound')}</button><a class="icon-button" href="/reports/index.html" title="검증 보고서" aria-label="검증 보고서">${icon('check')}</a></div></header>
<div class="workspace"><aside class="sidebar"><div class="sidebar-top"><div class="eyebrow">SOUTH KOREA <span id="catalog-range">01 — 40</span></div><h1>도면에서,<br><em>공간으로.</em></h1><p class="intro">평면 너머의 공간을 탐험하세요.<br>출발점에서 목적지까지, 더 명확하게.</p><label class="search">${icon('search')}<input id="search" placeholder="건물 이름 또는 주소 검색" aria-label="건물 검색"><span>⌘ K</span></label></div><div class="list-heading"><strong>도면을 확보한 공간 <span id="site-count">10</span></strong><span>공개 도면 원본</span></div><div id="site-list" class="site-list"></div><button id="lab-launch" class="lab-launch"><span class="lab-icon">${icon('car')}</span><span><small>INTERACTIVE LAB</small><strong>주차장 길찾기 체험</strong></span>${icon('arrow')}</button><div class="sidebar-foot"><i></i> 원본 출처 확인 가능 <span>↗</span></div></aside>
<main class="stage"><div id="world" class="world"></div><div id="google-map" class="google-map"></div><section id="library" class="library" hidden></section><div class="stage-top"><div class="breadcrumbs"><span id="crumb">서울</span><span>/</span><strong id="crumb-title">공간 탐색</strong></div><div id="map-switch" class="segmented"><button data-map="google" class="selected">${icon('map')} Google 지도</button><button data-map="city">${icon('cube')} 3D 미리보기</button></div><button class="back-button" id="back" hidden>← 서울 지도로</button></div>
<div id="explore-caption" class="explore-caption"><span class="eyebrow">A NEW PERSPECTIVE ON SPACE</span><h2>도시를 읽는<br>새로운 시선.</h2><p>왼쪽 목록에서 공간을 선택해<br>실제 도면의 3D 분석을 시작하세요.</p><span class="caption-line"></span></div>
<div id="map-note" class="map-note">Google 지도 · 원본 도면은 왼쪽 목록에서 선택</div>
<div id="model-tools" class="model-tools" hidden><div class="segmented"><button data-model="3d" class="selected">${icon('cube')} 3D 분석</button><button data-model="2d">${icon('layers')} 원본 도면</button><button data-model="exterior">${icon('eye')} 건물 매스</button></div><button id="source-info" class="icon-button" aria-label="도면 출처와 분석 정보">${icon('info')}</button></div>
<div id="flat-plan" class="flat-plan" hidden><img id="flat-image" alt="선택한 평면도 원본"></div>
<aside id="plan-info" class="plan-info" hidden></aside><section id="route-panel" class="route-panel" hidden></section>
<div id="simulation-banner" class="simulation-banner" hidden>${icon('info')} 주차장 시험 도면 · 실제 건물의 주차장/비상 안내가 아닙니다.</div>
<div id="camera-controls" class="camera-controls" hidden><div class="segmented"><button data-camera="orbit" class="selected">전체 보기</button><button data-camera="first">1인칭</button><button data-camera="third">3인칭</button></div><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 직접 이동</span></div>
<div class="view-controls"><span class="compass">N<span>↑</span></span><button class="icon-button" id="zoom-in" aria-label="확대">+</button><button class="icon-button" id="zoom-out" aria-label="축소">−</button><button class="icon-button" id="reset-view" aria-label="시점 초기화">${icon('reset')}</button></div>
<div id="render-error" class="render-error" hidden></div><div class="stage-footer"><span id="scene-status"><i></i> 라이브러리의 공간을 탐색하세요</span><span id="render-stats">WEBGL 2 <b>·</b> ATLAS ENGINE</span></div></main></div>
<footer class="footer"><span>ATLAS / 도면 분석 연구소 <span class="construction">공사 중</span></span><div><button id="import">${icon('upload')} 내 도면 가져오기</button><a href="/reports/index.html">테스트 리포트 ↗</a><button id="about">프로젝트 안내 ↗</button></div><span>DESIGNED TO FIND YOUR WAY.</span></footer><input type="file" id="file" accept=".pdf,.png,.jpg,.jpeg,.svg,.json" hidden><dialog id="dialog"><button id="dialog-close" class="icon-button" aria-label="닫기">${icon('close')}</button><div id="dialog-content"></div></dialog><div id="notification" role="status" aria-live="polite"></div>`;

function notify(message,kind='notice'){const n=$('#notification');n.textContent=message;n.dataset.kind=kind;n.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.classList.remove('visible'),6000);audio.play(message,kind);}
function dialog(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
$('#dialog-close').onclick=()=>$('#dialog').close();
function setScreen(next){if(next!=='charging'){charging?.dispose();charging=null;}document.body.classList.toggle('ev-mode',next==='charging');screen=next;playing=false;keys.clear();$('#route-panel').hidden=next!=='lab';$('#simulation-banner').hidden=next!=='lab';$('#camera-controls').hidden=next!=='lab';$('#plan-info').hidden=next!=='plan';$('#model-tools').hidden=next!=='plan';$('#back').hidden=next==='map';$('#map-switch').hidden=next!=='map';$('#library').hidden=next!=='plans';$('#explore-caption').hidden=next!=='map';$('#map-note').hidden=next!=='map';$('#flat-plan').hidden=true;$('#google-map').hidden=next!=='map'||mapStyle!=='google';$('#world').hidden=next==='plans'||next==='map'&&mapStyle==='google';document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===(next==='plan'?'plans':next)));scene?.resize();googleView?.resize?.();if(next==='map'&&googleView?.mode==='address-map')$('#explore-caption').hidden=true;}
function siteList(filter=''){const list=catalog.filter(s=>(s.name+s.address).toLowerCase().includes(filter.toLowerCase()));$('#site-count').textContent=list.length;$('#site-list').innerHTML=list.length?list.map(s=>`<button class="site-card ${s.id===selected?.id?'active':''}" data-site="${s.id}"><div class="site-thumb"><img src="${s.assets[0].file}" alt="" loading="lazy"><span>${String(catalog.indexOf(s)+1).padStart(2,'0')}</span></div><div class="site-copy"><h3>${escape(s.name.replace(' - 공동육아형 공동체주택',''))}</h3><p>${escape(s.address.split(' ').slice(0,3).join(' '))}</p><small>${s.assets.length}개 도면 <i>·</i> ${s.parkingStatus==='verified-in-published-plan'?'주차장 확인':'원본 확보'}</small></div><span class="site-arrow">↗</span></button>`).join(''):'<p class="empty">일치하는 공간이 없습니다.<br>다른 이름으로 검색해 주세요.</p>';$('#site-list').querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>selectSite(b.dataset.site));}
function showMap(){++loadVersion;setScreen('map');scene?.showCity(catalog);$('#crumb').textContent='서울';$('#crumb-title').textContent='공간 탐색';$('#scene-status').innerHTML='<i></i> 도면과 위치를 함께 탐색하세요';}
function showLibrary(){++loadVersion;setScreen('plans');$('#crumb-title').textContent='도면 라이브러리';$('#library').innerHTML=`<div class="eyebrow">THE BLUEPRINT COLLECTION</div><h2>모든 공간의 시작.</h2><p>공개 발행 자료에서 수집한 ${catalog.length}곳, ${catalog.reduce((sum,s)=>sum+s.assets.length,0)}장의 원본 평면도. 주차 구획을 확인한 추가 30곳은 서울 15곳과 다른 지역 15곳입니다.</p><div class="collection-filters"><button data-filter="all" aria-pressed="true">전체 ${catalog.length}</button><button data-filter="parking" aria-pressed="false">주차장 도면 ${catalog.filter(s=>s.parkingStatus==='verified-in-published-plan').length}</button><button data-filter="multilevel" aria-pressed="false">지하 1–4층</button><button data-filter="complex" aria-pressed="false">아파트 단지</button></div><button id="public-parking" class="public-parking">${icon('car')} 실제 주차장 도면 · 동북권 세대융합형 복합시설 B2 분석 ${icon('arrow')}</button><button id="source-drive" class="public-parking">${icon('car')} 이 주차장의 코어까지 주행 체험 ${icon('arrow')}</button><div class="library-grid">${catalog.map(s=>`<button data-site="${s.id}" data-parking="${s.parkingStatus==='verified-in-published-plan'}" data-multilevel="${s.assets.filter(a=>/^B[1-4]$/.test(a.floor)).length===4}" data-complex="${Boolean(s.complexInfo)}"><img src="${s.assets[0].file}" alt="${escape(s.name)} 평면도"><span>${escape(s.name)}</span><small>${escape(s.address.split(' ').slice(0,3).join(' '))} · ${s.assets.length}개 도면 ${icon('arrow')}</small></button>`).join('')}</div>${complexReferences()}`;$('#library').querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>selectSite(b.dataset.site));$('#library').querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{$('#library').querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#library').querySelectorAll('.library-grid button').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset[b.dataset.filter]!=='true');$('#library .complex-references').hidden=b.dataset.filter!=='complex';});$('#source-drive').onclick=()=>loadLab('changdong');$('#public-parking').onclick=async()=>{pdfModule=await import('./graphics/pdf.js');try{const res=await fetch('/plans/changdong-parking-source.pdf');await pdfDocument?.destroy();pdfDocument=await pdfModule.openPdf(await res.arrayBuffer());await renderPdf(16,'동북권 세대융합형 복합시설 · B2 주차장');}catch(e){notify(e.message);}};}
async function imagePixels(url){const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,900/Math.max(image.width,image.height));const c=document.createElement('canvas');c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);const context=c.getContext('2d',{willReadFrequently:true});context.fillStyle='#fff';context.fillRect(0,0,c.width,c.height);context.drawImage(image,0,0,c.width,c.height);return context.getImageData(0,0,c.width,c.height);}
async function renderPdf(number,name=plan?.name||'PDF 도면'){const version=++loadVersion;try{const {pixels,image}=await pdfModule.pdfPage(pdfDocument,number);if(version!==loadVersion)return;plan=analyzeBlueprint(pixels,{metersPerPixel:30/pixels.width});plan.name=name;selected=null;setScreen('plan');scene?.showPlan(plan);$('#flat-image').src=image;$('#crumb').textContent=name;$('#crumb-title').textContent=`PDF ${number}쪽 분석`;planInfo();$('#pdf-page').value=number;notify(`${number}쪽 구조선 ${plan.walls.length}개를 추출했습니다.`);}catch(error){notify(error.message);}}
async function selectSite(id,assetIndex=0,model=null){
 const site=catalog.find(s=>s.id===id);if(!site?.assets[assetIndex])return;model??=site.basementFloors?'2d':'3d';if(pdfDocument){await pdfDocument.destroy();pdfDocument=null;}const version=++loadVersion;selected=site;currentAsset=assetIndex;siteList($('#search').value);setScreen('plan');$('#scene-status').textContent='원본 도면의 구조선을 분석하고 있습니다…';$('#plan-info').innerHTML='<div class="eyebrow">ANALYZING BLUEPRINT</div><h2>공간을 읽고 있어요.</h2>';$('#crumb').textContent=site.name;$('#crumb-title').textContent='도면 분석';
 try{const pixels=await imagePixels(site.assets[assetIndex].file);if(version!==loadVersion)return;plan=analyzeBlueprint(pixels,{metersPerPixel:30/pixels.width,minLength:Math.max(18,pixels.width*.025)});plan.name=site.name;plan.source=site.source;plan.floor=site.assets[assetIndex].floor||null;plan.sourceAsset=site.assets[assetIndex].file;plan.sourcePage=site.assets[assetIndex].sourcePage||null;scene?.showPlan(plan);$('#flat-image').src=site.assets[assetIndex].file;planInfo();$('#scene-status').innerHTML=`<i></i> ${plan.walls.length}개 구조선 추정 · 축척 보정 전`;document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('selected',b.dataset.model===model));$('#flat-plan').hidden=model!=='2d';if(model==='exterior')scene?.showExterior(plan);if(plan.floor)$('#crumb-title').textContent=plan.floor==='SITE'?'단지 배치도':`${plan.floor} · 층별 도면`;}
 catch(error){if(version===loadVersion)notify(`도면 분석 실패: ${error.message}`);}
}
function planInfo(){const s=selected;$('#plan-info').innerHTML=`<div class="eyebrow">BLUEPRINT → SPATIAL MODEL</div><h2>${escape(plan.name)}</h2><p>${s?escape(s.address):'로컬에서 가져온 도면'}</p>${floorDetails(s,currentAsset)}${s?.parkingEvidence?`<p class="parking-evidence"><strong>${escape(s.parkingEvidence.floor)} · 주차장 도면 확인</strong><br>${escape(s.parkingEvidence.note)}<br><small>공개 도면 검토 · 현장 상태 미확인</small></p>`:''}<div class="analysis-stats"><div><strong>${plan.walls.length}</strong><span>추정 구조선</span></div><div><strong>2.8<small> m</small></strong><span>가정한 벽 높이</span></div></div><label class="field">도면 선택<select id="asset-select">${s?s.assets.map((a,i)=>`<option value="${i}" ${i===currentAsset?'selected':''}>${i+1}. ${escape(a.label)}</option>`).join(''):'<option>가져온 도면</option>'}</select></label><label class="field">도면 전체 너비 (m)<div class="scale-row"><input id="scale" type="number" min="1" max="200" step="0.1" value="${plan.width.toFixed(1)}" aria-label="도면 전체 너비"><button id="calibrate">축척 적용</button></div></label><p class="analysis-note">${plan.scaleStatus==='user-calibrated'?'사용자 입력 축척 적용.':'현재 축척과 높이는 시각화용 추정치입니다.'} 벽·문·계단은 원본과 대조가 필요합니다.</p>${s?.architect?`<p class="analysis-note">© ${escape(s.architect)} · ${escape(s.publisher||'브리크 매거진')}<br>원본 도면의 권리는 제작자에게 있습니다. 주소 범위 위치와 정확도는 지도 마커에서 확인할 수 있습니다.</p>`:''}<div class="source-links">${s?`<a href="${s.source}" target="_blank" rel="noopener">발행 원본 출처 ↗</a>`:''}<button id="export">분석 JSON ↓</button></div>${pdfDocument?`<label class="field">PDF 페이지<select id="pdf-page">${Array.from({length:pdfDocument.numPages},(_,i)=>`<option value="${i+1}">${i+1}쪽</option>`).join('')}</select></label>`:''}<button id="plan-map" class="public-parking" ${s?'':'hidden'}>지도에서 이 주소 보기 ↗</button><button id="plan-charging" class="public-parking">이 도면으로 충전기 설치 검토 ↗</button><button id="plan-lab" class="primary">주차장 시험장 체험 ${icon('arrow')}</button>`;
 $('#plan-map').onclick=()=>{mapStyle='google';showMap();googleView?.focus?.(s);};$('#plan-charging').onclick=()=>showCharging({...plan,id:s?`${s.id}:${currentAsset}`:'imported-plan'});const currentModel=()=>document.querySelector('[data-model].selected')?.dataset.model||'3d';$('#asset-select').onchange=e=>s&&selectSite(s.id,Number(e.target.value),currentModel());$('#plan-info').querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>selectSite(s.id,Number(b.dataset.assetIndex),currentModel()));$('#calibrate').onclick=()=>{const width=Number($('#scale').value);if(!Number.isFinite(width)||width<1||width>200)return notify('너비는 1~200m로 입력해 주세요.');const factor=width/plan.width;plan={...plan,width,depth:plan.depth*factor,walls:plan.walls.map(w=>({...w,x1:w.x1*factor,z1:w.z1*factor,x2:w.x2*factor,z2:w.z2*factor,thickness:w.thickness*factor})),scaleStatus:'user-calibrated'};scene?.showPlan(plan);planInfo();notify('입력한 축척으로 3D 모델을 갱신했습니다.');};$('#export').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));link.download='atlas-analysis.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};$('#plan-lab').onclick=loadLab;$('#pdf-page')?.addEventListener('change',async e=>{const number=Number(e.target.value);await renderPdf(number);});
}
async function showCharging(existing=null){if(existing){++loadVersion;plan=existing;charging?.dispose();charging=null;scene.showPlan(plan);}else{await loadLab();if(screen!=='lab')return;}setScreen('charging');scene.car.visible=false;scene.person.visible=false;scene.setRoute(null);$('#crumb').textContent='EV INFRASTRUCTURE';$('#crumb-title').textContent='충전기 설치 추천';$('#scene-status').innerHTML='<i></i> 전원 · 통신 · 접근성 분석';charging=chargingWorkspace({scene,plan,notify});scene.resize();}
async function loadLab(source='lab'){labSource=typeof source==='string'?source:'lab';playing=false;activeRoute=null;$('#route-panel').setAttribute('aria-busy','true');if($('#start'))$('#start').disabled=true;if($('#destination'))$('#destination').disabled=true;const version=++loadVersion;try{const res=await fetch(labSource==='changdong'?'/plans/changdong-parking-annotated.svg':'/plans/parking-lab.svg');if(!res.ok)throw new Error('주차장 도면을 읽지 못했습니다.');const parsed=analyzeSvg(await res.text());if(version!==loadVersion)return;plan=parsed;selected=null;mode='car';camera='orbit';hazards=[];activeRoute=null;travel=0;const entry=plan.nodes.find(n=>n.kind==='entrance');pose={x:entry.x,z:entry.z,heading:entry.heading};setScreen('lab');scene?.showPlan(plan,{garage:true});$('#crumb').textContent='ATLAS LAB';$('#crumb-title').textContent=labSource==='changdong'?'실제 B2 도면 · 코어 접근':'B1 주차장';$('#scene-status').innerHTML=labSource==='changdong'?'<i></i> 원본 PDF 좌표 기반 · 분석가 지정 동선':'<i></i> 도면에서 생성한 주차장 · 4개 동 연결';$('#simulation-banner').innerHTML=icon('info')+(labSource==='changdong'?'계획 도면의 근사 모델 · 동선 수동 지정 · 축척/현장 상태 검증 전':'주차장 시험 도면 · 실제 건물의 주차장/비상 안내가 아닙니다.');document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('selected',b.dataset.camera==='orbit'));routePanel();planRoute(true);$('#route-panel').setAttribute('aria-busy','false');}catch(e){notify(e.message);}}
function routePanel(){
 $('#route-panel').innerHTML=`<div class="eyebrow">${mode==='person'?'EVACUATION SIMULATION':'PARKING NAVIGATION'}<span class="live-dot"></span></div><h2>${mode==='person'?'안전한 출구를 향해.':'어느 동으로 갈까요?'}</h2><p>${mode==='person'?'화재 구역을 제외하고 외부 집결지까지 탐색합니다.':'입구에서 동 입구 정차 지점까지 안내합니다.'}</p><div class="route-origin"><span class="origin-dot"></span><span>${mode==='person'?'현재 보행 위치':'차량 현재 위치'}</span><small>B1</small></div><div class="route-connector"></div><label class="destination-label">${icon('pin')}<select id="destination" aria-label="목적지 동" ${mode==='person'?'disabled':''}>${plan.nodes.filter(n=>n.kind==='building').map(n=>`<option value="${escape(n.id)}">${escape(n.label)}</option>`).join('')}</select></label><div id="route-result" class="route-result"></div><div class="route-actions"><button id="start" class="primary">${icon('play')} 안내 시작</button><button id="restart" class="icon-button" aria-label="입구로 초기화">${icon('reset')}</button></div><label class="speed-control">재생 속도<select id="speed" aria-label="재생 속도"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label><div class="fire-divider"></div><button id="fire-toggle" class="fire-toggle ${mode==='person'?'on':''}" aria-pressed="${mode==='person'}">${icon('fire')}<span><strong>${mode==='person'?'화재 시뮬레이션 종료':'화재 상황 시뮬레이션'}</strong><small>${mode==='person'?'보행 모드 · 엘리베이터 경로 제외':'사람의 이동 경로로 전환합니다'}</small></span><span class="switch"></span></button>${mode==='person'?'<label class="field fire-location">화재 위치<select id="fire-location"><option value="center">중앙 차로</option><option value="west">서쪽 차로</option><option value="east">동쪽 차로</option><option value="all">양쪽 출구 차단</option></select></label>':''}`;
 $('#destination').onchange=()=>planRoute();$('#start').onclick=()=>{if(!activeRoute)return;playing=!playing;$('#start').innerHTML=playing?'Ⅱ 안내 일시정지':`${icon('play')} 안내 재개`;if(playing)notify(`${mode==='person'?'보행 대피':'차량'} 안내를 시작합니다.`);};$('#restart').onclick=()=>loadLab(labSource);$('#fire-toggle').onclick=()=>toggleFire();$('#fire-location')?.addEventListener('change',e=>{setFire(e.target.value);planRoute();});
}
function setFire(location='center'){hazards=location==='all'?[{x:-40,z:0,radius:5},{x:40,z:0,radius:5}]:[{x:location==='west'?-28:location==='east'?28:0,z:0,radius:5}];scene?.setHazards(hazards);}
function toggleFire(){if(labSource==='changdong'){notify('이 도면은 지상 대피 연결이 미확인입니다. 대피 시뮬레이션은 ATLAS 시험장에서 사용할 수 있습니다.');return;}if(mode==='person')return loadLab();mode='person';playing=false;setFire();scene?.setPose(pose,mode);routePanel();planRoute();notify('화재 시뮬레이션. 차량에서 내려 외부 집결지로 이동합니다.','fire');}
function planRoute(reset=false){
 playing=false;travel=0;const attached=reset?plan:attachPosition(plan,pose,mode);const start=reset?'entrance':'@position';activeRoute=attached?(mode==='person'?evacuation(attached,start,{hazards}):route(attached,start,$('#destination').value,{mode,hazards})):null;
 scene?.setRoute(activeRoute,mode==='person'?'#d28b57':'#5baf88');$('#start').disabled=!activeRoute;$('#start').innerHTML=`${icon('play')} 안내 시작`;
 if(!activeRoute){$('#route-result').innerHTML='<div class="no-route"><strong>통과 가능한 경로가 없습니다.</strong><span>위험 구역 또는 목적지를 변경해 주세요.</span></div>';notify('안전한 경로를 찾지 못했습니다. 이동을 중지합니다.','fire');return;}
 $('#route-result').innerHTML=`<div><strong id="distance">${Math.round(activeRoute.distance)}<small> m</small></strong><span>남은 거리</span></div><div><strong id="eta">${Math.ceil(activeRoute.seconds)}<small> 초</small></strong><span>예상 이동 시간</span></div><p>${icon('check')} ${mode==='person'?escape(activeRoute.destination.label)+' · 위험 회피 경로':'차량 통행 가능 · 동 입구 정차'}</p>`;
}
function update(delta){
 if(screen!=='lab'||!plan)return;
 if(playing&&activeRoute){travel+=delta*(mode==='person'?1.2:3.5)*Number($('#speed').value);pose=sampleRoute(activeRoute,travel);scene?.setPose(pose,mode);if($('#distance'))$('#distance').innerHTML=`${Math.max(0,Math.round(activeRoute.distance-travel))}<small> m</small>`;if($('#eta'))$('#eta').innerHTML=`${Math.max(0,Math.ceil((activeRoute.distance-travel)/(mode==='person'?1.2:3.5)))}<small> 초</small>`;if(pose.arrived){playing=false;$('#start').disabled=true;$('#start').innerHTML=`${icon('check')} 도착했습니다`;notify(`${activeRoute.destination.label}에 도착했습니다.`,'arrive');}}
 else if(keys.size){let turn=(keys.has('a')||keys.has('arrowleft')?1:0)-(keys.has('d')||keys.has('arrowright')?1:0);pose.heading+=turn*delta*1.8;let direction=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);const speed=mode==='car'?4:1.5;const next={...pose,x:pose.x+Math.sin(pose.heading)*direction*speed*delta,z:pose.z+Math.cos(pose.heading)*direction*speed*delta};if(canMove(plan,next,{mode,hazards}))pose=next;scene?.setPose(pose,mode);}
}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>b.dataset.nav==='map'?showMap():b.dataset.nav==='plans'?showLibrary():b.dataset.nav==='charging'?showCharging():loadLab());$('#lab-launch').onclick=loadLab;$('#back').onclick=showMap;$('#search').oninput=e=>siteList(e.target.value);
document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{mapStyle=b.dataset.map;document.querySelectorAll('[data-map]').forEach(x=>x.classList.toggle('selected',x===b));setScreen('map');$('#map-note').textContent=mapStyle==='city'?'3D 개념 지도 · 위치는 원문 좌표 기준, 건물 외형은 개념 모델':(googleView?.mode==='address-map'?'OpenStreetMap · 주소 마커를 눌러 3D 건물 보기':'Google 지도 · 원본 도면은 왼쪽 목록에서 선택');});
document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-model]').forEach(x=>x.classList.toggle('selected',x===b));$('#flat-plan').hidden=b.dataset.model!=='2d';if(b.dataset.model==='3d')scene?.showPlan(plan);if(b.dataset.model==='exterior'){scene?.showExterior(plan);notify('동일 평면을 5개 층으로 반복한 개념 매스입니다. 실제 층수·외관은 미확인입니다.');}});
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{camera=b.dataset.camera;scene?.setView(camera);document.querySelectorAll('[data-camera]').forEach(x=>x.classList.toggle('selected',x===b));});
$('#sound').onclick=async()=>{try{const enabled=await audio.toggle();$('#sound').setAttribute('aria-pressed',String(enabled));$('#sound').setAttribute('aria-label',enabled?'소리 안내 끄기':'소리 안내 켜기');notify(enabled?'소리 안내를 켰습니다.':'소리 안내를 껐습니다.');}catch{notify('이 브라우저에서 소리를 사용할 수 없습니다.');}};
$('#zoom-in').onclick=()=>scene?.camera.position.lerp(scene.controls.target,.15);$('#zoom-out').onclick=()=>scene?.camera.position.lerp(scene.controls.target,-.15);$('#reset-view').onclick=()=>{if(screen==='map')scene?.showCity(catalog);else if(screen==='lab')scene?.setView('orbit');else if(screen==='charging')scene?.setView('orbit');else if(plan)scene?.showPlan(plan);};
$('#about').onclick=()=>dialog('<div class="eyebrow">ABOUT THE RESEARCH</div><h2>도면에서 길을 찾습니다.</h2><p>공개 도면을 구조선으로 분석해 WebGL 공간으로 보여주는 연구용 앱입니다. 주차장 길찾기와 대피 기능은 별도의 검증용 도면에서 실행됩니다.</p><p>실제 도면은 축척·출입구·소방시설 검토가 필요합니다. Google 지도의 3D 건물 연동은 Maps JavaScript API 키를 설정하면 사용할 수 있습니다.</p><p>차량: <a href="https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CarConcept">CarConcept</a> · Eric Chadwick / Darmstadt Graphics Group GmbH · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. 색상·크기·유리 재질 조정. <a href="/models/NOTICE.md">자산 출처·변경 내역</a></p><a href="/reports/index.html">검증 결과 보기 ↗</a>');
$('#source-info').onclick=()=>dialog(`<div class="eyebrow">SOURCE & ANALYSIS</div><h2>${escape(plan?.name||'도면 분석')}</h2><p>원본의 어두운 직교 선분을 추출해 벽체 후보로 변환합니다. 텍스트나 치수선도 감지될 수 있어 검토가 필요하며, 문이나 통과 가능한 경로를 자동 확정하지 않습니다.</p><p>출처: ${selected?`<a href="${selected.source}" target="_blank" rel="noopener">${escape(selected.publisher)} ↗</a>`:'사용자가 가져온 도면'}</p><p>주차장 시험장에서는 축척·차로·동 입구·외부 집결지가 명시된 SVG를 분석합니다.</p>`);
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>15_000_000)return notify('15MB 이하의 도면을 선택해 주세요.');const version=++loadVersion;let url;try{let result;if(file.name.endsWith('.pdf')){pdfModule=await import('./graphics/pdf.js');await pdfDocument?.destroy();pdfDocument=await pdfModule.openPdf(await file.arrayBuffer());await renderPdf(1,file.name);return;}else if(file.name.endsWith('.svg'))result=analyzeSvg(await file.text());else if(file.name.endsWith('.json'))result=validatePlan(JSON.parse(await file.text()));else{url=URL.createObjectURL(file);const pixels=await imagePixels(url);result=analyzeBlueprint(pixels,{metersPerPixel:30/pixels.width});}if(version!==loadVersion)return;plan=result;plan.name=file.name;selected=null;setScreen('plan');scene?.showPlan(plan);$('#crumb').textContent=file.name;$('#crumb-title').textContent='가져온 도면';$('#flat-image').src=url||'';planInfo();notify('도면을 분석했습니다. 축척과 구조선을 확인하세요.');}catch(error){notify('도면을 읽지 못했습니다. '+error.message);}finally{$('#file').value='';}};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#search').focus();return;}if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||$('#dialog').open)return;const key=e.key.toLowerCase();if(screen==='lab'&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();if(playing){playing=false;$('#start').innerHTML=`${icon('play')} 안내 재개`;}if(!keys.has(key)){keys.add(key);update(1/60);}}});
document.addEventListener('keyup',e=>{const had=keys.delete(e.key.toLowerCase());if(had&&keys.size===0&&screen==='lab')planRoute();});window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();playing=false;}});
await prepareVehicle();
try{scene=new AtlasScene($('#world'),{onSelect:selectSite,onFrame:update,capture});}catch(e){$('#render-error').hidden=false;$('#render-error').textContent='3D를 시작하지 못했습니다. WebGL을 지원하는 브라우저에서 열어 주세요.';console.error(e);}
$('#world').addEventListener('atlas-error',e=>notify(e.detail));
try{const res=await fetch('/plans/catalog.json');if(!res.ok)throw new Error('자료를 읽지 못했습니다.');catalog=await res.json();const locations=await (await fetch('/plans/locations.json')).json();catalog=catalog.map(s=>({...s,mapLocation:locations[s.id]}));$('#catalog-count').textContent=catalog.length;$('#catalog-range').textContent=`01 — ${catalog.length}`;siteList();scene?.showCity(catalog);googleView=await createGoogleMap($('#google-map'),catalog,selectSite,{apiKey:import.meta.env.VITE_GOOGLE_MAPS_API_KEY,mapId:import.meta.env.VITE_GOOGLE_MAPS_MAP_ID});if(googleView.mode==='webgl')$('#map-note').textContent='Google 지도 · 3D 건물을 눌러 도면 분석으로 이동';else{$('[data-map=google]').innerHTML=icon('map')+' 주소 지도';$('#map-note').textContent=`OpenStreetMap · ${catalog.length}곳 주소 마커 · 유형별 3D 모델`;$('#explore-caption').hidden=true;}}catch(error){notify(error.message);}
setScreen('map');
setInterval(()=>{if(scene)$('#render-stats').innerHTML=`WEBGL 2 <b>·</b> ${capture?'—':scene.fps} FPS`;},1200);
window.__atlas={get state(){return {screen,mode,camera,pose:{...pose},playing,travel,hazards,route:activeRoute,plan,catalog,googleMode:googleView?.mode,audioEnabled:audio.enabled,mapModelCount:googleView?.models?.length,mapMarkerCount:googleView?.markers?.length,charging:charging?.state};},scene,loadLab,selectSite,get addressMap(){return googleView;}};
window.addEventListener('pagehide',()=>{charging?.dispose();scene?.dispose();googleView?.dispose();audio.dispose();});
